// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "nxauxiliariesx.h"

/////////////////////////////////////////////////////////////////////////////
// CNXAuxiliariesX

IMPLEMENT_DYNCREATE(CNXAuxiliariesX, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CNXAuxiliariesX properties

BOOL CNXAuxiliariesX::GetLowStatus()
{
	BOOL result;
	GetProperty(0x1, VT_BOOL, (void*)&result);
	return result;
}

void CNXAuxiliariesX::SetLowStatus(BOOL propVal)
{
	SetProperty(0x1, VT_BOOL, propVal);
}

BOOL CNXAuxiliariesX::GetEngagedStatus()
{
	BOOL result;
	GetProperty(0x2, VT_BOOL, (void*)&result);
	return result;
}

void CNXAuxiliariesX::SetEngagedStatus(BOOL propVal)
{
	SetProperty(0x2, VT_BOOL, propVal);
}

BOOL CNXAuxiliariesX::GetPoweringStatus()
{
	BOOL result;
	GetProperty(0x3, VT_BOOL, (void*)&result);
	return result;
}

void CNXAuxiliariesX::SetPoweringStatus(BOOL propVal)
{
	SetProperty(0x3, VT_BOOL, propVal);
}

BOOL CNXAuxiliariesX::GetRecoveredStatus()
{
	BOOL result;
	GetProperty(0x4, VT_BOOL, (void*)&result);
	return result;
}

void CNXAuxiliariesX::SetRecoveredStatus(BOOL propVal)
{
	SetProperty(0x4, VT_BOOL, propVal);
}

BOOL CNXAuxiliariesX::GetHasUPS()
{
	BOOL result;
	GetProperty(0x5, VT_BOOL, (void*)&result);
	return result;
}

void CNXAuxiliariesX::SetHasUPS(BOOL propVal)
{
	SetProperty(0x5, VT_BOOL, propVal);
}

BOOL CNXAuxiliariesX::GetCanLow()
{
	BOOL result;
	GetProperty(0x6, VT_BOOL, (void*)&result);
	return result;
}

void CNXAuxiliariesX::SetCanLow(BOOL propVal)
{
	SetProperty(0x6, VT_BOOL, propVal);
}

BOOL CNXAuxiliariesX::GetCanEngaged()
{
	BOOL result;
	GetProperty(0x7, VT_BOOL, (void*)&result);
	return result;
}

void CNXAuxiliariesX::SetCanEngaged(BOOL propVal)
{
	SetProperty(0x7, VT_BOOL, propVal);
}

BOOL CNXAuxiliariesX::GetCanPowering()
{
	BOOL result;
	GetProperty(0x8, VT_BOOL, (void*)&result);
	return result;
}

void CNXAuxiliariesX::SetCanPowering(BOOL propVal)
{
	SetProperty(0x8, VT_BOOL, propVal);
}

BOOL CNXAuxiliariesX::GetCanRecovered()
{
	BOOL result;
	GetProperty(0x9, VT_BOOL, (void*)&result);
	return result;
}

void CNXAuxiliariesX::SetCanRecovered(BOOL propVal)
{
	SetProperty(0x9, VT_BOOL, propVal);
}

short CNXAuxiliariesX::GetVolumeStatus()
{
	short result;
	GetProperty(0xa, VT_I2, (void*)&result);
	return result;
}

void CNXAuxiliariesX::SetVolumeStatus(short propVal)
{
	SetProperty(0xa, VT_I2, propVal);
}

short CNXAuxiliariesX::GetVolumeStep()
{
	short result;
	GetProperty(0xb, VT_I2, (void*)&result);
	return result;
}

void CNXAuxiliariesX::SetVolumeStep(short propVal)
{
	SetProperty(0xb, VT_I2, propVal);
}

CString CNXAuxiliariesX::GetDeviceStatus()
{
	CString result;
	GetProperty(0xc, VT_BSTR, (void*)&result);
	return result;
}

void CNXAuxiliariesX::SetDeviceStatus(LPCTSTR propVal)
{
	SetProperty(0xc, VT_BSTR, propVal);
}

CString CNXAuxiliariesX::GetGreenLedStatus()
{
	CString result;
	GetProperty(0xd, VT_BSTR, (void*)&result);
	return result;
}

void CNXAuxiliariesX::SetGreenLedStatus(LPCTSTR propVal)
{
	SetProperty(0xd, VT_BSTR, propVal);
}

CString CNXAuxiliariesX::GetAmberLedStatus()
{
	CString result;
	GetProperty(0xe, VT_BSTR, (void*)&result);
	return result;
}

void CNXAuxiliariesX::SetAmberLedStatus(LPCTSTR propVal)
{
	SetProperty(0xe, VT_BSTR, propVal);
}

CString CNXAuxiliariesX::GetRedLedStatus()
{
	CString result;
	GetProperty(0xf, VT_BSTR, (void*)&result);
	return result;
}

void CNXAuxiliariesX::SetRedLedStatus(LPCTSTR propVal)
{
	SetProperty(0xf, VT_BSTR, propVal);
}

CString CNXAuxiliariesX::GetAlarmStatus()
{
	CString result;
	GetProperty(0x10, VT_BSTR, (void*)&result);
	return result;
}

void CNXAuxiliariesX::SetAlarmStatus(LPCTSTR propVal)
{
	SetProperty(0x10, VT_BSTR, propVal);
}

CString CNXAuxiliariesX::GetEnhancedAudioCtrlStatus()
{
	CString result;
	GetProperty(0x11, VT_BSTR, (void*)&result);
	return result;
}

void CNXAuxiliariesX::SetEnhancedAudioCtrlStatus(LPCTSTR propVal)
{
	SetProperty(0x11, VT_BSTR, propVal);
}

BOOL CNXAuxiliariesX::GetHasRMSMonitor()
{
	BOOL result;
	GetProperty(0x12, VT_BOOL, (void*)&result);
	return result;
}

void CNXAuxiliariesX::SetHasRMSMonitor(BOOL propVal)
{
	SetProperty(0x12, VT_BOOL, propVal);
}

BOOL CNXAuxiliariesX::GetHasAlarm()
{
	BOOL result;
	GetProperty(0x13, VT_BOOL, (void*)&result);
	return result;
}

void CNXAuxiliariesX::SetHasAlarm(BOOL propVal)
{
	SetProperty(0x13, VT_BOOL, propVal);
}

BOOL CNXAuxiliariesX::GetHasEnhancedAudioCtrl()
{
	BOOL result;
	GetProperty(0x14, VT_BOOL, (void*)&result);
	return result;
}

void CNXAuxiliariesX::SetHasEnhancedAudioCtrl(BOOL propVal)
{
	SetProperty(0x14, VT_BOOL, propVal);
}

BOOL CNXAuxiliariesX::GetCanHeadsetDetection()
{
	BOOL result;
	GetProperty(0x15, VT_BOOL, (void*)&result);
	return result;
}

void CNXAuxiliariesX::SetCanHeadsetDetection(BOOL propVal)
{
	SetProperty(0x15, VT_BOOL, propVal);
}

BOOL CNXAuxiliariesX::GetCanModeControllable()
{
	BOOL result;
	GetProperty(0x16, VT_BOOL, (void*)&result);
	return result;
}

void CNXAuxiliariesX::SetCanModeControllable(BOOL propVal)
{
	SetProperty(0x16, VT_BOOL, propVal);
}

CString CNXAuxiliariesX::GetLogicalServiceName()
{
	CString result;
	GetProperty(0x17, VT_BSTR, (void*)&result);
	return result;
}

void CNXAuxiliariesX::SetLogicalServiceName(LPCTSTR propVal)
{
	SetProperty(0x17, VT_BSTR, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CNXAuxiliariesX operations

long CNXAuxiliariesX::OpenSessionSync(long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x18, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Timeout);
	return result;
}

long CNXAuxiliariesX::CloseSessionSync()
{
	long result;
	InvokeHelper(0x19, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXAuxiliariesX::RequestLock(long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x1a, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Timeout);
	return result;
}

long CNXAuxiliariesX::ReleaseLock()
{
	long result;
	InvokeHelper(0x1b, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXAuxiliariesX::Reset()
{
	long result;
	InvokeHelper(0x1c, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

CString CNXAuxiliariesX::GetExtraStatus(LPCTSTR KeyName)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x1d, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		KeyName);
	return result;
}

CString CNXAuxiliariesX::GetExtraCaps(LPCTSTR KeyName)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x1e, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		KeyName);
	return result;
}

long CNXAuxiliariesX::EngageUPS()
{
	long result;
	InvokeHelper(0x1f, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXAuxiliariesX::DisengageUPS()
{
	long result;
	InvokeHelper(0x20, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXAuxiliariesX::SetVolume(short Level)
{
	long result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x21, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Level);
	return result;
}

long CNXAuxiliariesX::SetAlarm(LPCTSTR State)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x22, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		State);
	return result;
}

long CNXAuxiliariesX::SetEnhancedAudioCtrl(LPCTSTR State)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x23, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		State);
	return result;
}

long CNXAuxiliariesX::SetRMSMonitor(LPCTSTR State)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x24, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		State);
	return result;
}
