#if !defined(AFX_NXAUXILIARIESX_H__3312547E_C8E7_4D9B_9BD5_49929C71FAF9__INCLUDED_)
#define AFX_NXAUXILIARIESX_H__3312547E_C8E7_4D9B_9BD5_49929C71FAF9__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CNXAuxiliariesX wrapper class

class CNXAuxiliariesX : public CWnd
{
protected:
	DECLARE_DYNCREATE(CNXAuxiliariesX)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x2a40c242, 0xc066, 0x4d90, { 0xac, 0xe4, 0x58, 0x5c, 0x8b, 0x7e, 0x22, 0x5f } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	BOOL GetLowStatus();
	void SetLowStatus(BOOL);
	BOOL GetEngagedStatus();
	void SetEngagedStatus(BOOL);
	BOOL GetPoweringStatus();
	void SetPoweringStatus(BOOL);
	BOOL GetRecoveredStatus();
	void SetRecoveredStatus(BOOL);
	BOOL GetHasUPS();
	void SetHasUPS(BOOL);
	BOOL GetCanLow();
	void SetCanLow(BOOL);
	BOOL GetCanEngaged();
	void SetCanEngaged(BOOL);
	BOOL GetCanPowering();
	void SetCanPowering(BOOL);
	BOOL GetCanRecovered();
	void SetCanRecovered(BOOL);
	short GetVolumeStatus();
	void SetVolumeStatus(short);
	short GetVolumeStep();
	void SetVolumeStep(short);
	CString GetDeviceStatus();
	void SetDeviceStatus(LPCTSTR);
	CString GetGreenLedStatus();
	void SetGreenLedStatus(LPCTSTR);
	CString GetAmberLedStatus();
	void SetAmberLedStatus(LPCTSTR);
	CString GetRedLedStatus();
	void SetRedLedStatus(LPCTSTR);
	CString GetAlarmStatus();
	void SetAlarmStatus(LPCTSTR);
	CString GetEnhancedAudioCtrlStatus();
	void SetEnhancedAudioCtrlStatus(LPCTSTR);
	BOOL GetHasRMSMonitor();
	void SetHasRMSMonitor(BOOL);
	BOOL GetHasAlarm();
	void SetHasAlarm(BOOL);
	BOOL GetHasEnhancedAudioCtrl();
	void SetHasEnhancedAudioCtrl(BOOL);
	BOOL GetCanHeadsetDetection();
	void SetCanHeadsetDetection(BOOL);
	BOOL GetCanModeControllable();
	void SetCanModeControllable(BOOL);
	CString GetLogicalServiceName();
	void SetLogicalServiceName(LPCTSTR);

// Operations
public:
	long OpenSessionSync(long Timeout);
	long CloseSessionSync();
	long RequestLock(long Timeout);
	long ReleaseLock();
	long Reset();
	CString GetExtraStatus(LPCTSTR KeyName);
	CString GetExtraCaps(LPCTSTR KeyName);
	long EngageUPS();
	long DisengageUPS();
	long SetVolume(short Level);
	long SetAlarm(LPCTSTR State);
	long SetEnhancedAudioCtrl(LPCTSTR State);
	long SetRMSMonitor(LPCTSTR State);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_NXAUXILIARIESX_H__3312547E_C8E7_4D9B_9BD5_49929C71FAF9__INCLUDED_)
