#if !defined(AFX_NXCASHACCEPTORX_H__02FA53D2_58BF_4A3E_A4BE_675F5887B6EC__INCLUDED_)
#define AFX_NXCASHACCEPTORX_H__02FA53D2_58BF_4A3E_A4BE_675F5887B6EC__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CNXCashAcceptorX wrapper class

class CNXCashAcceptorX : public CWnd
{
protected:
	DECLARE_DYNCREATE(CNXCashAcceptorX)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x449bcf97, 0x82d1, 0x4be2, { 0xbe, 0x54, 0x2e, 0x95, 0xcc, 0xfc, 0xe7, 0x37 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	CString GetDeviceStatus();
	void SetDeviceStatus(LPCTSTR);
	CString GetSafeDoorStatus();
	void SetSafeDoorStatus(LPCTSTR);
	CString GetStackerStatus();
	void SetStackerStatus(LPCTSTR);
	CString GetAcceptorStatus();
	void SetAcceptorStatus(LPCTSTR);
	CString GetReaderStatus();
	void SetReaderStatus(LPCTSTR);
	CString GetPositionStatus();
	void SetPositionStatus(LPCTSTR);
	CString GetShutterStatus();
	void SetShutterStatus(LPCTSTR);
	CString GetTransportStatus();
	void SetTransportStatus(LPCTSTR);
	long GetNumberOfPositions();
	void SetNumberOfPositions(long);
	CString GetDeviceType();
	void SetDeviceType(LPCTSTR);
	long GetMaxCashInItem();
	void SetMaxCashInItem(long);
	BOOL GetHasSafeDoor();
	void SetHasSafeDoor(BOOL);
	BOOL GetHasShutter();
	void SetHasShutter(BOOL);
	BOOL GetCanShutterControl();
	void SetCanShutterControl(BOOL);
	long GetMaxStackerItem();
	void SetMaxStackerItem(long);
	BOOL GetHasTakenSensor();
	void SetHasTakenSensor(BOOL);
	BOOL GetHasInsertedSensor();
	void SetHasInsertedSensor(BOOL);
	VARIANT GetHasPositions();
	void SetHasPositions(const VARIANT&);
	VARIANT GetExchangeType();
	void SetExchangeType(const VARIANT&);
	VARIANT GetRetractAreas();
	void SetRetractAreas(const VARIANT&);
	long GetNumberOfItemType();
	void SetNumberOfItemType(long);
	BOOL GetCashUnitChangeInprogress();
	void SetCashUnitChangeInprogress(BOOL);
	CString GetLastCashInStatus();
	void SetLastCashInStatus(LPCTSTR);
	long GetNumberOfCashInStatus();
	void SetNumberOfCashInStatus(long);
	long GetNumberOfLogicalUnit();
	void SetNumberOfLogicalUnit(long);
	long GetLastRefusedCount();
	void SetLastRefusedCount(long);
	long GetNumberOfP6Info();
	void SetNumberOfP6Info(long);
	CString GetRefusedReason();
	void SetRefusedReason(LPCTSTR);
	BOOL GetCanPowerSaveControl();
	void SetCanPowerSaveControl(BOOL);
	short GetPowerSaveRecoveryTime();
	void SetPowerSaveRecoveryTime(short);
	CString GetDevicePositionStatus();
	void SetDevicePositionStatus(LPCTSTR);
	short GetNumberOfLevel2ItemInfo();
	void SetNumberOfLevel2ItemInfo(short);
	short GetNumberOfLevel3ItemInfo();
	void SetNumberOfLevel3ItemInfo(short);
	short GetNumberOfLevel4ItemInfo();
	void SetNumberOfLevel4ItemInfo(short);

// Operations
public:
	long OpenSessionSync(long Timeout);
	long CloseSessionSync();
	long RequestLock(long Timeout);
	long ReleaseLock();
	CString GetExtraStatus(LPCTSTR KeyName);
	CString GetExtraCaps(LPCTSTR KeyName);
	long StartCashIn();
	long AcceptCash(long InsertionTimeOut, long TakenTimeOut);
	long CancelAccept();
	long StoreCash();
	long RollbackCash(long TakenTimeOut);
	long Retract(short RetractAreas);
	long OpenShutter(long Position);
	long CloseShutter(long Position);
	long StartExchangeSync(const VARIANT& CashUnitToExchange);
	long EndExchangeSync();
	long OpenSafeDoor();
	long Reset(short UnitNumber);
	long ConfigureNoteTypeSync();
	LPDISPATCH GetPositions(long Index);
	LPDISPATCH GetItemType(long Index);
	LPDISPATCH GetCashInStatus(long Index);
	LPDISPATCH GetLogicalUnit(long Index);
	LPDISPATCH GetP6Info(long Index);
	long CreateP6Signature(long InsertionTimeOut, long TakenTimeOut);
	long GetP6Signature(LPCTSTR Level, short Index);
	long ConfigureCashUnitSync(short Number, LPCTSTR Type, const VARIANT& NoteIDs);
	long SetCashUnitInfo();
	long SetCashInLimit(long TotalItemsLimit, LPCTSTR CurrencyID, long Amount);
	long Replenish(long SourceNumber, const VARIANT& TargetNumbers, const VARIANT& NumberOfItemsToMove);
	long StartExchangeSyncEx(short ExchangeType, const VARIANT& CashUnitToExchange);
	long Present(long TakenTimeOut);
	BOOL RegisterXFSEvent(long Command);
	long Cancel();
	long PowerSaveControl(short MaxPowerSaveRecoveryTime);
	long SetGuidLight(short LightIndex, long Command);
	long GetGuidLightsType(short GuidLightIndex);
	long GetGuidLightStatus(short GuidLightIndex);
	long StartCashInEx(short TellerID, long UseRecycleUnits, LPCTSTR InputPosition, LPCTSTR OutputPosition);
	long SetMixedMode(long UseMixed);
	long CancelReplenish();
	long RetractEx(short RetractAreas, short Index);
	long ResetEx(short UnitNumber, short RetractAreas, short Index);
	CString GetItemInfo(LPCTSTR Level, short Index, LPCTSTR ItemInfoType);
	long PresentEx(short fwPosition, long TakenTimeOut);
};

/////////////////////////////////////////////////////////////////////////////
// IPositions wrapper class

class IPositions : public COleDispatchDriver
{
public:
	IPositions() {}		// Calls COleDispatchDriver default constructor
	IPositions(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	IPositions(const IPositions& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CString GetType();
	CString GetPositionStatus();
	CString GetShutterStatus();
	CString GetTransportStatus();
};
/////////////////////////////////////////////////////////////////////////////
// IItemType wrapper class

class IItemType : public COleDispatchDriver
{
public:
	IItemType() {}		// Calls COleDispatchDriver default constructor
	IItemType(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	IItemType(const IItemType& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetId();
	long GetValue();
	CString GetCurrency();
	long GetExponent();
	long GetConfigured();
	void SetConfigured(long nNewValue);
};
/////////////////////////////////////////////////////////////////////////////
// ICashInStatus wrapper class

class ICashInStatus : public COleDispatchDriver
{
public:
	ICashInStatus() {}		// Calls COleDispatchDriver default constructor
	ICashInStatus(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	ICashInStatus(const ICashInStatus& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetId();
	long GetValue();
	CString GetCurrency();
	long GetExponent();
	long GetItemCount();
};
/////////////////////////////////////////////////////////////////////////////
// ILogicalUnit wrapper class

class ILogicalUnit : public COleDispatchDriver
{
public:
	ILogicalUnit() {}		// Calls COleDispatchDriver default constructor
	ILogicalUnit(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	ILogicalUnit(const ILogicalUnit& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetNumber();
	CString GetType();
	long GetTotalCount();
	void SetTotalCount(long nNewValue);
	long GetMaximumCount();
	void SetMaximumCount(long nNewValue);
	CString GetStatus();
	long GetCashInCount();
	void SetCashInCount(long nNewValue);
	CString GetUnitID();
	long GetNumberOfItem();
	VARIANT GetItemID();
	VARIANT GetItemCount();
	VARIANT GetItemValue();
	VARIANT GetItemConfigured();
	long GetNumberOfPCU();
	VARIANT GetPcuid();
	VARIANT GetPCUCashInCount();
	void SetPCUCashInCount(const VARIANT& newValue);
	VARIANT GetPCUTotalCount();
	void SetPCUTotalCount(const VARIANT& newValue);
	VARIANT GetPCUMaximumCount();
	VARIANT GetPCUStatus();
	VARIANT GetPCUSensor();
	CString GetCurrencyID();
	void SetType(LPCTSTR lpszNewValue);
	void SetNumberOfItem(long nNewValue);
	void SetItemID(const VARIANT& newValue);
	void SetItemCount(const VARIANT& newValue);
	VARIANT GetPCUPositionName();
	CString GetCashUnitName();
	void SetCashUnitName(BSTR* newValue);
	long GetInitialCount();
	void SetInitialCount(long nNewValue);
	long GetDispensedCount();
	void SetDispensedCount(long nNewValue);
	long GetPresentedCount();
	void SetPresentedCount(long nNewValue);
	long GetRetractedCount();
	void SetRetractedCount(long nNewValue);
	long GetRejectCount();
	void SetRejectCount(long nNewValue);
	VARIANT GetPCUInitialCount();
	void SetPCUInitialCount(const VARIANT& newValue);
	VARIANT GetPCUDispensedCount();
	void SetPCUDispensedCount(const VARIANT& newValue);
	VARIANT GetPCUPresentedCount();
	void SetPCUPresentedCount(const VARIANT& newValue);
	VARIANT GetPCURetractedCount();
	void SetPCURetractedCount(const VARIANT& newValue);
	VARIANT GetPCURejectCount();
	void SetPCURejectCount(const VARIANT& newValue);
	void SetCurrencyID(LPCTSTR lpszNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_NXCASHACCEPTORX_H__02FA53D2_58BF_4A3E_A4BE_675F5887B6EC__INCLUDED_)
