// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "nxcashacceptorx.h"

/////////////////////////////////////////////////////////////////////////////
// CNXCashAcceptorX

IMPLEMENT_DYNCREATE(CNXCashAcceptorX, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CNXCashAcceptorX properties

CString CNXCashAcceptorX::GetDeviceStatus()
{
	CString result;
	GetProperty(0x1, VT_BSTR, (void*)&result);
	return result;
}

void CNXCashAcceptorX::SetDeviceStatus(LPCTSTR propVal)
{
	SetProperty(0x1, VT_BSTR, propVal);
}

CString CNXCashAcceptorX::GetSafeDoorStatus()
{
	CString result;
	GetProperty(0x2, VT_BSTR, (void*)&result);
	return result;
}

void CNXCashAcceptorX::SetSafeDoorStatus(LPCTSTR propVal)
{
	SetProperty(0x2, VT_BSTR, propVal);
}

CString CNXCashAcceptorX::GetStackerStatus()
{
	CString result;
	GetProperty(0x3, VT_BSTR, (void*)&result);
	return result;
}

void CNXCashAcceptorX::SetStackerStatus(LPCTSTR propVal)
{
	SetProperty(0x3, VT_BSTR, propVal);
}

CString CNXCashAcceptorX::GetAcceptorStatus()
{
	CString result;
	GetProperty(0x4, VT_BSTR, (void*)&result);
	return result;
}

void CNXCashAcceptorX::SetAcceptorStatus(LPCTSTR propVal)
{
	SetProperty(0x4, VT_BSTR, propVal);
}

CString CNXCashAcceptorX::GetReaderStatus()
{
	CString result;
	GetProperty(0x5, VT_BSTR, (void*)&result);
	return result;
}

void CNXCashAcceptorX::SetReaderStatus(LPCTSTR propVal)
{
	SetProperty(0x5, VT_BSTR, propVal);
}

CString CNXCashAcceptorX::GetPositionStatus()
{
	CString result;
	GetProperty(0x6, VT_BSTR, (void*)&result);
	return result;
}

void CNXCashAcceptorX::SetPositionStatus(LPCTSTR propVal)
{
	SetProperty(0x6, VT_BSTR, propVal);
}

CString CNXCashAcceptorX::GetShutterStatus()
{
	CString result;
	GetProperty(0x7, VT_BSTR, (void*)&result);
	return result;
}

void CNXCashAcceptorX::SetShutterStatus(LPCTSTR propVal)
{
	SetProperty(0x7, VT_BSTR, propVal);
}

CString CNXCashAcceptorX::GetTransportStatus()
{
	CString result;
	GetProperty(0x8, VT_BSTR, (void*)&result);
	return result;
}

void CNXCashAcceptorX::SetTransportStatus(LPCTSTR propVal)
{
	SetProperty(0x8, VT_BSTR, propVal);
}

long CNXCashAcceptorX::GetNumberOfPositions()
{
	long result;
	GetProperty(0x9, VT_I4, (void*)&result);
	return result;
}

void CNXCashAcceptorX::SetNumberOfPositions(long propVal)
{
	SetProperty(0x9, VT_I4, propVal);
}

CString CNXCashAcceptorX::GetDeviceType()
{
	CString result;
	GetProperty(0xa, VT_BSTR, (void*)&result);
	return result;
}

void CNXCashAcceptorX::SetDeviceType(LPCTSTR propVal)
{
	SetProperty(0xa, VT_BSTR, propVal);
}

long CNXCashAcceptorX::GetMaxCashInItem()
{
	long result;
	GetProperty(0xb, VT_I4, (void*)&result);
	return result;
}

void CNXCashAcceptorX::SetMaxCashInItem(long propVal)
{
	SetProperty(0xb, VT_I4, propVal);
}

BOOL CNXCashAcceptorX::GetHasSafeDoor()
{
	BOOL result;
	GetProperty(0xc, VT_BOOL, (void*)&result);
	return result;
}

void CNXCashAcceptorX::SetHasSafeDoor(BOOL propVal)
{
	SetProperty(0xc, VT_BOOL, propVal);
}

BOOL CNXCashAcceptorX::GetHasShutter()
{
	BOOL result;
	GetProperty(0xd, VT_BOOL, (void*)&result);
	return result;
}

void CNXCashAcceptorX::SetHasShutter(BOOL propVal)
{
	SetProperty(0xd, VT_BOOL, propVal);
}

BOOL CNXCashAcceptorX::GetCanShutterControl()
{
	BOOL result;
	GetProperty(0xe, VT_BOOL, (void*)&result);
	return result;
}

void CNXCashAcceptorX::SetCanShutterControl(BOOL propVal)
{
	SetProperty(0xe, VT_BOOL, propVal);
}

long CNXCashAcceptorX::GetMaxStackerItem()
{
	long result;
	GetProperty(0xf, VT_I4, (void*)&result);
	return result;
}

void CNXCashAcceptorX::SetMaxStackerItem(long propVal)
{
	SetProperty(0xf, VT_I4, propVal);
}

BOOL CNXCashAcceptorX::GetHasTakenSensor()
{
	BOOL result;
	GetProperty(0x10, VT_BOOL, (void*)&result);
	return result;
}

void CNXCashAcceptorX::SetHasTakenSensor(BOOL propVal)
{
	SetProperty(0x10, VT_BOOL, propVal);
}

BOOL CNXCashAcceptorX::GetHasInsertedSensor()
{
	BOOL result;
	GetProperty(0x11, VT_BOOL, (void*)&result);
	return result;
}

void CNXCashAcceptorX::SetHasInsertedSensor(BOOL propVal)
{
	SetProperty(0x11, VT_BOOL, propVal);
}

VARIANT CNXCashAcceptorX::GetHasPositions()
{
	VARIANT result;
	GetProperty(0x12, VT_VARIANT, (void*)&result);
	return result;
}

void CNXCashAcceptorX::SetHasPositions(const VARIANT& propVal)
{
	SetProperty(0x12, VT_VARIANT, &propVal);
}

VARIANT CNXCashAcceptorX::GetExchangeType()
{
	VARIANT result;
	GetProperty(0x13, VT_VARIANT, (void*)&result);
	return result;
}

void CNXCashAcceptorX::SetExchangeType(const VARIANT& propVal)
{
	SetProperty(0x13, VT_VARIANT, &propVal);
}

VARIANT CNXCashAcceptorX::GetRetractAreas()
{
	VARIANT result;
	GetProperty(0x14, VT_VARIANT, (void*)&result);
	return result;
}

void CNXCashAcceptorX::SetRetractAreas(const VARIANT& propVal)
{
	SetProperty(0x14, VT_VARIANT, &propVal);
}

long CNXCashAcceptorX::GetNumberOfItemType()
{
	long result;
	GetProperty(0x15, VT_I4, (void*)&result);
	return result;
}

void CNXCashAcceptorX::SetNumberOfItemType(long propVal)
{
	SetProperty(0x15, VT_I4, propVal);
}

BOOL CNXCashAcceptorX::GetCashUnitChangeInprogress()
{
	BOOL result;
	GetProperty(0x16, VT_BOOL, (void*)&result);
	return result;
}

void CNXCashAcceptorX::SetCashUnitChangeInprogress(BOOL propVal)
{
	SetProperty(0x16, VT_BOOL, propVal);
}

CString CNXCashAcceptorX::GetLastCashInStatus()
{
	CString result;
	GetProperty(0x17, VT_BSTR, (void*)&result);
	return result;
}

void CNXCashAcceptorX::SetLastCashInStatus(LPCTSTR propVal)
{
	SetProperty(0x17, VT_BSTR, propVal);
}

long CNXCashAcceptorX::GetNumberOfCashInStatus()
{
	long result;
	GetProperty(0x18, VT_I4, (void*)&result);
	return result;
}

void CNXCashAcceptorX::SetNumberOfCashInStatus(long propVal)
{
	SetProperty(0x18, VT_I4, propVal);
}

long CNXCashAcceptorX::GetNumberOfLogicalUnit()
{
	long result;
	GetProperty(0x19, VT_I4, (void*)&result);
	return result;
}

void CNXCashAcceptorX::SetNumberOfLogicalUnit(long propVal)
{
	SetProperty(0x19, VT_I4, propVal);
}

long CNXCashAcceptorX::GetLastRefusedCount()
{
	long result;
	GetProperty(0x1a, VT_I4, (void*)&result);
	return result;
}

void CNXCashAcceptorX::SetLastRefusedCount(long propVal)
{
	SetProperty(0x1a, VT_I4, propVal);
}

long CNXCashAcceptorX::GetNumberOfP6Info()
{
	long result;
	GetProperty(0x36, VT_I4, (void*)&result);
	return result;
}

void CNXCashAcceptorX::SetNumberOfP6Info(long propVal)
{
	SetProperty(0x36, VT_I4, propVal);
}

CString CNXCashAcceptorX::GetRefusedReason()
{
	CString result;
	GetProperty(0x3c, VT_BSTR, (void*)&result);
	return result;
}

void CNXCashAcceptorX::SetRefusedReason(LPCTSTR propVal)
{
	SetProperty(0x3c, VT_BSTR, propVal);
}

BOOL CNXCashAcceptorX::GetCanPowerSaveControl()
{
	BOOL result;
	GetProperty(0x3f, VT_BOOL, (void*)&result);
	return result;
}

void CNXCashAcceptorX::SetCanPowerSaveControl(BOOL propVal)
{
	SetProperty(0x3f, VT_BOOL, propVal);
}

short CNXCashAcceptorX::GetPowerSaveRecoveryTime()
{
	short result;
	GetProperty(0x40, VT_I2, (void*)&result);
	return result;
}

void CNXCashAcceptorX::SetPowerSaveRecoveryTime(short propVal)
{
	SetProperty(0x40, VT_I2, propVal);
}

CString CNXCashAcceptorX::GetDevicePositionStatus()
{
	CString result;
	GetProperty(0x41, VT_BSTR, (void*)&result);
	return result;
}

void CNXCashAcceptorX::SetDevicePositionStatus(LPCTSTR propVal)
{
	SetProperty(0x41, VT_BSTR, propVal);
}

short CNXCashAcceptorX::GetNumberOfLevel2ItemInfo()
{
	short result;
	GetProperty(0x4c, VT_I2, (void*)&result);
	return result;
}

void CNXCashAcceptorX::SetNumberOfLevel2ItemInfo(short propVal)
{
	SetProperty(0x4c, VT_I2, propVal);
}

short CNXCashAcceptorX::GetNumberOfLevel3ItemInfo()
{
	short result;
	GetProperty(0x4d, VT_I2, (void*)&result);
	return result;
}

void CNXCashAcceptorX::SetNumberOfLevel3ItemInfo(short propVal)
{
	SetProperty(0x4d, VT_I2, propVal);
}

short CNXCashAcceptorX::GetNumberOfLevel4ItemInfo()
{
	short result;
	GetProperty(0x4e, VT_I2, (void*)&result);
	return result;
}

void CNXCashAcceptorX::SetNumberOfLevel4ItemInfo(short propVal)
{
	SetProperty(0x4e, VT_I2, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CNXCashAcceptorX operations

long CNXCashAcceptorX::OpenSessionSync(long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x1b, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Timeout);
	return result;
}

long CNXCashAcceptorX::CloseSessionSync()
{
	long result;
	InvokeHelper(0x1c, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXCashAcceptorX::RequestLock(long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x1d, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Timeout);
	return result;
}

long CNXCashAcceptorX::ReleaseLock()
{
	long result;
	InvokeHelper(0x1e, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

CString CNXCashAcceptorX::GetExtraStatus(LPCTSTR KeyName)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x1f, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		KeyName);
	return result;
}

CString CNXCashAcceptorX::GetExtraCaps(LPCTSTR KeyName)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x20, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		KeyName);
	return result;
}

long CNXCashAcceptorX::StartCashIn()
{
	long result;
	InvokeHelper(0x21, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXCashAcceptorX::AcceptCash(long InsertionTimeOut, long TakenTimeOut)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0x22, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		InsertionTimeOut, TakenTimeOut);
	return result;
}

long CNXCashAcceptorX::CancelAccept()
{
	long result;
	InvokeHelper(0x23, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXCashAcceptorX::StoreCash()
{
	long result;
	InvokeHelper(0x24, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXCashAcceptorX::RollbackCash(long TakenTimeOut)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x25, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		TakenTimeOut);
	return result;
}

long CNXCashAcceptorX::Retract(short RetractAreas)
{
	long result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x26, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		RetractAreas);
	return result;
}

long CNXCashAcceptorX::OpenShutter(long Position)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x27, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Position);
	return result;
}

long CNXCashAcceptorX::CloseShutter(long Position)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x28, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Position);
	return result;
}

long CNXCashAcceptorX::StartExchangeSync(const VARIANT& CashUnitToExchange)
{
	long result;
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x29, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		&CashUnitToExchange);
	return result;
}

long CNXCashAcceptorX::EndExchangeSync()
{
	long result;
	InvokeHelper(0x2a, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXCashAcceptorX::OpenSafeDoor()
{
	long result;
	InvokeHelper(0x2b, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXCashAcceptorX::Reset(short UnitNumber)
{
	long result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x2c, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		UnitNumber);
	return result;
}

long CNXCashAcceptorX::ConfigureNoteTypeSync()
{
	long result;
	InvokeHelper(0x2d, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

LPDISPATCH CNXCashAcceptorX::GetPositions(long Index)
{
	LPDISPATCH result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x2e, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&result, parms,
		Index);
	return result;
}

LPDISPATCH CNXCashAcceptorX::GetItemType(long Index)
{
	LPDISPATCH result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x2f, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&result, parms,
		Index);
	return result;
}

LPDISPATCH CNXCashAcceptorX::GetCashInStatus(long Index)
{
	LPDISPATCH result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x30, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&result, parms,
		Index);
	return result;
}

LPDISPATCH CNXCashAcceptorX::GetLogicalUnit(long Index)
{
	LPDISPATCH result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x31, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&result, parms,
		Index);
	return result;
}

LPDISPATCH CNXCashAcceptorX::GetP6Info(long Index)
{
	LPDISPATCH result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x32, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&result, parms,
		Index);
	return result;
}

long CNXCashAcceptorX::CreateP6Signature(long InsertionTimeOut, long TakenTimeOut)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0x33, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		InsertionTimeOut, TakenTimeOut);
	return result;
}

long CNXCashAcceptorX::GetP6Signature(LPCTSTR Level, short Index)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_I2;
	InvokeHelper(0x34, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Level, Index);
	return result;
}

long CNXCashAcceptorX::ConfigureCashUnitSync(short Number, LPCTSTR Type, const VARIANT& NoteIDs)
{
	long result;
	static BYTE parms[] =
		VTS_I2 VTS_BSTR VTS_VARIANT;
	InvokeHelper(0x35, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Number, Type, &NoteIDs);
	return result;
}

long CNXCashAcceptorX::SetCashUnitInfo()
{
	long result;
	InvokeHelper(0x37, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXCashAcceptorX::SetCashInLimit(long TotalItemsLimit, LPCTSTR CurrencyID, long Amount)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_BSTR VTS_I4;
	InvokeHelper(0x38, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		TotalItemsLimit, CurrencyID, Amount);
	return result;
}

long CNXCashAcceptorX::Replenish(long SourceNumber, const VARIANT& TargetNumbers, const VARIANT& NumberOfItemsToMove)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_VARIANT VTS_VARIANT;
	InvokeHelper(0x39, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		SourceNumber, &TargetNumbers, &NumberOfItemsToMove);
	return result;
}

long CNXCashAcceptorX::StartExchangeSyncEx(short ExchangeType, const VARIANT& CashUnitToExchange)
{
	long result;
	static BYTE parms[] =
		VTS_I2 VTS_VARIANT;
	InvokeHelper(0x3a, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		ExchangeType, &CashUnitToExchange);
	return result;
}

long CNXCashAcceptorX::Present(long TakenTimeOut)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x3b, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		TakenTimeOut);
	return result;
}

BOOL CNXCashAcceptorX::RegisterXFSEvent(long Command)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x3d, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		Command);
	return result;
}

long CNXCashAcceptorX::Cancel()
{
	long result;
	InvokeHelper(0x3e, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXCashAcceptorX::PowerSaveControl(short MaxPowerSaveRecoveryTime)
{
	long result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x42, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		MaxPowerSaveRecoveryTime);
	return result;
}

long CNXCashAcceptorX::SetGuidLight(short LightIndex, long Command)
{
	long result;
	static BYTE parms[] =
		VTS_I2 VTS_I4;
	InvokeHelper(0x43, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		LightIndex, Command);
	return result;
}

long CNXCashAcceptorX::GetGuidLightsType(short GuidLightIndex)
{
	long result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x44, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, parms,
		GuidLightIndex);
	return result;
}

long CNXCashAcceptorX::GetGuidLightStatus(short GuidLightIndex)
{
	long result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x45, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, parms,
		GuidLightIndex);
	return result;
}

long CNXCashAcceptorX::StartCashInEx(short TellerID, long UseRecycleUnits, LPCTSTR InputPosition, LPCTSTR OutputPosition)
{
	long result;
	static BYTE parms[] =
		VTS_I2 VTS_I4 VTS_BSTR VTS_BSTR;
	InvokeHelper(0x46, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		TellerID, UseRecycleUnits, InputPosition, OutputPosition);
	return result;
}

long CNXCashAcceptorX::SetMixedMode(long UseMixed)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x47, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		UseMixed);
	return result;
}

long CNXCashAcceptorX::CancelReplenish()
{
	long result;
	InvokeHelper(0x48, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXCashAcceptorX::RetractEx(short RetractAreas, short Index)
{
	long result;
	static BYTE parms[] =
		VTS_I2 VTS_I2;
	InvokeHelper(0x49, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		RetractAreas, Index);
	return result;
}

long CNXCashAcceptorX::ResetEx(short UnitNumber, short RetractAreas, short Index)
{
	long result;
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_I2;
	InvokeHelper(0x4a, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		UnitNumber, RetractAreas, Index);
	return result;
}

CString CNXCashAcceptorX::GetItemInfo(LPCTSTR Level, short Index, LPCTSTR ItemInfoType)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR VTS_I2 VTS_BSTR;
	InvokeHelper(0x4b, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		Level, Index, ItemInfoType);
	return result;
}

long CNXCashAcceptorX::PresentEx(short fwPosition, long TakenTimeOut)
{
	long result;
	static BYTE parms[] =
		VTS_I2 VTS_I4;
	InvokeHelper(0x4f, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		fwPosition, TakenTimeOut);
	return result;
}


/////////////////////////////////////////////////////////////////////////////
// IPositions properties

/////////////////////////////////////////////////////////////////////////////
// IPositions operations

CString IPositions::GetType()
{
	CString result;
	InvokeHelper(0x1, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString IPositions::GetPositionStatus()
{
	CString result;
	InvokeHelper(0x2, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString IPositions::GetShutterStatus()
{
	CString result;
	InvokeHelper(0x3, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString IPositions::GetTransportStatus()
{
	CString result;
	InvokeHelper(0x4, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}


/////////////////////////////////////////////////////////////////////////////
// IItemType properties

/////////////////////////////////////////////////////////////////////////////
// IItemType operations

long IItemType::GetId()
{
	long result;
	InvokeHelper(0x1, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

long IItemType::GetValue()
{
	long result;
	InvokeHelper(0x2, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

CString IItemType::GetCurrency()
{
	CString result;
	InvokeHelper(0x3, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

long IItemType::GetExponent()
{
	long result;
	InvokeHelper(0x4, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

long IItemType::GetConfigured()
{
	long result;
	InvokeHelper(0x5, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void IItemType::SetConfigured(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x5, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}


/////////////////////////////////////////////////////////////////////////////
// ICashInStatus properties

/////////////////////////////////////////////////////////////////////////////
// ICashInStatus operations

long ICashInStatus::GetId()
{
	long result;
	InvokeHelper(0x1, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

long ICashInStatus::GetValue()
{
	long result;
	InvokeHelper(0x2, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

CString ICashInStatus::GetCurrency()
{
	CString result;
	InvokeHelper(0x3, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

long ICashInStatus::GetExponent()
{
	long result;
	InvokeHelper(0x4, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

long ICashInStatus::GetItemCount()
{
	long result;
	InvokeHelper(0x5, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}


/////////////////////////////////////////////////////////////////////////////
// ILogicalUnit properties

/////////////////////////////////////////////////////////////////////////////
// ILogicalUnit operations

long ILogicalUnit::GetNumber()
{
	long result;
	InvokeHelper(0x1, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

CString ILogicalUnit::GetType()
{
	CString result;
	InvokeHelper(0x2, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

long ILogicalUnit::GetTotalCount()
{
	long result;
	InvokeHelper(0x3, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void ILogicalUnit::SetTotalCount(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x3, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long ILogicalUnit::GetMaximumCount()
{
	long result;
	InvokeHelper(0x4, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void ILogicalUnit::SetMaximumCount(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x4, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

CString ILogicalUnit::GetStatus()
{
	CString result;
	InvokeHelper(0x5, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

long ILogicalUnit::GetCashInCount()
{
	long result;
	InvokeHelper(0x6, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void ILogicalUnit::SetCashInCount(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x6, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

CString ILogicalUnit::GetUnitID()
{
	CString result;
	InvokeHelper(0x7, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

long ILogicalUnit::GetNumberOfItem()
{
	long result;
	InvokeHelper(0x8, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

VARIANT ILogicalUnit::GetItemID()
{
	VARIANT result;
	InvokeHelper(0x9, DISPATCH_PROPERTYGET, VT_VARIANT, (void*)&result, NULL);
	return result;
}

VARIANT ILogicalUnit::GetItemCount()
{
	VARIANT result;
	InvokeHelper(0xa, DISPATCH_PROPERTYGET, VT_VARIANT, (void*)&result, NULL);
	return result;
}

VARIANT ILogicalUnit::GetItemValue()
{
	VARIANT result;
	InvokeHelper(0xb, DISPATCH_PROPERTYGET, VT_VARIANT, (void*)&result, NULL);
	return result;
}

VARIANT ILogicalUnit::GetItemConfigured()
{
	VARIANT result;
	InvokeHelper(0xc, DISPATCH_PROPERTYGET, VT_VARIANT, (void*)&result, NULL);
	return result;
}

long ILogicalUnit::GetNumberOfPCU()
{
	long result;
	InvokeHelper(0xd, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

VARIANT ILogicalUnit::GetPcuid()
{
	VARIANT result;
	InvokeHelper(0xe, DISPATCH_PROPERTYGET, VT_VARIANT, (void*)&result, NULL);
	return result;
}

VARIANT ILogicalUnit::GetPCUCashInCount()
{
	VARIANT result;
	InvokeHelper(0xf, DISPATCH_PROPERTYGET, VT_VARIANT, (void*)&result, NULL);
	return result;
}

void ILogicalUnit::SetPCUCashInCount(const VARIANT& newValue)
{
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0xf, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 &newValue);
}

VARIANT ILogicalUnit::GetPCUTotalCount()
{
	VARIANT result;
	InvokeHelper(0x10, DISPATCH_PROPERTYGET, VT_VARIANT, (void*)&result, NULL);
	return result;
}

void ILogicalUnit::SetPCUTotalCount(const VARIANT& newValue)
{
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x10, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 &newValue);
}

VARIANT ILogicalUnit::GetPCUMaximumCount()
{
	VARIANT result;
	InvokeHelper(0x11, DISPATCH_PROPERTYGET, VT_VARIANT, (void*)&result, NULL);
	return result;
}

VARIANT ILogicalUnit::GetPCUStatus()
{
	VARIANT result;
	InvokeHelper(0x12, DISPATCH_PROPERTYGET, VT_VARIANT, (void*)&result, NULL);
	return result;
}

VARIANT ILogicalUnit::GetPCUSensor()
{
	VARIANT result;
	InvokeHelper(0x13, DISPATCH_PROPERTYGET, VT_VARIANT, (void*)&result, NULL);
	return result;
}

CString ILogicalUnit::GetCurrencyID()
{
	CString result;
	InvokeHelper(0x14, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void ILogicalUnit::SetType(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x2, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

void ILogicalUnit::SetNumberOfItem(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x8, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

void ILogicalUnit::SetItemID(const VARIANT& newValue)
{
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x9, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 &newValue);
}

void ILogicalUnit::SetItemCount(const VARIANT& newValue)
{
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0xa, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 &newValue);
}

VARIANT ILogicalUnit::GetPCUPositionName()
{
	VARIANT result;
	InvokeHelper(0x15, DISPATCH_PROPERTYGET, VT_VARIANT, (void*)&result, NULL);
	return result;
}

CString ILogicalUnit::GetCashUnitName()
{
	CString result;
	InvokeHelper(0x16, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void ILogicalUnit::SetCashUnitName(BSTR* newValue)
{
	static BYTE parms[] =
		VTS_PBSTR;
	InvokeHelper(0x16, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

long ILogicalUnit::GetInitialCount()
{
	long result;
	InvokeHelper(0x17, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void ILogicalUnit::SetInitialCount(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x17, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long ILogicalUnit::GetDispensedCount()
{
	long result;
	InvokeHelper(0x18, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void ILogicalUnit::SetDispensedCount(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x18, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long ILogicalUnit::GetPresentedCount()
{
	long result;
	InvokeHelper(0x19, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void ILogicalUnit::SetPresentedCount(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x19, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long ILogicalUnit::GetRetractedCount()
{
	long result;
	InvokeHelper(0x1a, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void ILogicalUnit::SetRetractedCount(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x1a, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long ILogicalUnit::GetRejectCount()
{
	long result;
	InvokeHelper(0x1b, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void ILogicalUnit::SetRejectCount(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x1b, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

VARIANT ILogicalUnit::GetPCUInitialCount()
{
	VARIANT result;
	InvokeHelper(0x1c, DISPATCH_PROPERTYGET, VT_VARIANT, (void*)&result, NULL);
	return result;
}

void ILogicalUnit::SetPCUInitialCount(const VARIANT& newValue)
{
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x1c, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 &newValue);
}

VARIANT ILogicalUnit::GetPCUDispensedCount()
{
	VARIANT result;
	InvokeHelper(0x1d, DISPATCH_PROPERTYGET, VT_VARIANT, (void*)&result, NULL);
	return result;
}

void ILogicalUnit::SetPCUDispensedCount(const VARIANT& newValue)
{
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x1d, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 &newValue);
}

VARIANT ILogicalUnit::GetPCUPresentedCount()
{
	VARIANT result;
	InvokeHelper(0x1e, DISPATCH_PROPERTYGET, VT_VARIANT, (void*)&result, NULL);
	return result;
}

void ILogicalUnit::SetPCUPresentedCount(const VARIANT& newValue)
{
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x1e, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 &newValue);
}

VARIANT ILogicalUnit::GetPCURetractedCount()
{
	VARIANT result;
	InvokeHelper(0x1f, DISPATCH_PROPERTYGET, VT_VARIANT, (void*)&result, NULL);
	return result;
}

void ILogicalUnit::SetPCURetractedCount(const VARIANT& newValue)
{
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x1f, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 &newValue);
}

VARIANT ILogicalUnit::GetPCURejectCount()
{
	VARIANT result;
	InvokeHelper(0x20, DISPATCH_PROPERTYGET, VT_VARIANT, (void*)&result, NULL);
	return result;
}

void ILogicalUnit::SetPCURejectCount(const VARIANT& newValue)
{
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x20, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 &newValue);
}

void ILogicalUnit::SetCurrencyID(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x14, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}
