// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "nxcashdispenserx.h"

/////////////////////////////////////////////////////////////////////////////
// CNXCashDispenserX

IMPLEMENT_DYNCREATE(CNXCashDispenserX, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CNXCashDispenserX properties

long CNXCashDispenserX::GetMaxDispenseItems()
{
	long result;
	GetProperty(0x1, VT_I4, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetMaxDispenseItems(long propVal)
{
	SetProperty(0x1, VT_I4, propVal);
}

BOOL CNXCashDispenserX::GetHasShutter()
{
	BOOL result;
	GetProperty(0x2, VT_BOOL, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetHasShutter(BOOL propVal)
{
	SetProperty(0x2, VT_BOOL, propVal);
}

BOOL CNXCashDispenserX::GetCanShutterControl()
{
	BOOL result;
	GetProperty(0x3, VT_BOOL, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetCanShutterControl(BOOL propVal)
{
	SetProperty(0x3, VT_BOOL, propVal);
}

VARIANT CNXCashDispenserX::GetRetractAreas()
{
	VARIANT result;
	GetProperty(0x4, VT_VARIANT, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetRetractAreas(const VARIANT& propVal)
{
	SetProperty(0x4, VT_VARIANT, &propVal);
}

VARIANT CNXCashDispenserX::GetRetractTransportActions()
{
	VARIANT result;
	GetProperty(0x5, VT_VARIANT, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetRetractTransportActions(const VARIANT& propVal)
{
	SetProperty(0x5, VT_VARIANT, &propVal);
}

VARIANT CNXCashDispenserX::GetRetractStackerActions()
{
	VARIANT result;
	GetProperty(0x6, VT_VARIANT, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetRetractStackerActions(const VARIANT& propVal)
{
	SetProperty(0x6, VT_VARIANT, &propVal);
}

BOOL CNXCashDispenserX::GetHasSafeDoor()
{
	BOOL result;
	GetProperty(0x7, VT_BOOL, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetHasSafeDoor(BOOL propVal)
{
	SetProperty(0x7, VT_BOOL, propVal);
}

BOOL CNXCashDispenserX::GetHasStacker()
{
	BOOL result;
	GetProperty(0x8, VT_BOOL, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetHasStacker(BOOL propVal)
{
	SetProperty(0x8, VT_BOOL, propVal);
}

BOOL CNXCashDispenserX::GetHasTakenSensor()
{
	BOOL result;
	GetProperty(0x9, VT_BOOL, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetHasTakenSensor(BOOL propVal)
{
	SetProperty(0x9, VT_BOOL, propVal);
}

VARIANT CNXCashDispenserX::GetMoveItems()
{
	VARIANT result;
	GetProperty(0xa, VT_VARIANT, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetMoveItems(const VARIANT& propVal)
{
	SetProperty(0xa, VT_VARIANT, &propVal);
}

VARIANT CNXCashDispenserX::GetExchangeTypes()
{
	VARIANT result;
	GetProperty(0xb, VT_VARIANT, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetExchangeTypes(const VARIANT& propVal)
{
	SetProperty(0xb, VT_VARIANT, &propVal);
}

long CNXCashDispenserX::GetNumberOfCurrency()
{
	long result;
	GetProperty(0xc, VT_I4, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetNumberOfCurrency(long propVal)
{
	SetProperty(0xc, VT_I4, propVal);
}

VARIANT CNXCashDispenserX::GetCurrencyIDs()
{
	VARIANT result;
	GetProperty(0xd, VT_VARIANT, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetCurrencyIDs(const VARIANT& propVal)
{
	SetProperty(0xd, VT_VARIANT, &propVal);
}

VARIANT CNXCashDispenserX::GetCurrencyExponents()
{
	VARIANT result;
	GetProperty(0xe, VT_VARIANT, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetCurrencyExponents(const VARIANT& propVal)
{
	SetProperty(0xe, VT_VARIANT, &propVal);
}

short CNXCashDispenserX::GetNumberOfLogicalUnits()
{
	short result;
	GetProperty(0xf, VT_I2, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetNumberOfLogicalUnits(short propVal)
{
	SetProperty(0xf, VT_I2, propVal);
}

short CNXCashDispenserX::GetNumberOfPhysicalUnits()
{
	short result;
	GetProperty(0x10, VT_I2, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetNumberOfPhysicalUnits(short propVal)
{
	SetProperty(0x10, VT_I2, propVal);
}

long CNXCashDispenserX::GetNumberOfMixAlgorithm()
{
	long result;
	GetProperty(0x11, VT_I4, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetNumberOfMixAlgorithm(long propVal)
{
	SetProperty(0x11, VT_I4, propVal);
}

VARIANT CNXCashDispenserX::GetMixAlgorithmNumber()
{
	VARIANT result;
	GetProperty(0x12, VT_VARIANT, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetMixAlgorithmNumber(const VARIANT& propVal)
{
	SetProperty(0x12, VT_VARIANT, &propVal);
}

VARIANT CNXCashDispenserX::GetMixAlgorithmName()
{
	VARIANT result;
	GetProperty(0x13, VT_VARIANT, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetMixAlgorithmName(const VARIANT& propVal)
{
	SetProperty(0x13, VT_VARIANT, &propVal);
}

VARIANT CNXCashDispenserX::GetMixAlgorithmOrTable()
{
	VARIANT result;
	GetProperty(0x14, VT_VARIANT, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetMixAlgorithmOrTable(const VARIANT& propVal)
{
	SetProperty(0x14, VT_VARIANT, &propVal);
}

VARIANT CNXCashDispenserX::GetMixAlgorithmType()
{
	VARIANT result;
	GetProperty(0x15, VT_VARIANT, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetMixAlgorithmType(const VARIANT& propVal)
{
	SetProperty(0x15, VT_VARIANT, &propVal);
}

CString CNXCashDispenserX::GetLastPresentInformation()
{
	CString result;
	GetProperty(0x16, VT_BSTR, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetLastPresentInformation(LPCTSTR propVal)
{
	SetProperty(0x16, VT_BSTR, propVal);
}

VARIANT CNXCashDispenserX::GetLastDispenseDenomination()
{
	VARIANT result;
	GetProperty(0x17, VT_VARIANT, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetLastDispenseDenomination(const VARIANT& propVal)
{
	SetProperty(0x17, VT_VARIANT, &propVal);
}

CString CNXCashDispenserX::GetDeviceStatus()
{
	CString result;
	GetProperty(0x18, VT_BSTR, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetDeviceStatus(LPCTSTR propVal)
{
	SetProperty(0x18, VT_BSTR, propVal);
}

CString CNXCashDispenserX::GetSafeDoorStatus()
{
	CString result;
	GetProperty(0x19, VT_BSTR, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetSafeDoorStatus(LPCTSTR propVal)
{
	SetProperty(0x19, VT_BSTR, propVal);
}

CString CNXCashDispenserX::GetDispenserStatus()
{
	CString result;
	GetProperty(0x1a, VT_BSTR, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetDispenserStatus(LPCTSTR propVal)
{
	SetProperty(0x1a, VT_BSTR, propVal);
}

CString CNXCashDispenserX::GetStackerStatus()
{
	CString result;
	GetProperty(0x1b, VT_BSTR, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetStackerStatus(LPCTSTR propVal)
{
	SetProperty(0x1b, VT_BSTR, propVal);
}

CString CNXCashDispenserX::GetShutterStatus()
{
	CString result;
	GetProperty(0x1c, VT_BSTR, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetShutterStatus(LPCTSTR propVal)
{
	SetProperty(0x1c, VT_BSTR, propVal);
}

CString CNXCashDispenserX::GetTransportStatus()
{
	CString result;
	GetProperty(0x1d, VT_BSTR, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetTransportStatus(LPCTSTR propVal)
{
	SetProperty(0x1d, VT_BSTR, propVal);
}

CString CNXCashDispenserX::GetTransportStateStatus()
{
	CString result;
	GetProperty(0x1e, VT_BSTR, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetTransportStateStatus(LPCTSTR propVal)
{
	SetProperty(0x1e, VT_BSTR, propVal);
}

BOOL CNXCashDispenserX::GetCashUnitChangeInProgress()
{
	BOOL result;
	GetProperty(0x1f, VT_BOOL, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetCashUnitChangeInProgress(BOOL propVal)
{
	SetProperty(0x1f, VT_BOOL, propVal);
}

VARIANT CNXCashDispenserX::GetUnitNumber()
{
	VARIANT result;
	GetProperty(0x20, VT_VARIANT, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetUnitNumber(const VARIANT& propVal)
{
	SetProperty(0x20, VT_VARIANT, &propVal);
}

VARIANT CNXCashDispenserX::GetUnitType()
{
	VARIANT result;
	GetProperty(0x21, VT_VARIANT, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetUnitType(const VARIANT& propVal)
{
	SetProperty(0x21, VT_VARIANT, &propVal);
}

VARIANT CNXCashDispenserX::GetUnitStatus()
{
	VARIANT result;
	GetProperty(0x22, VT_VARIANT, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetUnitStatus(const VARIANT& propVal)
{
	SetProperty(0x22, VT_VARIANT, &propVal);
}

VARIANT CNXCashDispenserX::GetUnitID()
{
	VARIANT result;
	GetProperty(0x23, VT_VARIANT, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetUnitID(const VARIANT& propVal)
{
	SetProperty(0x23, VT_VARIANT, &propVal);
}

VARIANT CNXCashDispenserX::GetUnitCurrencyID()
{
	VARIANT result;
	GetProperty(0x24, VT_VARIANT, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetUnitCurrencyID(const VARIANT& propVal)
{
	SetProperty(0x24, VT_VARIANT, &propVal);
}

VARIANT CNXCashDispenserX::GetUnitValue()
{
	VARIANT result;
	GetProperty(0x25, VT_VARIANT, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetUnitValue(const VARIANT& propVal)
{
	SetProperty(0x25, VT_VARIANT, &propVal);
}

VARIANT CNXCashDispenserX::GetUnitInitialCount()
{
	VARIANT result;
	GetProperty(0x26, VT_VARIANT, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetUnitInitialCount(const VARIANT& propVal)
{
	SetProperty(0x26, VT_VARIANT, &propVal);
}

VARIANT CNXCashDispenserX::GetUnitCount()
{
	VARIANT result;
	GetProperty(0x27, VT_VARIANT, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetUnitCount(const VARIANT& propVal)
{
	SetProperty(0x27, VT_VARIANT, &propVal);
}

VARIANT CNXCashDispenserX::GetUnitMinimumCount()
{
	VARIANT result;
	GetProperty(0x28, VT_VARIANT, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetUnitMinimumCount(const VARIANT& propVal)
{
	SetProperty(0x28, VT_VARIANT, &propVal);
}

VARIANT CNXCashDispenserX::GetUnitMaximumCount()
{
	VARIANT result;
	GetProperty(0x29, VT_VARIANT, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetUnitMaximumCount(const VARIANT& propVal)
{
	SetProperty(0x29, VT_VARIANT, &propVal);
}

VARIANT CNXCashDispenserX::GetPhysicalPositionName()
{
	VARIANT result;
	GetProperty(0x2a, VT_VARIANT, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetPhysicalPositionName(const VARIANT& propVal)
{
	SetProperty(0x2a, VT_VARIANT, &propVal);
}

VARIANT CNXCashDispenserX::GetPhysicalStatus()
{
	VARIANT result;
	GetProperty(0x2b, VT_VARIANT, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetPhysicalStatus(const VARIANT& propVal)
{
	SetProperty(0x2b, VT_VARIANT, &propVal);
}

VARIANT CNXCashDispenserX::GetPhysicalID()
{
	VARIANT result;
	GetProperty(0x2c, VT_VARIANT, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetPhysicalID(const VARIANT& propVal)
{
	SetProperty(0x2c, VT_VARIANT, &propVal);
}

VARIANT CNXCashDispenserX::GetPhysicalInitialCount()
{
	VARIANT result;
	GetProperty(0x2d, VT_VARIANT, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetPhysicalInitialCount(const VARIANT& propVal)
{
	SetProperty(0x2d, VT_VARIANT, &propVal);
}

VARIANT CNXCashDispenserX::GetPhysicalCount()
{
	VARIANT result;
	GetProperty(0x2e, VT_VARIANT, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetPhysicalCount(const VARIANT& propVal)
{
	SetProperty(0x2e, VT_VARIANT, &propVal);
}

VARIANT CNXCashDispenserX::GetPhysicalMaximum()
{
	VARIANT result;
	GetProperty(0x2f, VT_VARIANT, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetPhysicalMaximum(const VARIANT& propVal)
{
	SetProperty(0x2f, VT_VARIANT, &propVal);
}

VARIANT CNXCashDispenserX::GetPhysicalHardwareSensor()
{
	VARIANT result;
	GetProperty(0x30, VT_VARIANT, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetPhysicalHardwareSensor(const VARIANT& propVal)
{
	SetProperty(0x30, VT_VARIANT, &propVal);
}

VARIANT CNXCashDispenserX::GetUnitPUNumber()
{
	VARIANT result;
	GetProperty(0x31, VT_VARIANT, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetUnitPUNumber(const VARIANT& propVal)
{
	SetProperty(0x31, VT_VARIANT, &propVal);
}

VARIANT CNXCashDispenserX::GetUnitPUIDs()
{
	VARIANT result;
	GetProperty(0x32, VT_VARIANT, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetUnitPUIDs(const VARIANT& propVal)
{
	SetProperty(0x32, VT_VARIANT, &propVal);
}

CString CNXCashDispenserX::GetDeviceType()
{
	CString result;
	GetProperty(0x33, VT_BSTR, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetDeviceType(LPCTSTR propVal)
{
	SetProperty(0x33, VT_BSTR, propVal);
}

CString CNXCashDispenserX::GetPositionStatus()
{
	CString result;
	GetProperty(0x34, VT_BSTR, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetPositionStatus(LPCTSTR propVal)
{
	SetProperty(0x34, VT_BSTR, propVal);
}

VARIANT CNXCashDispenserX::GetUnitRejectCount()
{
	VARIANT result;
	GetProperty(0x35, VT_VARIANT, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetUnitRejectCount(const VARIANT& propVal)
{
	SetProperty(0x35, VT_VARIANT, &propVal);
}

VARIANT CNXCashDispenserX::GetPhysicalRejectCount()
{
	VARIANT result;
	GetProperty(0x36, VT_VARIANT, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetPhysicalRejectCount(const VARIANT& propVal)
{
	SetProperty(0x36, VT_VARIANT, &propVal);
}

CString CNXCashDispenserX::GetLogicalServiceName()
{
	CString result;
#ifdef UNDER_CE
#  define GETLSNAME_ID 0x37
#else
#  define GETLSNAME_ID 0x37
#endif

	GetProperty(GETLSNAME_ID, VT_BSTR, (void*)&result);
	return result;
}

void CNXCashDispenserX::SetLogicalServiceName(LPCTSTR propVal)
{
	SetProperty(0x37, VT_BSTR, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CNXCashDispenserX operations

long CNXCashDispenserX::OpenSessionSync(long Timeout)
{
#ifdef UNDER_CE
#  define OPENSESSION_ID 0x38
#else
#  define OPENSESSION_ID 0x37
#endif

	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(OPENSESSION_ID, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Timeout);
	return result;
}

long CNXCashDispenserX::CloseSessionSync()
{
#ifdef UNDER_CE
#  define CLOSESESSION_ID 0x39
#else
#  define CLOSESESSION_ID 0x38
#endif

	long result;
	InvokeHelper(CLOSESESSION_ID, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXCashDispenserX::RequestLock(long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x3a, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Timeout);
	return result;
}

long CNXCashDispenserX::ReleaseLock()
{
	long result;
	InvokeHelper(0x3b, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

CString CNXCashDispenserX::GetExtraStatus(LPCTSTR KeyName)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x3c, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		KeyName);
	return result;
}

CString CNXCashDispenserX::GetExtraCaps(LPCTSTR KeyName)
{
#ifdef UNDER_CE
#  define GETEXTRACAPS_ID 0x3e
#else
#  define GETEXTRACAPS_ID 0x3d
#endif

	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(GETEXTRACAPS_ID, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		KeyName);
	return result;
}

long CNXCashDispenserX::Denominate(LPCTSTR MixAlgorithm, LPCTSTR Currency, long Amount, const VARIANT& NoteCounts)
{
#ifdef UNDER_CE
#  define DENOMINATE_ID 0x3e
#else
#  define DENOMINATE_ID 0x3d
#endif

	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_I4 VTS_VARIANT;
	InvokeHelper(DENOMINATE_ID, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		MixAlgorithm, Currency, Amount, &NoteCounts);
	return result;
}

long CNXCashDispenserX::Dispense(LPCTSTR MixAlgorithm, LPCTSTR Currency, long Amount, const VARIANT& NoteCounts, long Present, long Timeout)
{
#ifdef UNDER_CE
#  define DISPENSE_ID 0x3f
#else
#  define DISPENSE_ID 0x3e
#endif

	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_I4 VTS_VARIANT VTS_I4 VTS_I4;
	InvokeHelper(DISPENSE_ID, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		MixAlgorithm, Currency, Amount, &NoteCounts, Present, Timeout);

	return result;
}

long CNXCashDispenserX::Present(long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x40, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Timeout);
	return result;
}

long CNXCashDispenserX::Count(long EmptyAll, LPCTSTR PhysicalPositionName)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_BSTR;
	InvokeHelper(0x41, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		EmptyAll, PhysicalPositionName);
	return result;
}

long CNXCashDispenserX::Reject()
{
	long result;
	InvokeHelper(0x42, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXCashDispenserX::Retract(short RetractArea)
{
	long result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x43, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		RetractArea);
	return result;
}

long CNXCashDispenserX::OpenShutter()
{
	long result;
	InvokeHelper(0x44, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXCashDispenserX::CloseShutter()
{
	long result;
	InvokeHelper(0x45, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXCashDispenserX::StartExchangeSync(const VARIANT& CashUnitsToExchange, long ExchangeType)
{
	long result;
	static BYTE parms[] =
		VTS_VARIANT VTS_I4;
	InvokeHelper(0x46, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		&CashUnitsToExchange, ExchangeType);
	return result;
}

long CNXCashDispenserX::EndExchangeSync()
{
	long result;
	InvokeHelper(0x47, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXCashDispenserX::OpenSafeDoor()
{
	long result;
	InvokeHelper(0x48, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXCashDispenserX::CalibrateCashUnit(short UnitNumber, short NumberOfBills)
{
	long result;
	static BYTE parms[] =
		VTS_I2 VTS_I2;
	InvokeHelper(0x49, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		UnitNumber, NumberOfBills);
	return result;
}

long CNXCashDispenserX::Reset(short CashUnitNumber)
{
#ifdef UNDER_CE
#  define RESET_ID 0x4a
#else
#  define RESET_ID 0x49
#endif

	long result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(RESET_ID, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		CashUnitNumber);
	return result;
}

void CNXCashDispenserX::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
