#if !defined(AFX_NXCASHDISPENSERX_H__2F9963F1_8F29_4F11_9ACC_166ADB8F03E0__INCLUDED_)
#define AFX_NXCASHDISPENSERX_H__2F9963F1_8F29_4F11_9ACC_166ADB8F03E0__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CNXCashDispenserX wrapper class

class CNXCashDispenserX : public CWnd
{
protected:
	DECLARE_DYNCREATE(CNXCashDispenserX)
public:
	CLSID const& GetClsid()
	{
#ifdef UNDER_CE
		static CLSID const clsid
			= { 0x80842368, 0xa7b8, 0x46d2, { 0xa1, 0x27, 0x57, 0x24, 0xc1, 0x28, 0x91, 0xff } };
#else
		static CLSID const clsid
			= { 0x0CC5C44C, 0x95D5, 0x4D67, { 0xA8, 0x74, 0xDA, 0x94, 0xF1, 0xAD, 0x34, 0x56 } };
			//= { 0x80842368, 0xa7b8, 0x46d2, { 0xa1, 0x27, 0x57, 0x24, 0xc1, 0x28, 0x91, 0xff } };
			//= { 0x0D88E5F9, 0x7696, 0x49BF, { 0xB6, 0xFB, 0x29, 0xDE, 0x77, 0x23, 0xB4, 0xAB } };
			//= { 0xaffd32fe, 0x5d18, 0x482e, { 0xab, 0x9d, 0x09, 0x8a, 0xa7, 0xe9, 0xf1, 0x8e } };
#endif
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	long GetMaxDispenseItems();
	void SetMaxDispenseItems(long);
	BOOL GetHasShutter();
	void SetHasShutter(BOOL);
	BOOL GetCanShutterControl();
	void SetCanShutterControl(BOOL);
	VARIANT GetRetractAreas();
	void SetRetractAreas(const VARIANT&);
	VARIANT GetRetractTransportActions();
	void SetRetractTransportActions(const VARIANT&);
	VARIANT GetRetractStackerActions();
	void SetRetractStackerActions(const VARIANT&);
	BOOL GetHasSafeDoor();
	void SetHasSafeDoor(BOOL);
	BOOL GetHasStacker();
	void SetHasStacker(BOOL);
	BOOL GetHasTakenSensor();
	void SetHasTakenSensor(BOOL);
	VARIANT GetMoveItems();
	void SetMoveItems(const VARIANT&);
	VARIANT GetExchangeTypes();
	void SetExchangeTypes(const VARIANT&);
	long GetNumberOfCurrency();
	void SetNumberOfCurrency(long);
	VARIANT GetCurrencyIDs();
	void SetCurrencyIDs(const VARIANT&);
	VARIANT GetCurrencyExponents();
	void SetCurrencyExponents(const VARIANT&);
	short GetNumberOfLogicalUnits();
	void SetNumberOfLogicalUnits(short);
	short GetNumberOfPhysicalUnits();
	void SetNumberOfPhysicalUnits(short);
	long GetNumberOfMixAlgorithm();
	void SetNumberOfMixAlgorithm(long);
	VARIANT GetMixAlgorithmNumber();
	void SetMixAlgorithmNumber(const VARIANT&);
	VARIANT GetMixAlgorithmName();
	void SetMixAlgorithmName(const VARIANT&);
	VARIANT GetMixAlgorithmOrTable();
	void SetMixAlgorithmOrTable(const VARIANT&);
	VARIANT GetMixAlgorithmType();
	void SetMixAlgorithmType(const VARIANT&);
	CString GetLastPresentInformation();
	void SetLastPresentInformation(LPCTSTR);
	VARIANT GetLastDispenseDenomination();
	void SetLastDispenseDenomination(const VARIANT&);
	CString GetDeviceStatus();
	void SetDeviceStatus(LPCTSTR);
	CString GetSafeDoorStatus();
	void SetSafeDoorStatus(LPCTSTR);
	CString GetDispenserStatus();
	void SetDispenserStatus(LPCTSTR);
	CString GetStackerStatus();
	void SetStackerStatus(LPCTSTR);
	CString GetShutterStatus();
	void SetShutterStatus(LPCTSTR);
	CString GetTransportStatus();
	void SetTransportStatus(LPCTSTR);
	CString GetTransportStateStatus();
	void SetTransportStateStatus(LPCTSTR);
	BOOL GetCashUnitChangeInProgress();
	void SetCashUnitChangeInProgress(BOOL);
	VARIANT GetUnitNumber();
	void SetUnitNumber(const VARIANT&);
	VARIANT GetUnitType();
	void SetUnitType(const VARIANT&);
	VARIANT GetUnitStatus();
	void SetUnitStatus(const VARIANT&);
	VARIANT GetUnitID();
	void SetUnitID(const VARIANT&);
	VARIANT GetUnitCurrencyID();
	void SetUnitCurrencyID(const VARIANT&);
	VARIANT GetUnitValue();
	void SetUnitValue(const VARIANT&);
	VARIANT GetUnitInitialCount();
	void SetUnitInitialCount(const VARIANT&);
	VARIANT GetUnitCount();
	void SetUnitCount(const VARIANT&);
	VARIANT GetUnitMinimumCount();
	void SetUnitMinimumCount(const VARIANT&);
	VARIANT GetUnitMaximumCount();
	void SetUnitMaximumCount(const VARIANT&);
	VARIANT GetPhysicalPositionName();
	void SetPhysicalPositionName(const VARIANT&);
	VARIANT GetPhysicalStatus();
	void SetPhysicalStatus(const VARIANT&);
	VARIANT GetPhysicalID();
	void SetPhysicalID(const VARIANT&);
	VARIANT GetPhysicalInitialCount();
	void SetPhysicalInitialCount(const VARIANT&);
	VARIANT GetPhysicalCount();
	void SetPhysicalCount(const VARIANT&);
	VARIANT GetPhysicalMaximum();
	void SetPhysicalMaximum(const VARIANT&);
	VARIANT GetPhysicalHardwareSensor();
	void SetPhysicalHardwareSensor(const VARIANT&);
	VARIANT GetUnitPUNumber();
	void SetUnitPUNumber(const VARIANT&);
	VARIANT GetUnitPUIDs();
	void SetUnitPUIDs(const VARIANT&);
	CString GetDeviceType();
	void SetDeviceType(LPCTSTR);
	CString GetPositionStatus();
	void SetPositionStatus(LPCTSTR);
	VARIANT GetUnitRejectCount();
	void SetUnitRejectCount(const VARIANT&);
	VARIANT GetPhysicalRejectCount();
	void SetPhysicalRejectCount(const VARIANT&);
	CString GetLogicalServiceName();
	void SetLogicalServiceName(LPCTSTR);

// Operations
public:
	long OpenSessionSync(long Timeout);
	long CloseSessionSync();
	long RequestLock(long Timeout);
	long ReleaseLock();
	CString GetExtraStatus(LPCTSTR KeyName);
	CString GetExtraCaps(LPCTSTR KeyName);
	long Denominate(LPCTSTR MixAlgorithm, LPCTSTR Currency, long Amount, const VARIANT& NoteCounts);
	long Dispense(LPCTSTR MixAlgorithm, LPCTSTR Currency, long Amount, const VARIANT& NoteCounts, long Present, long Timeout);
	long Present(long Timeout);
	long Count(long EmptyAll, LPCTSTR PhysicalPositionName);
	long Reject();
	long Retract(short RetractArea);
	long OpenShutter();
	long CloseShutter();
	long StartExchangeSync(const VARIANT& CashUnitsToExchange, long ExchangeType);
	long EndExchangeSync();
	long OpenSafeDoor();
	long CalibrateCashUnit(short UnitNumber, short NumberOfBills);
	long Reset(short CashUnitNumber);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_NXCASHDISPENSERX_H__2F9963F1_8F29_4F11_9ACC_166ADB8F03E0__INCLUDED_)
