// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "nxcardreaderx.h"

/////////////////////////////////////////////////////////////////////////////
// CNXCardReaderX

IMPLEMENT_DYNCREATE(CNXCardReaderX, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CNXCardReaderX properties

CString CNXCardReaderX::GetDeviceStatus()
{
	CString result;
	GetProperty(0x1, VT_BSTR, (void*)&result);
	return result;
}

void CNXCardReaderX::SetDeviceStatus(LPCTSTR propVal)
{
	SetProperty(0x1, VT_BSTR, propVal);
}

CString CNXCardReaderX::GetMediaStatus()
{
	CString result;
	GetProperty(0x2, VT_BSTR, (void*)&result);
	return result;
}

void CNXCardReaderX::SetMediaStatus(LPCTSTR propVal)
{
	SetProperty(0x2, VT_BSTR, propVal);
}

CString CNXCardReaderX::GetRetainBinStatus()
{
	CString result;
	GetProperty(0x3, VT_BSTR, (void*)&result);
	return result;
}

void CNXCardReaderX::SetRetainBinStatus(LPCTSTR propVal)
{
	SetProperty(0x3, VT_BSTR, propVal);
}

short CNXCardReaderX::GetMaxRetainCount()
{
	short result;
	GetProperty(0x4, VT_I2, (void*)&result);
	return result;
}

void CNXCardReaderX::SetMaxRetainCount(short propVal)
{
	SetProperty(0x4, VT_I2, propVal);
}

short CNXCardReaderX::GetRetainCount()
{
	short result;
	GetProperty(0x5, VT_I2, (void*)&result);
	return result;
}

void CNXCardReaderX::SetRetainCount(short propVal)
{
	SetProperty(0x5, VT_I2, propVal);
}

BOOL CNXCardReaderX::GetCanReadISO1Track()
{
	BOOL result;
	GetProperty(0x6, VT_BOOL, (void*)&result);
	return result;
}

void CNXCardReaderX::SetCanReadISO1Track(BOOL propVal)
{
	SetProperty(0x6, VT_BOOL, propVal);
}

BOOL CNXCardReaderX::GetCanReadISO2Track()
{
	BOOL result;
	GetProperty(0x7, VT_BOOL, (void*)&result);
	return result;
}

void CNXCardReaderX::SetCanReadISO2Track(BOOL propVal)
{
	SetProperty(0x7, VT_BOOL, propVal);
}

BOOL CNXCardReaderX::GetCanReadISO3Track()
{
	BOOL result;
	GetProperty(0x8, VT_BOOL, (void*)&result);
	return result;
}

void CNXCardReaderX::SetCanReadISO3Track(BOOL propVal)
{
	SetProperty(0x8, VT_BOOL, propVal);
}

BOOL CNXCardReaderX::GetCanWriteISO1Track()
{
	BOOL result;
	GetProperty(0x9, VT_BOOL, (void*)&result);
	return result;
}

void CNXCardReaderX::SetCanWriteISO1Track(BOOL propVal)
{
	SetProperty(0x9, VT_BOOL, propVal);
}

BOOL CNXCardReaderX::GetCanWriteISO2Track()
{
	BOOL result;
	GetProperty(0xa, VT_BOOL, (void*)&result);
	return result;
}

void CNXCardReaderX::SetCanWriteISO2Track(BOOL propVal)
{
	SetProperty(0xa, VT_BOOL, propVal);
}

BOOL CNXCardReaderX::GetCanWriteISO3Track()
{
	BOOL result;
	GetProperty(0xb, VT_BOOL, (void*)&result);
	return result;
}

void CNXCardReaderX::SetCanWriteISO3Track(BOOL propVal)
{
	SetProperty(0xb, VT_BOOL, propVal);
}

CString CNXCardReaderX::GetSecurityType()
{
	CString result;
	GetProperty(0xc, VT_BSTR, (void*)&result);
	return result;
}

void CNXCardReaderX::SetSecurityType(LPCTSTR propVal)
{
	SetProperty(0xc, VT_BSTR, propVal);
}

CString CNXCardReaderX::GetDeviceType()
{
	CString result;
	GetProperty(0xd, VT_BSTR, (void*)&result);
	return result;
}

void CNXCardReaderX::SetDeviceType(LPCTSTR propVal)
{
	SetProperty(0xd, VT_BSTR, propVal);
}

CString CNXCardReaderX::GetFormName()
{
	CString result;
	GetProperty(0xe, VT_BSTR, (void*)&result);
	return result;
}

void CNXCardReaderX::SetFormName(LPCTSTR propVal)
{
	SetProperty(0xe, VT_BSTR, propVal);
}

CString CNXCardReaderX::GetFormAction()
{
	CString result;
	GetProperty(0xf, VT_BSTR, (void*)&result);
	return result;
}

void CNXCardReaderX::SetFormAction(LPCTSTR propVal)
{
	SetProperty(0xf, VT_BSTR, propVal);
}

VARIANT CNXCardReaderX::GetTrack1Fields()
{
	VARIANT result;
	GetProperty(0x10, VT_VARIANT, (void*)&result);
	return result;
}

void CNXCardReaderX::SetTrack1Fields(const VARIANT& propVal)
{
	SetProperty(0x10, VT_VARIANT, &propVal);
}

VARIANT CNXCardReaderX::GetTrack2Fields()
{
	VARIANT result;
	GetProperty(0x11, VT_VARIANT, (void*)&result);
	return result;
}

void CNXCardReaderX::SetTrack2Fields(const VARIANT& propVal)
{
	SetProperty(0x11, VT_VARIANT, &propVal);
}

VARIANT CNXCardReaderX::GetTrack3Fields()
{
	VARIANT result;
	GetProperty(0x12, VT_VARIANT, (void*)&result);
	return result;
}

void CNXCardReaderX::SetTrack3Fields(const VARIANT& propVal)
{
	SetProperty(0x12, VT_VARIANT, &propVal);
}

CString CNXCardReaderX::GetTrack1Separator()
{
	CString result;
	GetProperty(0x13, VT_BSTR, (void*)&result);
	return result;
}

void CNXCardReaderX::SetTrack1Separator(LPCTSTR propVal)
{
	SetProperty(0x13, VT_BSTR, propVal);
}

CString CNXCardReaderX::GetTrack2Separator()
{
	CString result;
	GetProperty(0x14, VT_BSTR, (void*)&result);
	return result;
}

void CNXCardReaderX::SetTrack2Separator(LPCTSTR propVal)
{
	SetProperty(0x14, VT_BSTR, propVal);
}

CString CNXCardReaderX::GetTrack3Separator()
{
	CString result;
	GetProperty(0x15, VT_BSTR, (void*)&result);
	return result;
}

void CNXCardReaderX::SetTrack3Separator(LPCTSTR propVal)
{
	SetProperty(0x15, VT_BSTR, propVal);
}

CString CNXCardReaderX::GetTracks()
{
	CString result;
	GetProperty(0x16, VT_BSTR, (void*)&result);
	return result;
}

void CNXCardReaderX::SetTracks(LPCTSTR propVal)
{
	SetProperty(0x16, VT_BSTR, propVal);
}

CString CNXCardReaderX::GetTrack1Data()
{
	CString result;
	GetProperty(0x17, VT_BSTR, (void*)&result);
	return result;
}

void CNXCardReaderX::SetTrack1Data(LPCTSTR propVal)
{
	SetProperty(0x17, VT_BSTR, propVal);
}

CString CNXCardReaderX::GetTrack2Data()
{
	CString result;
	GetProperty(0x18, VT_BSTR, (void*)&result);
	return result;
}

void CNXCardReaderX::SetTrack2Data(LPCTSTR propVal)
{
	SetProperty(0x18, VT_BSTR, propVal);
}

CString CNXCardReaderX::GetTrack3Data()
{
	CString result;
	GetProperty(0x19, VT_BSTR, (void*)&result);
	return result;
}

void CNXCardReaderX::SetTrack3Data(LPCTSTR propVal)
{
	SetProperty(0x19, VT_BSTR, propVal);
}

CString CNXCardReaderX::GetSecurityData()
{
	CString result;
	GetProperty(0x1a, VT_BSTR, (void*)&result);
	return result;
}

void CNXCardReaderX::SetSecurityData(LPCTSTR propVal)
{
	SetProperty(0x1a, VT_BSTR, propVal);
}

VARIANT CNXCardReaderX::GetChipData()
{
	VARIANT result;
	GetProperty(0x1b, VT_VARIANT, (void*)&result);
	return result;
}

void CNXCardReaderX::SetChipData(const VARIANT& propVal)
{
	SetProperty(0x1b, VT_VARIANT, &propVal);
}

CString CNXCardReaderX::GetTrack1Status()
{
	CString result;
	GetProperty(0x1c, VT_BSTR, (void*)&result);
	return result;
}

void CNXCardReaderX::SetTrack1Status(LPCTSTR propVal)
{
	SetProperty(0x1c, VT_BSTR, propVal);
}

CString CNXCardReaderX::GetTrack2Status()
{
	CString result;
	GetProperty(0x1d, VT_BSTR, (void*)&result);
	return result;
}

void CNXCardReaderX::SetTrack2Status(LPCTSTR propVal)
{
	SetProperty(0x1d, VT_BSTR, propVal);
}

CString CNXCardReaderX::GetTrack3Status()
{
	CString result;
	GetProperty(0x1e, VT_BSTR, (void*)&result);
	return result;
}

void CNXCardReaderX::SetTrack3Status(LPCTSTR propVal)
{
	SetProperty(0x1e, VT_BSTR, propVal);
}

CString CNXCardReaderX::GetSecurityStatus()
{
	CString result;
	GetProperty(0x1f, VT_BSTR, (void*)&result);
	return result;
}

void CNXCardReaderX::SetSecurityStatus(LPCTSTR propVal)
{
	SetProperty(0x1f, VT_BSTR, propVal);
}

CString CNXCardReaderX::GetChipStatus()
{
	CString result;
	GetProperty(0x20, VT_BSTR, (void*)&result);
	return result;
}

void CNXCardReaderX::SetChipStatus(LPCTSTR propVal)
{
	SetProperty(0x20, VT_BSTR, propVal);
}

CString CNXCardReaderX::GetPowerOnOptions()
{
	CString result;
	GetProperty(0x21, VT_BSTR, (void*)&result);
	return result;
}

void CNXCardReaderX::SetPowerOnOptions(LPCTSTR propVal)
{
	SetProperty(0x21, VT_BSTR, propVal);
}

CString CNXCardReaderX::GetPowerOffOptions()
{
	CString result;
	GetProperty(0x22, VT_BSTR, (void*)&result);
	return result;
}

void CNXCardReaderX::SetPowerOffOptions(LPCTSTR propVal)
{
	SetProperty(0x22, VT_BSTR, propVal);
}

CString CNXCardReaderX::GetChipProtocols()
{
	CString result;
	GetProperty(0x23, VT_BSTR, (void*)&result);
	return result;
}

void CNXCardReaderX::SetChipProtocols(LPCTSTR propVal)
{
	SetProperty(0x23, VT_BSTR, propVal);
}

BOOL CNXCardReaderX::GetFluxSensorProgrammable()
{
	BOOL result;
	GetProperty(0x24, VT_BOOL, (void*)&result);
	return result;
}

void CNXCardReaderX::SetFluxSensorProgrammable(BOOL propVal)
{
	SetProperty(0x24, VT_BOOL, propVal);
}

BOOL CNXCardReaderX::GetCanRWFollowingEject()
{
	BOOL result;
	GetProperty(0x25, VT_BOOL, (void*)&result);
	return result;
}

void CNXCardReaderX::SetCanRWFollowingEject(BOOL propVal)
{
	SetProperty(0x25, VT_BOOL, propVal);
}

CString CNXCardReaderX::GetChipPowerStatus()
{
	CString result;
	GetProperty(0x26, VT_BSTR, (void*)&result);
	return result;
}

void CNXCardReaderX::SetChipPowerStatus(LPCTSTR propVal)
{
	SetProperty(0x26, VT_BSTR, propVal);
}

CString CNXCardReaderX::GetWriteMode()
{
	CString result;
	GetProperty(0x27, VT_BSTR, (void*)&result);
	return result;
}

void CNXCardReaderX::SetWriteMode(LPCTSTR propVal)
{
	SetProperty(0x27, VT_BSTR, propVal);
}

CString CNXCardReaderX::GetChipPowerType()
{
	CString result;
	GetProperty(0x28, VT_BSTR, (void*)&result);
	return result;
}

void CNXCardReaderX::SetChipPowerType(LPCTSTR propVal)
{
	SetProperty(0x28, VT_BSTR, propVal);
}

BOOL CNXCardReaderX::GetCanReadWMTrack()
{
	BOOL result;
	GetProperty(0x29, VT_BOOL, (void*)&result);
	return result;
}

void CNXCardReaderX::SetCanReadWMTrack(BOOL propVal)
{
	SetProperty(0x29, VT_BOOL, propVal);
}

BOOL CNXCardReaderX::GetCanWriteWMTrack()
{
	BOOL result;
	GetProperty(0x2a, VT_BOOL, (void*)&result);
	return result;
}

void CNXCardReaderX::SetCanWriteWMTrack(BOOL propVal)
{
	SetProperty(0x2a, VT_BOOL, propVal);
}

CString CNXCardReaderX::GetTrackWMStatus()
{
	CString result;
	GetProperty(0x2b, VT_BSTR, (void*)&result);
	return result;
}

void CNXCardReaderX::SetTrackWMStatus(LPCTSTR propVal)
{
	SetProperty(0x2b, VT_BSTR, propVal);
}

CString CNXCardReaderX::GetTrackWMData()
{
	CString result;
	GetProperty(0x2c, VT_BSTR, (void*)&result);
	return result;
}

void CNXCardReaderX::SetTrackWMData(LPCTSTR propVal)
{
	SetProperty(0x2c, VT_BSTR, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CNXCardReaderX operations

long CNXCardReaderX::OpenSessionSync(long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x2d, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Timeout);
	return result;
}

long CNXCardReaderX::CloseSessionSync()
{
	long result;
	InvokeHelper(0x2e, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXCardReaderX::RequestLock(long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x2f, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Timeout);
	return result;
}

long CNXCardReaderX::ReleaseLock()
{
	long result;
	InvokeHelper(0x30, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

CString CNXCardReaderX::GetExtraStatus(LPCTSTR KeyName)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x31, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		KeyName);
	return result;
}

CString CNXCardReaderX::GetExtraCaps(LPCTSTR KeyName)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x32, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		KeyName);
	return result;
}

long CNXCardReaderX::ReadForm(LPCTSTR FormName, long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4;
	InvokeHelper(0x33, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		FormName, Timeout);
	return result;
}

long CNXCardReaderX::ReadRawData(LPCTSTR Tracks, long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4;
	InvokeHelper(0x34, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Tracks, Timeout);
	return result;
}

long CNXCardReaderX::ReadAvailableRawData(LPCTSTR Tracks, long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4;
	InvokeHelper(0x35, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Tracks, Timeout);
	return result;
}

long CNXCardReaderX::CancelAccept()
{
	long result;
	InvokeHelper(0x36, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXCardReaderX::EjectMedia(long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x37, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Timeout);
	return result;
}

long CNXCardReaderX::RetainMedia()
{
	long result;
	InvokeHelper(0x38, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXCardReaderX::ResetRetainCount()
{
	long result;
	InvokeHelper(0x39, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXCardReaderX::WriteForm(LPCTSTR FormName, LPCTSTR TrackData, LPCTSTR WriteMethod)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x3a, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		FormName, TrackData, WriteMethod);
	return result;
}

long CNXCardReaderX::WriteRawData(LPCTSTR Tracks, const VARIANT& TrackData, LPCTSTR WriteMethod)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_VARIANT VTS_BSTR;
	InvokeHelper(0x3b, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Tracks, &TrackData, WriteMethod);
	return result;
}

BOOL CNXCardReaderX::GetFieldValue(LPCTSTR FieldName, BSTR* FieldValue)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_PBSTR;
	InvokeHelper(0x3c, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		FieldName, FieldValue);
	return result;
}

long CNXCardReaderX::ChipIO(short Protocol, LPCTSTR Token, const VARIANT& Bytes, long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_I2 VTS_BSTR VTS_VARIANT VTS_I4;
	InvokeHelper(0x3d, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Protocol, Token, &Bytes, Timeout);
	return result;
}

long CNXCardReaderX::QueryFormList(VARIANT* FormList)
{
	long result;
	static BYTE parms[] =
		VTS_PVARIANT;
	InvokeHelper(0x3e, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		FormList);
	return result;
}

long CNXCardReaderX::QueryForm(LPCTSTR FormName)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x3f, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		FormName);
	return result;
}

long CNXCardReaderX::Reset(LPCTSTR ResetIn)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x40, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		ResetIn);
	return result;
}

long CNXCardReaderX::ChipPower(LPCTSTR ChipPower)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x41, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		ChipPower);
	return result;
}

void CNXCardReaderX::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
