// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "nxcamerax.h"

/////////////////////////////////////////////////////////////////////////////
// CNXCameraX

IMPLEMENT_DYNCREATE(CNXCameraX, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CNXCameraX properties

CString CNXCameraX::GetDeviceStatus()
{
	CString result;
	GetProperty(0x1, VT_BSTR, (void*)&result);
	return result;
}

void CNXCameraX::SetDeviceStatus(LPCTSTR propVal)
{
	SetProperty(0x1, VT_BSTR, propVal);
}

long CNXCameraX::GetMaxNumberOfPicture()
{
	long result;
	GetProperty(0x2, VT_I4, (void*)&result);
	return result;
}

void CNXCameraX::SetMaxNumberOfPicture(long propVal)
{
	SetProperty(0x2, VT_I4, propVal);
}

CString CNXCameraX::GetPictureData()
{
	CString result;
	GetProperty(0x3, VT_BSTR, (void*)&result);
	return result;
}

void CNXCameraX::SetPictureData(LPCTSTR propVal)
{
	SetProperty(0x3, VT_BSTR, propVal);
}

long CNXCameraX::GetMaxPictureDataSize()
{
	long result;
	GetProperty(0x4, VT_I4, (void*)&result);
	return result;
}

void CNXCameraX::SetMaxPictureDataSize(long propVal)
{
	SetProperty(0x4, VT_I4, propVal);
}

VARIANT CNXCameraX::GetSupportedCharSet()
{
	VARIANT result;
	GetProperty(0x5, VT_VARIANT, (void*)&result);
	return result;
}

void CNXCameraX::SetSupportedCharSet(const VARIANT& propVal)
{
	SetProperty(0x5, VT_VARIANT, &propVal);
}

CString CNXCameraX::GetLogicalSerivceName()
{
	CString result;
	GetProperty(0x6, VT_BSTR, (void*)&result);
	return result;
}

void CNXCameraX::SetLogicalSerivceName(LPCTSTR propVal)
{
	SetProperty(0x6, VT_BSTR, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CNXCameraX operations

long CNXCameraX::OpenSessionSync(long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x7, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Timeout);
	return result;
}

long CNXCameraX::CloseSessionSync()
{
	long result;
	InvokeHelper(0x8, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXCameraX::RequestLock(long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x9, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Timeout);
	return result;
}

long CNXCameraX::ReleaseLock()
{
	long result;
	InvokeHelper(0xa, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXCameraX::Reset()
{
	long result;
	InvokeHelper(0xb, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

CString CNXCameraX::GetExtraStatus(LPCTSTR KeyName)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0xc, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		KeyName);
	return result;
}

CString CNXCameraX::GetExtraCaps(LPCTSTR KeyName)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0xd, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		KeyName);
	return result;
}

long CNXCameraX::Capture(LPCTSTR CamType, LPCTSTR PictureInfo)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0xe, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		CamType, PictureInfo);
	return result;
}

CString CNXCameraX::GetCameraStatus(LPCTSTR KeyName)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0xf, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, parms,
		KeyName);
	return result;
}

CString CNXCameraX::GetMediaStatus(LPCTSTR CamType)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x10, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, parms,
		CamType);
	return result;
}

long CNXCameraX::GetNumberOfPicture(LPCTSTR CamType)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x11, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, parms,
		CamType);
	return result;
}

void CNXCameraX::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
