#if !defined(AFX_NXCAMERAX_H__FFFFA1DC_B728_492E_A268_16C276DCF22F__INCLUDED_)
#define AFX_NXCAMERAX_H__FFFFA1DC_B728_492E_A268_16C276DCF22F__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CNXCameraX wrapper class

class CNXCameraX : public CWnd
{
protected:
	DECLARE_DYNCREATE(CNXCameraX)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x1438abe4, 0x8b0, 0x4fc5, { 0x81, 0xca, 0xa0, 0xfd, 0x49, 0x7b, 0x35, 0xc2 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	CString GetDeviceStatus();
	void SetDeviceStatus(LPCTSTR);
	long GetMaxNumberOfPicture();
	void SetMaxNumberOfPicture(long);
	CString GetPictureData();
	void SetPictureData(LPCTSTR);
	long GetMaxPictureDataSize();
	void SetMaxPictureDataSize(long);
	VARIANT GetSupportedCharSet();
	void SetSupportedCharSet(const VARIANT&);
	CString GetLogicalSerivceName();
	void SetLogicalSerivceName(LPCTSTR);

// Operations
public:
	long OpenSessionSync(long Timeout);
	long CloseSessionSync();
	long RequestLock(long Timeout);
	long ReleaseLock();
	long Reset();
	CString GetExtraStatus(LPCTSTR KeyName);
	CString GetExtraCaps(LPCTSTR KeyName);
	long Capture(LPCTSTR CamType, LPCTSTR PictureInfo);
	CString GetCameraStatus(LPCTSTR KeyName);
	CString GetMediaStatus(LPCTSTR CamType);
	long GetNumberOfPicture(LPCTSTR CamType);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_NXCAMERAX_H__FFFFA1DC_B728_492E_A268_16C276DCF22F__INCLUDED_)
