#if !defined(AFX_NXDOORSX_H__3C0618FA_96D7_4645_BA97_BDE0565F1907__INCLUDED_)
#define AFX_NXDOORSX_H__3C0618FA_96D7_4645_BA97_BDE0565F1907__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CNXDoorsX wrapper class

class CNXDoorsX : public CWnd
{
protected:
	DECLARE_DYNCREATE(CNXDoorsX)
public:
	CLSID const& GetClsid()
	{

#ifdef UNDER_CE
		static CLSID const clsid
			= { 0x7ebc2c95, 0x89fe, 0x4593, { 0xa5, 0x51, 0x28, 0x9d, 0x40, 0xbd, 0x89, 0xc4 } };
#else
		static CLSID const clsid
			= { 0x21332595, 0x6b2e, 0x4482, { 0x95, 0xf0, 0x9b, 0xda, 0x28, 0x3d, 0x74, 0xf7 } };
#endif
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	CString GetCabinetStatus();
	void SetCabinetStatus(LPCTSTR);
	CString GetSafeStatus();
	void SetSafeStatus(LPCTSTR);
	CString GetShieldStatus();
	void SetShieldStatus(LPCTSTR);
	BOOL GetCanBoltCabinet();
	void SetCanBoltCabinet(BOOL);
	BOOL GetCanBoltSafe();
	void SetCanBoltSafe(BOOL);
	BOOL GetCanCloseShield();
	void SetCanCloseShield(BOOL);
	BOOL GetCanOpenShield();
	void SetCanOpenShield(BOOL);
	BOOL GetCanServiceShield();
	void SetCanServiceShield(BOOL);
	BOOL GetCanKeyboardShield();
	void SetCanKeyboardShield(BOOL);
	CString GetDeviceStatus();
	void SetDeviceStatus(LPCTSTR);
	BOOL GetHasCabinet();
	void SetHasCabinet(BOOL);
	BOOL GetHasSafe();
	void SetHasSafe(BOOL);
	BOOL GetHasShield();
	void SetHasShield(BOOL);
	CString GetLogicalServiceName();
	void SetLogicalServiceName(LPCTSTR);

// Operations
public:
	long OpenSessionSync(long Timeout);
	long CloseSessionSync();
	long RequestLock(long Timeout);
	long ReleaseLock();
	long Reset();
	CString GetExtraStatus(LPCTSTR KeyName);
	CString GetExtraCaps(LPCTSTR KeyName);
	long BoltCabinet();
	long UnboltCabinet();
	long BoltSafe();
	long UnboltSafe();
	long SetShield(LPCTSTR State);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_NXDOORSX_H__3C0618FA_96D7_4645_BA97_BDE0565F1907__INCLUDED_)
