// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "nxdoorsx.h"

/////////////////////////////////////////////////////////////////////////////
// CNXDoorsX

IMPLEMENT_DYNCREATE(CNXDoorsX, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CNXDoorsX properties

CString CNXDoorsX::GetCabinetStatus()
{
	CString result;
	GetProperty(0x1, VT_BSTR, (void*)&result);
	return result;
}

void CNXDoorsX::SetCabinetStatus(LPCTSTR propVal)
{
	SetProperty(0x1, VT_BSTR, propVal);
}

CString CNXDoorsX::GetSafeStatus()
{
	CString result;
	GetProperty(0x2, VT_BSTR, (void*)&result);
	return result;
}

void CNXDoorsX::SetSafeStatus(LPCTSTR propVal)
{
	SetProperty(0x2, VT_BSTR, propVal);
}

CString CNXDoorsX::GetShieldStatus()
{
	CString result;
	GetProperty(0x3, VT_BSTR, (void*)&result);
	return result;
}

void CNXDoorsX::SetShieldStatus(LPCTSTR propVal)
{
	SetProperty(0x3, VT_BSTR, propVal);
}

BOOL CNXDoorsX::GetCanBoltCabinet()
{
	BOOL result;
	GetProperty(0x4, VT_BOOL, (void*)&result);
	return result;
}

void CNXDoorsX::SetCanBoltCabinet(BOOL propVal)
{
	SetProperty(0x4, VT_BOOL, propVal);
}

BOOL CNXDoorsX::GetCanBoltSafe()
{
	BOOL result;
	GetProperty(0x5, VT_BOOL, (void*)&result);
	return result;
}

void CNXDoorsX::SetCanBoltSafe(BOOL propVal)
{
	SetProperty(0x5, VT_BOOL, propVal);
}

BOOL CNXDoorsX::GetCanCloseShield()
{
	BOOL result;
	GetProperty(0x6, VT_BOOL, (void*)&result);
	return result;
}

void CNXDoorsX::SetCanCloseShield(BOOL propVal)
{
	SetProperty(0x6, VT_BOOL, propVal);
}

BOOL CNXDoorsX::GetCanOpenShield()
{
	BOOL result;
	GetProperty(0x7, VT_BOOL, (void*)&result);
	return result;
}

void CNXDoorsX::SetCanOpenShield(BOOL propVal)
{
	SetProperty(0x7, VT_BOOL, propVal);
}

BOOL CNXDoorsX::GetCanServiceShield()
{
	BOOL result;
	GetProperty(0x8, VT_BOOL, (void*)&result);
	return result;
}

void CNXDoorsX::SetCanServiceShield(BOOL propVal)
{
	SetProperty(0x8, VT_BOOL, propVal);
}

BOOL CNXDoorsX::GetCanKeyboardShield()
{
	BOOL result;
	GetProperty(0x9, VT_BOOL, (void*)&result);
	return result;
}

void CNXDoorsX::SetCanKeyboardShield(BOOL propVal)
{
	SetProperty(0x9, VT_BOOL, propVal);
}

CString CNXDoorsX::GetDeviceStatus()
{
	CString result;
	GetProperty(0xa, VT_BSTR, (void*)&result);
	return result;
}

void CNXDoorsX::SetDeviceStatus(LPCTSTR propVal)
{
	SetProperty(0xa, VT_BSTR, propVal);
}

BOOL CNXDoorsX::GetHasCabinet()
{
	BOOL result;
	GetProperty(0xb, VT_BOOL, (void*)&result);
	return result;
}

void CNXDoorsX::SetHasCabinet(BOOL propVal)
{
	SetProperty(0xb, VT_BOOL, propVal);
}

BOOL CNXDoorsX::GetHasSafe()
{
	BOOL result;
	GetProperty(0xc, VT_BOOL, (void*)&result);
	return result;
}

void CNXDoorsX::SetHasSafe(BOOL propVal)
{
	SetProperty(0xc, VT_BOOL, propVal);
}

BOOL CNXDoorsX::GetHasShield()
{
	BOOL result;
	GetProperty(0xd, VT_BOOL, (void*)&result);
	return result;
}

void CNXDoorsX::SetHasShield(BOOL propVal)
{
	SetProperty(0xd, VT_BOOL, propVal);
}

CString CNXDoorsX::GetLogicalServiceName()
{
#ifdef UNDER_CE
#  define GETLSNAME_ID 0xe
#else
#  define GETLSNAME_ID 0xd
#endif

	CString result;
	GetProperty(GETLSNAME_ID, VT_BSTR, (void*)&result);
	return result;
}

void CNXDoorsX::SetLogicalServiceName(LPCTSTR propVal)
{
	SetProperty(0xe, VT_BSTR, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CNXDoorsX operations

long CNXDoorsX::OpenSessionSync(long Timeout)
{
#ifdef UNDER_CE
#  define OPENSESSION_ID 0xf
#else
#  define OPENSESSION_ID 0xe
#endif

	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(OPENSESSION_ID, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Timeout);
	return result;
}

long CNXDoorsX::CloseSessionSync()
{
	long result;
	InvokeHelper(0x10, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXDoorsX::RequestLock(long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x11, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Timeout);
	return result;
}

long CNXDoorsX::ReleaseLock()
{
	long result;
	InvokeHelper(0x12, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXDoorsX::Reset()
{
	long result;
	InvokeHelper(0x13, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

CString CNXDoorsX::GetExtraStatus(LPCTSTR KeyName)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x14, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		KeyName);
	return result;
}

CString CNXDoorsX::GetExtraCaps(LPCTSTR KeyName)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x15, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		KeyName);
	return result;
}

long CNXDoorsX::BoltCabinet()
{
	long result;
	InvokeHelper(0x16, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXDoorsX::UnboltCabinet()
{
	long result;
	InvokeHelper(0x17, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXDoorsX::BoltSafe()
{
	long result;
	InvokeHelper(0x18, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXDoorsX::UnboltSafe()
{
	long result;
	InvokeHelper(0x19, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXDoorsX::SetShield(LPCTSTR State)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x1a, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		State);
	return result;
}

void CNXDoorsX::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
