#if !defined(AFX_NXGUIDLIGHTSX_H__F0A3098F_4716_4827_A4E4_8E78974ACC6C__INCLUDED_)
#define AFX_NXGUIDLIGHTSX_H__F0A3098F_4716_4827_A4E4_8E78974ACC6C__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CNXGuidLightsX wrapper class

class CNXGuidLightsX : public CWnd
{
protected:
	DECLARE_DYNCREATE(CNXGuidLightsX)
public:
	CLSID const& GetClsid()
	{
#ifdef UNDER_CE
		static CLSID const clsid
			= { 0xf2df0dc3, 0xc486, 0x4d37, { 0x99, 0x9, 0xbf, 0x53, 0x60, 0x97, 0x68, 0x1a } };
#else
		static CLSID const clsid
			//= { 0x9fad3d21, 0xd23f, 0x4eff, { 0x8e, 0x79, 0xf7, 0xb0, 0xf7, 0x40, 0x1d, 0x96 } };
			//= { 0x5d8948fd, 0x6017, 0x4e55, { 0xb6, 0xa0, 0xf9, 0xd4, 0xb8, 0x92, 0x79, 0xa2 } };
			= { 0x182B2321, 0xED5E, 0x4096, { 0xB8, 0x1A, 0xBA, 0x5B, 0xB3, 0xB5, 0xAB, 0xEE } };
#endif
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	BOOL GetHasCardReader();
	void SetHasCardReader(BOOL);
	BOOL GetHasPinPad();
	void SetHasPinPad(BOOL);
	BOOL GetHasNotesDispenser();
	void SetHasNotesDispenser(BOOL);
	BOOL GetHasCoinDispenser();
	void SetHasCoinDispenser(BOOL);
	BOOL GetHasReceiptPrinter();
	void SetHasReceiptPrinter(BOOL);
	BOOL GetHasPassbookPrinter();
	void SetHasPassbookPrinter(BOOL);
	BOOL GetHasEnvelopeDepository();
	void SetHasEnvelopeDepository(BOOL);
	BOOL GetHasChequeUnit();
	void SetHasChequeUnit(BOOL);
	BOOL GetHasBillAcceptor();
	void SetHasBillAcceptor(BOOL);
	BOOL GetHasEnvelopeDispenser();
	void SetHasEnvelopeDispenser(BOOL);
	CString GetDeviceStatus();
	void SetDeviceStatus(LPCTSTR);
	BOOL GetHasDocumentPrinter();
	void SetHasDocumentPrinter(BOOL);
	BOOL GetHasCoinAcceptor();
	void SetHasCoinAcceptor(BOOL);
	BOOL GetHasScanner();
	void SetHasScanner(BOOL);
	CString GetLogicalServiceName();
	void SetLogicalServiceName(LPCTSTR);

// Operations
public:
	long OpenSessionSync(long Timeout);
	long CloseSessionSync();
	long RequestLock(long Timeout);
	long ReleaseLock();
	long Reset();
	CString GetExtraStatus(LPCTSTR KeyName);
	CString GetExtraCaps(LPCTSTR KeyName);
	long SetGuidLight(LPCTSTR Device, LPCTSTR FlashRate);
	CString GetGuidLightStatus(LPCTSTR Device);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_NXGUIDLIGHTSX_H__F0A3098F_4716_4827_A4E4_8E78974ACC6C__INCLUDED_)
