// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "nxguidlightsx.h"

/////////////////////////////////////////////////////////////////////////////
// CNXGuidLightsX

IMPLEMENT_DYNCREATE(CNXGuidLightsX, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CNXGuidLightsX properties

BOOL CNXGuidLightsX::GetHasCardReader()
{
	BOOL result;
	GetProperty(0x1, VT_BOOL, (void*)&result);
	return result;
}

void CNXGuidLightsX::SetHasCardReader(BOOL propVal)
{
	SetProperty(0x1, VT_BOOL, propVal);
}

BOOL CNXGuidLightsX::GetHasPinPad()
{
	BOOL result;
	GetProperty(0x2, VT_BOOL, (void*)&result);
	return result;
}

void CNXGuidLightsX::SetHasPinPad(BOOL propVal)
{
	SetProperty(0x2, VT_BOOL, propVal);
}

BOOL CNXGuidLightsX::GetHasNotesDispenser()
{
	BOOL result;
	GetProperty(0x3, VT_BOOL, (void*)&result);
	return result;
}

void CNXGuidLightsX::SetHasNotesDispenser(BOOL propVal)
{
	SetProperty(0x3, VT_BOOL, propVal);
}

BOOL CNXGuidLightsX::GetHasCoinDispenser()
{
	BOOL result;
	GetProperty(0x4, VT_BOOL, (void*)&result);
	return result;
}

void CNXGuidLightsX::SetHasCoinDispenser(BOOL propVal)
{
	SetProperty(0x4, VT_BOOL, propVal);
}

BOOL CNXGuidLightsX::GetHasReceiptPrinter()
{
	BOOL result;
	GetProperty(0x5, VT_BOOL, (void*)&result);
	return result;
}

void CNXGuidLightsX::SetHasReceiptPrinter(BOOL propVal)
{
	SetProperty(0x5, VT_BOOL, propVal);
}

BOOL CNXGuidLightsX::GetHasPassbookPrinter()
{
	BOOL result;
	GetProperty(0x6, VT_BOOL, (void*)&result);
	return result;
}

void CNXGuidLightsX::SetHasPassbookPrinter(BOOL propVal)
{
	SetProperty(0x6, VT_BOOL, propVal);
}

BOOL CNXGuidLightsX::GetHasEnvelopeDepository()
{
	BOOL result;
	GetProperty(0x7, VT_BOOL, (void*)&result);
	return result;
}

void CNXGuidLightsX::SetHasEnvelopeDepository(BOOL propVal)
{
	SetProperty(0x7, VT_BOOL, propVal);
}

BOOL CNXGuidLightsX::GetHasChequeUnit()
{
	BOOL result;
	GetProperty(0x8, VT_BOOL, (void*)&result);
	return result;
}

void CNXGuidLightsX::SetHasChequeUnit(BOOL propVal)
{
	SetProperty(0x8, VT_BOOL, propVal);
}

BOOL CNXGuidLightsX::GetHasBillAcceptor()
{
	BOOL result;
	GetProperty(0x9, VT_BOOL, (void*)&result);
	return result;
}

void CNXGuidLightsX::SetHasBillAcceptor(BOOL propVal)
{
	SetProperty(0x9, VT_BOOL, propVal);
}

BOOL CNXGuidLightsX::GetHasEnvelopeDispenser()
{
	BOOL result;
	GetProperty(0xa, VT_BOOL, (void*)&result);
	return result;
}

void CNXGuidLightsX::SetHasEnvelopeDispenser(BOOL propVal)
{
	SetProperty(0xa, VT_BOOL, propVal);
}

CString CNXGuidLightsX::GetDeviceStatus()
{
	CString result;
	GetProperty(0xb, VT_BSTR, (void*)&result);
	return result;
}

void CNXGuidLightsX::SetDeviceStatus(LPCTSTR propVal)
{
	SetProperty(0xb, VT_BSTR, propVal);
}

BOOL CNXGuidLightsX::GetHasDocumentPrinter()
{
	BOOL result;
	GetProperty(0xc, VT_BOOL, (void*)&result);
	return result;
}

void CNXGuidLightsX::SetHasDocumentPrinter(BOOL propVal)
{
	SetProperty(0xc, VT_BOOL, propVal);
}

BOOL CNXGuidLightsX::GetHasCoinAcceptor()
{
	BOOL result;
	GetProperty(0xd, VT_BOOL, (void*)&result);
	return result;
}

void CNXGuidLightsX::SetHasCoinAcceptor(BOOL propVal)
{
	SetProperty(0xd, VT_BOOL, propVal);
}

BOOL CNXGuidLightsX::GetHasScanner()
{
	BOOL result;
	GetProperty(0xe, VT_BOOL, (void*)&result);
	return result;
}

void CNXGuidLightsX::SetHasScanner(BOOL propVal)
{
	SetProperty(0xe, VT_BOOL, propVal);
}

CString CNXGuidLightsX::GetLogicalServiceName()
{
	CString result;
	GetProperty(0xf, VT_BSTR, (void*)&result);
	return result;
}

void CNXGuidLightsX::SetLogicalServiceName(LPCTSTR propVal)
{
	SetProperty(0xf, VT_BSTR, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CNXGuidLightsX operations

long CNXGuidLightsX::OpenSessionSync(long Timeout)
{
#ifdef UNDER_CE
#  define OPENSESSION_ID 0x10
#else
#  define OPENSESSION_ID 0x0F
#endif

	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(OPENSESSION_ID, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Timeout);
	return result;
}

long CNXGuidLightsX::CloseSessionSync()
{
#ifdef UNDER_CE
#  define CLOSESESSION_ID 0x11
#else
#  define CLOSESESSION_ID 0x10
#endif

	long result;
	InvokeHelper(CLOSESESSION_ID, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXGuidLightsX::RequestLock(long Timeout)
{
#ifdef UNDER_CE
#  define REQUESTLOCK_ID 0x12
#else
#  define REQUESTLOCK_ID 0x11
#endif

	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(REQUESTLOCK_ID, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Timeout);
	return result;
}

long CNXGuidLightsX::ReleaseLock()
{
#ifdef UNDER_CE
#  define RELEASELOCK_ID 0x13
#else
#  define RELEASELOCK_ID 0x12
#endif

	long result;
	InvokeHelper(RELEASELOCK_ID, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXGuidLightsX::Reset()
{
#ifdef UNDER_CE
#  define RESET_ID 0x14
#else
#  define RESET_ID 0x13
#endif

	long result;
	InvokeHelper(RESET_ID, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

CString CNXGuidLightsX::GetExtraStatus(LPCTSTR KeyName)
{
#ifdef UNDER_CE
#  define GETEXTRASTATUS_ID 0x15
#else
#  define GETEXTRASTATUS_ID 0x14
#endif

	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(GETEXTRASTATUS_ID, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		KeyName);
	return result;
}

CString CNXGuidLightsX::GetExtraCaps(LPCTSTR KeyName)
{
#ifdef UNDER_CE
#  define GETEXTRACAPS_ID 0x16
#else
#  define GETEXTRACAPS_ID 0x15
#endif

	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(GETEXTRACAPS_ID, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		KeyName);
	return result;
}

long CNXGuidLightsX::SetGuidLight(LPCTSTR Device, LPCTSTR FlashRate)
{
#ifdef UNDER_CE
#  define SETGUIDLIGHT_ID 0x17
#else
#  define SETGUIDLIGHT_ID 0x16
#endif

	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(SETGUIDLIGHT_ID, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Device, FlashRate);
	return result;
}

CString CNXGuidLightsX::GetGuidLightStatus(LPCTSTR Device)
{
#ifdef UNDER_CE
#  define GETGUIDLIGHTSTATUS_ID 0x18
#else
#  define GETGUIDLIGHTSTATUS_ID 0x17
#endif

	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(GETGUIDLIGHTSTATUS_ID, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		Device);
	return result;
}

void CNXGuidLightsX::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
