#if !defined(AFX_NXINDICATORSX_H__6FC71D69_CA56_4B22_A07F_1F3F4CA27412__INCLUDED_)
#define AFX_NXINDICATORSX_H__6FC71D69_CA56_4B22_A07F_1F3F4CA27412__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CNXIndicatorsX wrapper class

class CNXIndicatorsX : public CWnd
{
protected:
	DECLARE_DYNCREATE(CNXIndicatorsX)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x5360a25e, 0x9d71, 0x4901, { 0x82, 0x7b, 0x42, 0xd0, 0xe8, 0x14, 0x4, 0x7c } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	CString GetOpenCloseStatus();
	void SetOpenCloseStatus(LPCTSTR);
	CString GetFasciaLightStatus();
	void SetFasciaLightStatus(LPCTSTR);
	CString GetAudioStatus();
	void SetAudioStatus(LPCTSTR);
	BOOL GetAudioContinuous();
	void SetAudioContinuous(BOOL);
	CString GetHeatingStatus();
	void SetHeatingStatus(LPCTSTR);
	BOOL GetHasOpenClose();
	void SetHasOpenClose(BOOL);
	BOOL GetHasFascialLight();
	void SetHasFascialLight(BOOL);
	BOOL GetHasAudio();
	void SetHasAudio(BOOL);
	BOOL GetHasHeating();
	void SetHasHeating(BOOL);
	CString GetDeviceStatus();
	void SetDeviceStatus(LPCTSTR);
	CString GetLogicalServiceName();
	void SetLogicalServiceName(LPCTSTR);

// Operations
public:
	long OpenSessionSync(long Timeout);
	long CloseSessionSync();
	long RequestLock(long Timeout);
	long ReleaseLock();
	long Reset();
	CString GetExtraStatus(LPCTSTR KeyName);
	CString GetExtraCaps(LPCTSTR KeyName);
	long SetOpenClose(LPCTSTR State);
	long SetFascialLight(LPCTSTR State);
	long SetHeating(LPCTSTR State);
	long SetAudio(LPCTSTR State, long Continuous);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_NXINDICATORSX_H__6FC71D69_CA56_4B22_A07F_1F3F4CA27412__INCLUDED_)
