// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "nxindicatorsx.h"

/////////////////////////////////////////////////////////////////////////////
// CNXIndicatorsX

IMPLEMENT_DYNCREATE(CNXIndicatorsX, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CNXIndicatorsX properties

CString CNXIndicatorsX::GetOpenCloseStatus()
{
	CString result;
	GetProperty(0x1, VT_BSTR, (void*)&result);
	return result;
}

void CNXIndicatorsX::SetOpenCloseStatus(LPCTSTR propVal)
{
	SetProperty(0x1, VT_BSTR, propVal);
}

CString CNXIndicatorsX::GetFasciaLightStatus()
{
	CString result;
	GetProperty(0x2, VT_BSTR, (void*)&result);
	return result;
}

void CNXIndicatorsX::SetFasciaLightStatus(LPCTSTR propVal)
{
	SetProperty(0x2, VT_BSTR, propVal);
}

CString CNXIndicatorsX::GetAudioStatus()
{
	CString result;
	GetProperty(0x3, VT_BSTR, (void*)&result);
	return result;
}

void CNXIndicatorsX::SetAudioStatus(LPCTSTR propVal)
{
	SetProperty(0x3, VT_BSTR, propVal);
}

BOOL CNXIndicatorsX::GetAudioContinuous()
{
	BOOL result;
	GetProperty(0x4, VT_BOOL, (void*)&result);
	return result;
}

void CNXIndicatorsX::SetAudioContinuous(BOOL propVal)
{
	SetProperty(0x4, VT_BOOL, propVal);
}

CString CNXIndicatorsX::GetHeatingStatus()
{
	CString result;
	GetProperty(0x5, VT_BSTR, (void*)&result);
	return result;
}

void CNXIndicatorsX::SetHeatingStatus(LPCTSTR propVal)
{
	SetProperty(0x5, VT_BSTR, propVal);
}

BOOL CNXIndicatorsX::GetHasOpenClose()
{
	BOOL result;
	GetProperty(0x6, VT_BOOL, (void*)&result);
	return result;
}

void CNXIndicatorsX::SetHasOpenClose(BOOL propVal)
{
	SetProperty(0x6, VT_BOOL, propVal);
}

BOOL CNXIndicatorsX::GetHasFascialLight()
{
	BOOL result;
	GetProperty(0x7, VT_BOOL, (void*)&result);
	return result;
}

void CNXIndicatorsX::SetHasFascialLight(BOOL propVal)
{
	SetProperty(0x7, VT_BOOL, propVal);
}

BOOL CNXIndicatorsX::GetHasAudio()
{
	BOOL result;
	GetProperty(0x8, VT_BOOL, (void*)&result);
	return result;
}

void CNXIndicatorsX::SetHasAudio(BOOL propVal)
{
	SetProperty(0x8, VT_BOOL, propVal);
}

BOOL CNXIndicatorsX::GetHasHeating()
{
	BOOL result;
	GetProperty(0x9, VT_BOOL, (void*)&result);
	return result;
}

void CNXIndicatorsX::SetHasHeating(BOOL propVal)
{
	SetProperty(0x9, VT_BOOL, propVal);
}

CString CNXIndicatorsX::GetDeviceStatus()
{
	CString result;
	GetProperty(0xa, VT_BSTR, (void*)&result);
	return result;
}

void CNXIndicatorsX::SetDeviceStatus(LPCTSTR propVal)
{
	SetProperty(0xa, VT_BSTR, propVal);
}

CString CNXIndicatorsX::GetLogicalServiceName()
{
	CString result;
	GetProperty(0xb, VT_BSTR, (void*)&result);
	return result;
}

void CNXIndicatorsX::SetLogicalServiceName(LPCTSTR propVal)
{
	SetProperty(0xb, VT_BSTR, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CNXIndicatorsX operations

long CNXIndicatorsX::OpenSessionSync(long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xc, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Timeout);
	return result;
}

long CNXIndicatorsX::CloseSessionSync()
{
	long result;
	InvokeHelper(0xd, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXIndicatorsX::RequestLock(long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xe, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Timeout);
	return result;
}

long CNXIndicatorsX::ReleaseLock()
{
	long result;
	InvokeHelper(0xf, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXIndicatorsX::Reset()
{
	long result;
	InvokeHelper(0x10, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

CString CNXIndicatorsX::GetExtraStatus(LPCTSTR KeyName)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x11, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		KeyName);
	return result;
}

CString CNXIndicatorsX::GetExtraCaps(LPCTSTR KeyName)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x12, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		KeyName);
	return result;
}

long CNXIndicatorsX::SetOpenClose(LPCTSTR State)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x13, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		State);
	return result;
}

long CNXIndicatorsX::SetFascialLight(LPCTSTR State)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x14, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		State);
	return result;
}

long CNXIndicatorsX::SetHeating(LPCTSTR State)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x15, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		State);
	return result;
}

long CNXIndicatorsX::SetAudio(LPCTSTR State, long Continuous)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4;
	InvokeHelper(0x16, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		State, Continuous);
	return result;
}

void CNXIndicatorsX::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
