// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "nxjournalprinterx.h"

/////////////////////////////////////////////////////////////////////////////
// CNXJournalPrinterX

IMPLEMENT_DYNCREATE(CNXJournalPrinterX, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CNXJournalPrinterX properties

CString CNXJournalPrinterX::GetDeviceStatus()
{
	CString result;
	GetProperty(0x1, VT_BSTR, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetDeviceStatus(LPCTSTR propVal)
{
	SetProperty(0x1, VT_BSTR, propVal);
}

CString CNXJournalPrinterX::GetMediaStatus()
{
	CString result;
	GetProperty(0x2, VT_BSTR, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetMediaStatus(LPCTSTR propVal)
{
	SetProperty(0x2, VT_BSTR, propVal);
}

CString CNXJournalPrinterX::GetTonerStatus()
{
	CString result;
	GetProperty(0x3, VT_BSTR, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetTonerStatus(LPCTSTR propVal)
{
	SetProperty(0x3, VT_BSTR, propVal);
}

CString CNXJournalPrinterX::GetInkStatus()
{
	CString result;
	GetProperty(0x4, VT_BSTR, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetInkStatus(LPCTSTR propVal)
{
	SetProperty(0x4, VT_BSTR, propVal);
}

CString CNXJournalPrinterX::GetLampStatus()
{
	CString result;
	GetProperty(0x5, VT_BSTR, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetLampStatus(LPCTSTR propVal)
{
	SetProperty(0x5, VT_BSTR, propVal);
}

short CNXJournalPrinterX::GetMediaOnStackerCount()
{
	short result;
	GetProperty(0x6, VT_I2, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetMediaOnStackerCount(short propVal)
{
	SetProperty(0x6, VT_I2, propVal);
}

VARIANT CNXJournalPrinterX::GetResolution()
{
	VARIANT result;
	GetProperty(0x7, VT_VARIANT, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetResolution(const VARIANT& propVal)
{
	SetProperty(0x7, VT_VARIANT, &propVal);
}

VARIANT CNXJournalPrinterX::GetReadTypes()
{
	VARIANT result;
	GetProperty(0x8, VT_VARIANT, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetReadTypes(const VARIANT& propVal)
{
	SetProperty(0x8, VT_VARIANT, &propVal);
}

VARIANT CNXJournalPrinterX::GetWriteTypes()
{
	VARIANT result;
	GetProperty(0x9, VT_VARIANT, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetWriteTypes(const VARIANT& propVal)
{
	SetProperty(0x9, VT_VARIANT, &propVal);
}

VARIANT CNXJournalPrinterX::GetControlMediaActions()
{
	VARIANT result;
	GetProperty(0xa, VT_VARIANT, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetControlMediaActions(const VARIANT& propVal)
{
	SetProperty(0xa, VT_VARIANT, &propVal);
}

short CNXJournalPrinterX::GetMaxMediaOnStacker()
{
	short result;
	GetProperty(0xb, VT_I2, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetMaxMediaOnStacker(short propVal)
{
	SetProperty(0xb, VT_I2, propVal);
}

VARIANT CNXJournalPrinterX::GetFormList()
{
	VARIANT result;
	GetProperty(0xc, VT_VARIANT, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetFormList(const VARIANT& propVal)
{
	SetProperty(0xc, VT_VARIANT, &propVal);
}

CString CNXJournalPrinterX::GetFormName()
{
	CString result;
	GetProperty(0xd, VT_BSTR, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetFormName(LPCTSTR propVal)
{
	SetProperty(0xd, VT_BSTR, propVal);
}

CString CNXJournalPrinterX::GetFormAlignment()
{
	CString result;
	GetProperty(0xe, VT_BSTR, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetFormAlignment(LPCTSTR propVal)
{
	SetProperty(0xe, VT_BSTR, propVal);
}

long CNXJournalPrinterX::GetFormUnitX()
{
	long result;
	GetProperty(0xf, VT_I4, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetFormUnitX(long propVal)
{
	SetProperty(0xf, VT_I4, propVal);
}

long CNXJournalPrinterX::GetFormUnitY()
{
	long result;
	GetProperty(0x10, VT_I4, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetFormUnitY(long propVal)
{
	SetProperty(0x10, VT_I4, propVal);
}

long CNXJournalPrinterX::GetFormWidth()
{
	long result;
	GetProperty(0x11, VT_I4, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetFormWidth(long propVal)
{
	SetProperty(0x11, VT_I4, propVal);
}

long CNXJournalPrinterX::GetFormHeight()
{
	long result;
	GetProperty(0x12, VT_I4, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetFormHeight(long propVal)
{
	SetProperty(0x12, VT_I4, propVal);
}

CString CNXJournalPrinterX::GetFormBase()
{
	CString result;
	GetProperty(0x13, VT_BSTR, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetFormBase(LPCTSTR propVal)
{
	SetProperty(0x13, VT_BSTR, propVal);
}

CString CNXJournalPrinterX::GetFormOrientation()
{
	CString result;
	GetProperty(0x14, VT_BSTR, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetFormOrientation(LPCTSTR propVal)
{
	SetProperty(0x14, VT_BSTR, propVal);
}

long CNXJournalPrinterX::GetFormOffsetX()
{
	long result;
	GetProperty(0x15, VT_I4, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetFormOffsetX(long propVal)
{
	SetProperty(0x15, VT_I4, propVal);
}

long CNXJournalPrinterX::GetFormOffsetY()
{
	long result;
	GetProperty(0x16, VT_I4, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetFormOffsetY(long propVal)
{
	SetProperty(0x16, VT_I4, propVal);
}

long CNXJournalPrinterX::GetFormVersionMajor()
{
	long result;
	GetProperty(0x17, VT_I4, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetFormVersionMajor(long propVal)
{
	SetProperty(0x17, VT_I4, propVal);
}

long CNXJournalPrinterX::GetFormVersionMinor()
{
	long result;
	GetProperty(0x18, VT_I4, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetFormVersionMinor(long propVal)
{
	SetProperty(0x18, VT_I4, propVal);
}

CString CNXJournalPrinterX::GetFormUserPrompt()
{
	CString result;
	GetProperty(0x19, VT_BSTR, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetFormUserPrompt(LPCTSTR propVal)
{
	SetProperty(0x19, VT_BSTR, propVal);
}

VARIANT CNXJournalPrinterX::GetFormFieldList()
{
	VARIANT result;
	GetProperty(0x1a, VT_VARIANT, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetFormFieldList(const VARIANT& propVal)
{
	SetProperty(0x1a, VT_VARIANT, &propVal);
}

CString CNXJournalPrinterX::GetFormFieldName()
{
	CString result;
	GetProperty(0x1b, VT_BSTR, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetFormFieldName(LPCTSTR propVal)
{
	SetProperty(0x1b, VT_BSTR, propVal);
}

CString CNXJournalPrinterX::GetFormFieldType()
{
	CString result;
	GetProperty(0x1c, VT_BSTR, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetFormFieldType(LPCTSTR propVal)
{
	SetProperty(0x1c, VT_BSTR, propVal);
}

CString CNXJournalPrinterX::GetFormFieldClass()
{
	CString result;
	GetProperty(0x1d, VT_BSTR, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetFormFieldClass(LPCTSTR propVal)
{
	SetProperty(0x1d, VT_BSTR, propVal);
}

CString CNXJournalPrinterX::GetFormFieldAccess()
{
	CString result;
	GetProperty(0x1e, VT_BSTR, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetFormFieldAccess(LPCTSTR propVal)
{
	SetProperty(0x1e, VT_BSTR, propVal);
}

CString CNXJournalPrinterX::GetFormFieldInitialValue()
{
	CString result;
	GetProperty(0x1f, VT_BSTR, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetFormFieldInitialValue(LPCTSTR propVal)
{
	SetProperty(0x1f, VT_BSTR, propVal);
}

CString CNXJournalPrinterX::GetFormFieldFormat()
{
	CString result;
	GetProperty(0x20, VT_BSTR, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetFormFieldFormat(LPCTSTR propVal)
{
	SetProperty(0x20, VT_BSTR, propVal);
}

VARIANT CNXJournalPrinterX::GetMediaList()
{
	VARIANT result;
	GetProperty(0x21, VT_VARIANT, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetMediaList(const VARIANT& propVal)
{
	SetProperty(0x21, VT_VARIANT, &propVal);
}

CString CNXJournalPrinterX::GetMediaName()
{
	CString result;
	GetProperty(0x22, VT_BSTR, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetMediaName(LPCTSTR propVal)
{
	SetProperty(0x22, VT_BSTR, propVal);
}

CString CNXJournalPrinterX::GetMediaType()
{
	CString result;
	GetProperty(0x23, VT_BSTR, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetMediaType(LPCTSTR propVal)
{
	SetProperty(0x23, VT_BSTR, propVal);
}

CString CNXJournalPrinterX::GetMediaBase()
{
	CString result;
	GetProperty(0x24, VT_BSTR, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetMediaBase(LPCTSTR propVal)
{
	SetProperty(0x24, VT_BSTR, propVal);
}

long CNXJournalPrinterX::GetMediaUnitX()
{
	long result;
	GetProperty(0x25, VT_I4, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetMediaUnitX(long propVal)
{
	SetProperty(0x25, VT_I4, propVal);
}

long CNXJournalPrinterX::GetMediaUnitY()
{
	long result;
	GetProperty(0x26, VT_I4, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetMediaUnitY(long propVal)
{
	SetProperty(0x26, VT_I4, propVal);
}

long CNXJournalPrinterX::GetMediaSizeWidth()
{
	long result;
	GetProperty(0x27, VT_I4, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetMediaSizeWidth(long propVal)
{
	SetProperty(0x27, VT_I4, propVal);
}

long CNXJournalPrinterX::GetMediaSizeHeight()
{
	long result;
	GetProperty(0x28, VT_I4, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetMediaSizeHeight(long propVal)
{
	SetProperty(0x28, VT_I4, propVal);
}

long CNXJournalPrinterX::GetMediaPageCount()
{
	long result;
	GetProperty(0x29, VT_I4, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetMediaPageCount(long propVal)
{
	SetProperty(0x29, VT_I4, propVal);
}

long CNXJournalPrinterX::GetMediaLineCount()
{
	long result;
	GetProperty(0x2a, VT_I4, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetMediaLineCount(long propVal)
{
	SetProperty(0x2a, VT_I4, propVal);
}

long CNXJournalPrinterX::GetMediaPrintAreaX()
{
	long result;
	GetProperty(0x2b, VT_I4, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetMediaPrintAreaX(long propVal)
{
	SetProperty(0x2b, VT_I4, propVal);
}

long CNXJournalPrinterX::GetMediaPrintAreaY()
{
	long result;
	GetProperty(0x2c, VT_I4, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetMediaPrintAreaY(long propVal)
{
	SetProperty(0x2c, VT_I4, propVal);
}

long CNXJournalPrinterX::GetMediaPrintAreaWidth()
{
	long result;
	GetProperty(0x2d, VT_I4, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetMediaPrintAreaWidth(long propVal)
{
	SetProperty(0x2d, VT_I4, propVal);
}

long CNXJournalPrinterX::GetMediaPrintAreaHeight()
{
	long result;
	GetProperty(0x2e, VT_I4, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetMediaPrintAreaHeight(long propVal)
{
	SetProperty(0x2e, VT_I4, propVal);
}

long CNXJournalPrinterX::GetMediaRestrictedAreaWidth()
{
	long result;
	GetProperty(0x2f, VT_I4, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetMediaRestrictedAreaWidth(long propVal)
{
	SetProperty(0x2f, VT_I4, propVal);
}

long CNXJournalPrinterX::GetMediaRestrictedAreaX()
{
	long result;
	GetProperty(0x30, VT_I4, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetMediaRestrictedAreaX(long propVal)
{
	SetProperty(0x30, VT_I4, propVal);
}

long CNXJournalPrinterX::GetMediaRestrictedAreaY()
{
	long result;
	GetProperty(0x31, VT_I4, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetMediaRestrictedAreaY(long propVal)
{
	SetProperty(0x31, VT_I4, propVal);
}

long CNXJournalPrinterX::GetMediaRestrictedAreaHeight()
{
	long result;
	GetProperty(0x32, VT_I4, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetMediaRestrictedAreaHeight(long propVal)
{
	SetProperty(0x32, VT_I4, propVal);
}

long CNXJournalPrinterX::GetMediaStagger()
{
	long result;
	GetProperty(0x33, VT_I4, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetMediaStagger(long propVal)
{
	SetProperty(0x33, VT_I4, propVal);
}

CString CNXJournalPrinterX::GetMediaFoldType()
{
	CString result;
	GetProperty(0x34, VT_BSTR, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetMediaFoldType(LPCTSTR propVal)
{
	SetProperty(0x34, VT_BSTR, propVal);
}

short CNXJournalPrinterX::GetFormFieldIndexCount()
{
	short result;
	GetProperty(0x35, VT_I2, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetFormFieldIndexCount(short propVal)
{
	SetProperty(0x35, VT_I2, propVal);
}

CString CNXJournalPrinterX::GetFormFieldOverflow()
{
	CString result;
	GetProperty(0x36, VT_BSTR, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetFormFieldOverflow(LPCTSTR propVal)
{
	SetProperty(0x36, VT_BSTR, propVal);
}

VARIANT CNXJournalPrinterX::GetFormCharSet()
{
	VARIANT result;
	GetProperty(0x37, VT_VARIANT, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetFormCharSet(const VARIANT& propVal)
{
	SetProperty(0x37, VT_VARIANT, &propVal);
}

CString CNXJournalPrinterX::GetMediaPaperSource()
{
	CString result;
	GetProperty(0x38, VT_BSTR, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetMediaPaperSource(LPCTSTR propVal)
{
	SetProperty(0x38, VT_BSTR, propVal);
}

VARIANT CNXJournalPrinterX::GetPaperSupplies()
{
	VARIANT result;
	GetProperty(0x39, VT_VARIANT, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetPaperSupplies(const VARIANT& propVal)
{
	SetProperty(0x39, VT_VARIANT, &propVal);
}

VARIANT CNXJournalPrinterX::GetSupportedCharSets()
{
	VARIANT result;
	GetProperty(0x3a, VT_VARIANT, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetSupportedCharSets(const VARIANT& propVal)
{
	SetProperty(0x3a, VT_VARIANT, &propVal);
}

BOOL CNXJournalPrinterX::GetCanDispensePaper()
{
	BOOL result;
	GetProperty(0x3b, VT_BOOL, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetCanDispensePaper(BOOL propVal)
{
	SetProperty(0x3b, VT_BOOL, propVal);
}

BOOL CNXJournalPrinterX::GetCanAcceptMedia()
{
	BOOL result;
	GetProperty(0x3c, VT_BOOL, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetCanAcceptMedia(BOOL propVal)
{
	SetProperty(0x3c, VT_BOOL, propVal);
}

BOOL CNXJournalPrinterX::GetCanDetectVerticalExtents()
{
	BOOL result;
	GetProperty(0x3d, VT_BOOL, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetCanDetectVerticalExtents(BOOL propVal)
{
	SetProperty(0x3d, VT_BOOL, propVal);
}

BOOL CNXJournalPrinterX::GetCanDetectHorizontalExtents()
{
	BOOL result;
	GetProperty(0x3e, VT_BOOL, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetCanDetectHorizontalExtents(BOOL propVal)
{
	SetProperty(0x3e, VT_BOOL, propVal);
}

short CNXJournalPrinterX::GetNumberOfRetractBins()
{
	short result;
	GetProperty(0x3f, VT_I2, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetNumberOfRetractBins(short propVal)
{
	SetProperty(0x3f, VT_I2, propVal);
}

BOOL CNXJournalPrinterX::GetCanPrintMultiplePages()
{
	BOOL result;
	GetProperty(0x40, VT_BOOL, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetCanPrintMultiplePages(BOOL propVal)
{
	SetProperty(0x40, VT_BOOL, propVal);
}

BOOL CNXJournalPrinterX::GetCanDetectMediaTaken()
{
	BOOL result;
	GetProperty(0x41, VT_BOOL, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetCanDetectMediaTaken(BOOL propVal)
{
	SetProperty(0x41, VT_BOOL, propVal);
}

VARIANT CNXJournalPrinterX::GetImageType()
{
	VARIANT result;
	GetProperty(0x42, VT_VARIANT, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetImageType(const VARIANT& propVal)
{
	SetProperty(0x42, VT_VARIANT, &propVal);
}

VARIANT CNXJournalPrinterX::GetFrontImageColorFormat()
{
	VARIANT result;
	GetProperty(0x43, VT_VARIANT, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetFrontImageColorFormat(const VARIANT& propVal)
{
	SetProperty(0x43, VT_VARIANT, &propVal);
}

VARIANT CNXJournalPrinterX::GetBackImageColorFormat()
{
	VARIANT result;
	GetProperty(0x44, VT_VARIANT, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetBackImageColorFormat(const VARIANT& propVal)
{
	SetProperty(0x44, VT_VARIANT, &propVal);
}

VARIANT CNXJournalPrinterX::GetCodelineFormat()
{
	VARIANT result;
	GetProperty(0x45, VT_VARIANT, (void*)&result);
	return result;
}

void CNXJournalPrinterX::SetCodelineFormat(const VARIANT& propVal)
{
	SetProperty(0x45, VT_VARIANT, &propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CNXJournalPrinterX operations

long CNXJournalPrinterX::OpenSessionSync(long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x46, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Timeout);
	return result;
}

long CNXJournalPrinterX::CloseSessionSync()
{
	long result;
	InvokeHelper(0x47, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXJournalPrinterX::RequestLock(long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x48, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Timeout);
	return result;
}

long CNXJournalPrinterX::ReleaseLock()
{
	long result;
	InvokeHelper(0x49, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

CString CNXJournalPrinterX::GetExtraStatus(LPCTSTR KeyName)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x4a, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		KeyName);
	return result;
}

CString CNXJournalPrinterX::GetExtraCaps(LPCTSTR KeyName)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x4b, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		KeyName);
	return result;
}

long CNXJournalPrinterX::ControlMedia(LPCTSTR Actions, long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4;
	InvokeHelper(0x4c, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Actions, Timeout);
	return result;
}

long CNXJournalPrinterX::QueryForm(LPCTSTR FormName)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x4d, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		FormName);
	return result;
}

long CNXJournalPrinterX::QueryFormList()
{
	long result;
	InvokeHelper(0x4e, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXJournalPrinterX::QueryMediaList()
{
	long result;
	InvokeHelper(0x4f, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXJournalPrinterX::QueryMedia(LPCTSTR MediaName)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x50, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		MediaName);
	return result;
}

long CNXJournalPrinterX::QueryField(LPCTSTR FieldName)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x51, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		FieldName);
	return result;
}

long CNXJournalPrinterX::SendRawData(long HasResponse, LPCTSTR RawData)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_BSTR;
	InvokeHelper(0x52, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		HasResponse, RawData);
	return result;
}

long CNXJournalPrinterX::ReadForm(LPCTSTR FormName, LPCTSTR MediaName, LPCTSTR FieldNames, long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR VTS_I4;
	InvokeHelper(0x53, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		FormName, MediaName, FieldNames, Timeout);
	return result;
}

long CNXJournalPrinterX::GetMediaExtents(LPCTSTR BaseUnit, short UnitX, short UnitY)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_I2 VTS_I2;
	InvokeHelper(0x54, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		BaseUnit, UnitX, UnitY);
	return result;
}

long CNXJournalPrinterX::CancelAccept()
{
	long result;
	InvokeHelper(0x55, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

CString CNXJournalPrinterX::GetFieldValue(LPCTSTR FieldName)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x56, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		FieldName);
	return result;
}

long CNXJournalPrinterX::Reset(LPCTSTR Action, short BinNumber)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_I2;
	InvokeHelper(0x57, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Action, BinNumber);
	return result;
}

long CNXJournalPrinterX::RetractMedia(short BinNumber)
{
	long result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x58, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		BinNumber);
	return result;
}

long CNXJournalPrinterX::DispensePaper(LPCTSTR PaperSource)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x59, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		PaperSource);
	return result;
}

long CNXJournalPrinterX::ResetRetractCount(short BinNumber)
{
	long result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x5a, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		BinNumber);
	return result;
}

long CNXJournalPrinterX::PrintForm(LPCTSTR FormName, LPCTSTR MediaName, LPCTSTR Alignment, short OffsetX, short OffsetY, LPCTSTR Resolution, LPCTSTR FieldValues, long Timeout, LPCTSTR PaperSource)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR VTS_I2 VTS_I2 VTS_BSTR VTS_BSTR VTS_I4 VTS_BSTR;
	InvokeHelper(0x5b, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		FormName, MediaName, Alignment, OffsetX, OffsetY, Resolution, FieldValues, Timeout, PaperSource);
	return result;
}

long CNXJournalPrinterX::CancelWaitForMediaTaken()
{
	long result;
	InvokeHelper(0x5c, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

CString CNXJournalPrinterX::GetPaperStatus(LPCTSTR PaperSupply)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x5d, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, parms,
		PaperSupply);
	return result;
}

CString CNXJournalPrinterX::GetRetractBinStatus(short BinNumber)
{
	CString result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x5e, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, parms,
		BinNumber);
	return result;
}

short CNXJournalPrinterX::GetRetractCount(short BinNumber)
{
	short result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x5f, DISPATCH_PROPERTYGET, VT_I2, (void*)&result, parms,
		BinNumber);
	return result;
}

short CNXJournalPrinterX::GetMaxRetract(short RetractBin)
{
	short result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x60, DISPATCH_PROPERTYGET, VT_I2, (void*)&result, parms,
		RetractBin);
	return result;
}
