#if !defined(AFX_NXOPERATORPANELX_H__51182673_3077_4E8A_B218_6DBE7C14A020__INCLUDED_)
#define AFX_NXOPERATORPANELX_H__51182673_3077_4E8A_B218_6DBE7C14A020__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CNXOperatorPanelX wrapper class

class CNXOperatorPanelX : public CWnd
{
protected:
	DECLARE_DYNCREATE(CNXOperatorPanelX)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x794af094, 0x34be, 0x4382, { 0xb6, 0x2f, 0xf9, 0xbc, 0xc0, 0xee, 0x1a, 0x91 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	CString GetDeviceStatus();
	void SetDeviceStatus(LPCTSTR);
	short GetDisplaySizeX();
	void SetDisplaySizeX(short);
	short GetDisplaySizeY();
	void SetDisplaySizeY(short);
	BOOL GetKeyLockStatus();
	void SetKeyLockStatus(BOOL);
	VARIANT GetLEDStatus();
	void SetLEDStatus(const VARIANT&);
	BOOL GetHasKeyLock();
	void SetHasKeyLock(BOOL);
	BOOL GetHasDisplayLigth();
	void SetHasDisplayLigth(BOOL);
	BOOL GetCanSupportCursor();
	void SetCanSupportCursor(BOOL);
	BOOL GetCanSupportForms();
	void SetCanSupportForms(BOOL);
	VARIANT GetSupportedScreenSizeX();
	void SetSupportedScreenSizeX(const VARIANT&);
	VARIANT GetSupportedScreenSizeY();
	void SetSupportedScreenSizeY(const VARIANT&);
	CString GetKeys();
	void SetKeys(LPCTSTR);
	CString GetCommandKeys();
	void SetCommandKeys(LPCTSTR);
	CString GetSupportedCharSets();
	void SetSupportedCharSets(LPCTSTR);
	long GetFormWidth();
	void SetFormWidth(long);
	long GetFormHeight();
	void SetFormHeight(long);
	long GetFormVersionMajor();
	void SetFormVersionMajor(long);
	long GetFormVersionMinor();
	void SetFormVersionMinor(long);
	CString GetFormCharSet();
	void SetFormCharSet(LPCTSTR);
	CString GetFormFieldType();
	void SetFormFieldType(LPCTSTR);
	CString GetFormFieldClass();
	void SetFormFieldClass(LPCTSTR);
	CString GetFormFieldAccess();
	void SetFormFieldAccess(LPCTSTR);
	CString GetFormFieldOverflow();
	void SetFormFieldOverflow(LPCTSTR);
	CString GetFormFieldFormat();
	void SetFormFieldFormat(LPCTSTR);
	CString GetFormName();
	void SetFormName(LPCTSTR);
	CString GetFormFieldName();
	void SetFormFieldName(LPCTSTR);
	VARIANT GetFormFieldList();
	void SetFormFieldList(const VARIANT&);
	short GetNumOfLEDs();
	void SetNumOfLEDs(short);
	CString GetKeyboardStatus();
	void SetKeyboardStatus(LPCTSTR);

// Operations
public:
	long OpenSessionSync(long Timeout);
	long CloseSessionSync();
	long RequestLock(long Timeout);
	long ReleaseLock();
	CString GetExtraStatus(LPCTSTR KeyName);
	CString GetExtraCaps(LPCTSTR KeyName);
	long Beep(LPCTSTR BeepType, long Continuous);
	long BeepOff();
	long ClearScreen(short TopLeftX, short TopLeftY, short Width, short Height);
	long SetDisplayLight(LPCTSTR LightAction);
	long SetLEDState(short Index, LPCTSTR State);
	long SelectScreenSize(short Width, short Height);
	long WriteForm(LPCTSTR FormName, long ClearScreen, LPCTSTR FieldValues);
	long ReadForm(LPCTSTR FormName, LPCTSTR Fields, short Timeout);
	long CancelRead();
	BOOL GetFieldValue(LPCTSTR FieldName, VARIANT* FieldValue);
	long Write(short x, short y, LPCTSTR TextAttribute, LPCTSTR Text);
	long Read(short x, short y, LPCTSTR TextAttribute, LPCTSTR EchoMode, short Length, long CursorOn, long Flush, long AutoEnd, long Timeout, LPCTSTR ActiveKeys, LPCTSTR ActiveCommandKeys, LPCTSTR TerminateCommandKeys);
	long QueryFormList(VARIANT* FormList);
	long Reset();
	long QueryForm(LPCTSTR FormName);
	long QueryField(LPCTSTR FieldName);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_NXOPERATORPANELX_H__51182673_3077_4E8A_B218_6DBE7C14A020__INCLUDED_)
