// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "nxoperatorpanelx.h"

/////////////////////////////////////////////////////////////////////////////
// CNXOperatorPanelX

IMPLEMENT_DYNCREATE(CNXOperatorPanelX, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CNXOperatorPanelX properties

CString CNXOperatorPanelX::GetDeviceStatus()
{
	CString result;
	GetProperty(0x1, VT_BSTR, (void*)&result);
	return result;
}

void CNXOperatorPanelX::SetDeviceStatus(LPCTSTR propVal)
{
	SetProperty(0x1, VT_BSTR, propVal);
}

short CNXOperatorPanelX::GetDisplaySizeX()
{
	short result;
	GetProperty(0x2, VT_I2, (void*)&result);
	return result;
}

void CNXOperatorPanelX::SetDisplaySizeX(short propVal)
{
	SetProperty(0x2, VT_I2, propVal);
}

short CNXOperatorPanelX::GetDisplaySizeY()
{
	short result;
	GetProperty(0x3, VT_I2, (void*)&result);
	return result;
}

void CNXOperatorPanelX::SetDisplaySizeY(short propVal)
{
	SetProperty(0x3, VT_I2, propVal);
}

BOOL CNXOperatorPanelX::GetKeyLockStatus()
{
	BOOL result;
	GetProperty(0x4, VT_BOOL, (void*)&result);
	return result;
}

void CNXOperatorPanelX::SetKeyLockStatus(BOOL propVal)
{
	SetProperty(0x4, VT_BOOL, propVal);
}

VARIANT CNXOperatorPanelX::GetLEDStatus()
{
	VARIANT result;
	GetProperty(0x5, VT_VARIANT, (void*)&result);
	return result;
}

void CNXOperatorPanelX::SetLEDStatus(const VARIANT& propVal)
{
	SetProperty(0x5, VT_VARIANT, &propVal);
}

BOOL CNXOperatorPanelX::GetHasKeyLock()
{
	BOOL result;
	GetProperty(0x6, VT_BOOL, (void*)&result);
	return result;
}

void CNXOperatorPanelX::SetHasKeyLock(BOOL propVal)
{
	SetProperty(0x6, VT_BOOL, propVal);
}

BOOL CNXOperatorPanelX::GetHasDisplayLigth()
{
	BOOL result;
	GetProperty(0x7, VT_BOOL, (void*)&result);
	return result;
}

void CNXOperatorPanelX::SetHasDisplayLigth(BOOL propVal)
{
	SetProperty(0x7, VT_BOOL, propVal);
}

BOOL CNXOperatorPanelX::GetCanSupportCursor()
{
	BOOL result;
	GetProperty(0x8, VT_BOOL, (void*)&result);
	return result;
}

void CNXOperatorPanelX::SetCanSupportCursor(BOOL propVal)
{
	SetProperty(0x8, VT_BOOL, propVal);
}

BOOL CNXOperatorPanelX::GetCanSupportForms()
{
	BOOL result;
	GetProperty(0x9, VT_BOOL, (void*)&result);
	return result;
}

void CNXOperatorPanelX::SetCanSupportForms(BOOL propVal)
{
	SetProperty(0x9, VT_BOOL, propVal);
}

VARIANT CNXOperatorPanelX::GetSupportedScreenSizeX()
{
	VARIANT result;
	GetProperty(0xa, VT_VARIANT, (void*)&result);
	return result;
}

void CNXOperatorPanelX::SetSupportedScreenSizeX(const VARIANT& propVal)
{
	SetProperty(0xa, VT_VARIANT, &propVal);
}

VARIANT CNXOperatorPanelX::GetSupportedScreenSizeY()
{
	VARIANT result;
	GetProperty(0xb, VT_VARIANT, (void*)&result);
	return result;
}

void CNXOperatorPanelX::SetSupportedScreenSizeY(const VARIANT& propVal)
{
	SetProperty(0xb, VT_VARIANT, &propVal);
}

CString CNXOperatorPanelX::GetKeys()
{
	CString result;
	GetProperty(0xc, VT_BSTR, (void*)&result);
	return result;
}

void CNXOperatorPanelX::SetKeys(LPCTSTR propVal)
{
	SetProperty(0xc, VT_BSTR, propVal);
}

CString CNXOperatorPanelX::GetCommandKeys()
{
	CString result;
	GetProperty(0xd, VT_BSTR, (void*)&result);
	return result;
}

void CNXOperatorPanelX::SetCommandKeys(LPCTSTR propVal)
{
	SetProperty(0xd, VT_BSTR, propVal);
}

CString CNXOperatorPanelX::GetSupportedCharSets()
{
	CString result;
	GetProperty(0xe, VT_BSTR, (void*)&result);
	return result;
}

void CNXOperatorPanelX::SetSupportedCharSets(LPCTSTR propVal)
{
	SetProperty(0xe, VT_BSTR, propVal);
}

long CNXOperatorPanelX::GetFormWidth()
{
	long result;
	GetProperty(0xf, VT_I4, (void*)&result);
	return result;
}

void CNXOperatorPanelX::SetFormWidth(long propVal)
{
	SetProperty(0xf, VT_I4, propVal);
}

long CNXOperatorPanelX::GetFormHeight()
{
	long result;
	GetProperty(0x10, VT_I4, (void*)&result);
	return result;
}

void CNXOperatorPanelX::SetFormHeight(long propVal)
{
	SetProperty(0x10, VT_I4, propVal);
}

long CNXOperatorPanelX::GetFormVersionMajor()
{
	long result;
	GetProperty(0x11, VT_I4, (void*)&result);
	return result;
}

void CNXOperatorPanelX::SetFormVersionMajor(long propVal)
{
	SetProperty(0x11, VT_I4, propVal);
}

long CNXOperatorPanelX::GetFormVersionMinor()
{
	long result;
	GetProperty(0x12, VT_I4, (void*)&result);
	return result;
}

void CNXOperatorPanelX::SetFormVersionMinor(long propVal)
{
	SetProperty(0x12, VT_I4, propVal);
}

CString CNXOperatorPanelX::GetFormCharSet()
{
	CString result;
	GetProperty(0x13, VT_BSTR, (void*)&result);
	return result;
}

void CNXOperatorPanelX::SetFormCharSet(LPCTSTR propVal)
{
	SetProperty(0x13, VT_BSTR, propVal);
}

CString CNXOperatorPanelX::GetFormFieldType()
{
	CString result;
	GetProperty(0x14, VT_BSTR, (void*)&result);
	return result;
}

void CNXOperatorPanelX::SetFormFieldType(LPCTSTR propVal)
{
	SetProperty(0x14, VT_BSTR, propVal);
}

CString CNXOperatorPanelX::GetFormFieldClass()
{
	CString result;
	GetProperty(0x15, VT_BSTR, (void*)&result);
	return result;
}

void CNXOperatorPanelX::SetFormFieldClass(LPCTSTR propVal)
{
	SetProperty(0x15, VT_BSTR, propVal);
}

CString CNXOperatorPanelX::GetFormFieldAccess()
{
	CString result;
	GetProperty(0x16, VT_BSTR, (void*)&result);
	return result;
}

void CNXOperatorPanelX::SetFormFieldAccess(LPCTSTR propVal)
{
	SetProperty(0x16, VT_BSTR, propVal);
}

CString CNXOperatorPanelX::GetFormFieldOverflow()
{
	CString result;
	GetProperty(0x17, VT_BSTR, (void*)&result);
	return result;
}

void CNXOperatorPanelX::SetFormFieldOverflow(LPCTSTR propVal)
{
	SetProperty(0x17, VT_BSTR, propVal);
}

CString CNXOperatorPanelX::GetFormFieldFormat()
{
	CString result;
	GetProperty(0x18, VT_BSTR, (void*)&result);
	return result;
}

void CNXOperatorPanelX::SetFormFieldFormat(LPCTSTR propVal)
{
	SetProperty(0x18, VT_BSTR, propVal);
}

CString CNXOperatorPanelX::GetFormName()
{
	CString result;
	GetProperty(0x19, VT_BSTR, (void*)&result);
	return result;
}

void CNXOperatorPanelX::SetFormName(LPCTSTR propVal)
{
	SetProperty(0x19, VT_BSTR, propVal);
}

CString CNXOperatorPanelX::GetFormFieldName()
{
	CString result;
	GetProperty(0x1a, VT_BSTR, (void*)&result);
	return result;
}

void CNXOperatorPanelX::SetFormFieldName(LPCTSTR propVal)
{
	SetProperty(0x1a, VT_BSTR, propVal);
}

VARIANT CNXOperatorPanelX::GetFormFieldList()
{
	VARIANT result;
	GetProperty(0x1b, VT_VARIANT, (void*)&result);
	return result;
}

void CNXOperatorPanelX::SetFormFieldList(const VARIANT& propVal)
{
	SetProperty(0x1b, VT_VARIANT, &propVal);
}

short CNXOperatorPanelX::GetNumOfLEDs()
{
	short result;
	GetProperty(0x1c, VT_I2, (void*)&result);
	return result;
}

void CNXOperatorPanelX::SetNumOfLEDs(short propVal)
{
	SetProperty(0x1c, VT_I2, propVal);
}

CString CNXOperatorPanelX::GetKeyboardStatus()
{
	CString result;
	GetProperty(0x1d, VT_BSTR, (void*)&result);
	return result;
}

void CNXOperatorPanelX::SetKeyboardStatus(LPCTSTR propVal)
{
	SetProperty(0x1d, VT_BSTR, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CNXOperatorPanelX operations

long CNXOperatorPanelX::OpenSessionSync(long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x1e, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Timeout);
	return result;
}

long CNXOperatorPanelX::CloseSessionSync()
{
	long result;
	InvokeHelper(0x1f, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXOperatorPanelX::RequestLock(long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x20, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Timeout);
	return result;
}

long CNXOperatorPanelX::ReleaseLock()
{
	long result;
	InvokeHelper(0x21, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

CString CNXOperatorPanelX::GetExtraStatus(LPCTSTR KeyName)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x22, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		KeyName);
	return result;
}

CString CNXOperatorPanelX::GetExtraCaps(LPCTSTR KeyName)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x23, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		KeyName);
	return result;
}

long CNXOperatorPanelX::Beep(LPCTSTR BeepType, long Continuous)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4;
	InvokeHelper(0x24, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		BeepType, Continuous);
	return result;
}

long CNXOperatorPanelX::BeepOff()
{
	long result;
	InvokeHelper(0x25, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXOperatorPanelX::ClearScreen(short TopLeftX, short TopLeftY, short Width, short Height)
{
	long result;
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_I2 VTS_I2;
	InvokeHelper(0x26, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		TopLeftX, TopLeftY, Width, Height);
	return result;
}

long CNXOperatorPanelX::SetDisplayLight(LPCTSTR LightAction)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x27, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		LightAction);
	return result;
}

long CNXOperatorPanelX::SetLEDState(short Index, LPCTSTR State)
{
	long result;
	static BYTE parms[] =
		VTS_I2 VTS_BSTR;
	InvokeHelper(0x28, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Index, State);
	return result;
}

long CNXOperatorPanelX::SelectScreenSize(short Width, short Height)
{
	long result;
	static BYTE parms[] =
		VTS_I2 VTS_I2;
	InvokeHelper(0x29, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Width, Height);
	return result;
}

long CNXOperatorPanelX::WriteForm(LPCTSTR FormName, long ClearScreen, LPCTSTR FieldValues)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4 VTS_BSTR;
	InvokeHelper(0x2a, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		FormName, ClearScreen, FieldValues);
	return result;
}

long CNXOperatorPanelX::ReadForm(LPCTSTR FormName, LPCTSTR Fields, short Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_I2;
	InvokeHelper(0x2b, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		FormName, Fields, Timeout);
	return result;
}

long CNXOperatorPanelX::CancelRead()
{
	long result;
	InvokeHelper(0x2c, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

BOOL CNXOperatorPanelX::GetFieldValue(LPCTSTR FieldName, VARIANT* FieldValue)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_PVARIANT;
	InvokeHelper(0x2d, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		FieldName, FieldValue);
	return result;
}

long CNXOperatorPanelX::Write(short x, short y, LPCTSTR TextAttribute, LPCTSTR Text)
{
	long result;
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_BSTR VTS_BSTR;
	InvokeHelper(0x2e, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		x, y, TextAttribute, Text);
	return result;
}

long CNXOperatorPanelX::Read(short x, short y, LPCTSTR TextAttribute, LPCTSTR EchoMode, short Length, long CursorOn, long Flush, long AutoEnd, long Timeout, LPCTSTR ActiveKeys, LPCTSTR ActiveCommandKeys, LPCTSTR TerminateCommandKeys)
{
	long result;
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_BSTR VTS_BSTR VTS_I2 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x2f, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		x, y, TextAttribute, EchoMode, Length, CursorOn, Flush, AutoEnd, Timeout, ActiveKeys, ActiveCommandKeys, TerminateCommandKeys);
	return result;
}

long CNXOperatorPanelX::QueryFormList(VARIANT* FormList)
{
	long result;
	static BYTE parms[] =
		VTS_PVARIANT;
	InvokeHelper(0x30, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		FormList);
	return result;
}

long CNXOperatorPanelX::Reset()
{
	long result;
	InvokeHelper(0x31, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXOperatorPanelX::QueryForm(LPCTSTR FormName)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x32, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		FormName);
	return result;
}

long CNXOperatorPanelX::QueryField(LPCTSTR FieldName)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x33, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		FieldName);
	return result;
}

void CNXOperatorPanelX::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
