// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "nxpassbookprinterx.h"

/////////////////////////////////////////////////////////////////////////////
// CNXPassbookPrinterX

IMPLEMENT_DYNCREATE(CNXPassbookPrinterX, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CNXPassbookPrinterX properties

CString CNXPassbookPrinterX::GetDeviceStatus()
{
	CString result;
	GetProperty(0x1, VT_BSTR, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetDeviceStatus(LPCTSTR propVal)
{
	SetProperty(0x1, VT_BSTR, propVal);
}

CString CNXPassbookPrinterX::GetMediaStatus()
{
	CString result;
	GetProperty(0x2, VT_BSTR, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetMediaStatus(LPCTSTR propVal)
{
	SetProperty(0x2, VT_BSTR, propVal);
}

CString CNXPassbookPrinterX::GetTonerStatus()
{
	CString result;
	GetProperty(0x3, VT_BSTR, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetTonerStatus(LPCTSTR propVal)
{
	SetProperty(0x3, VT_BSTR, propVal);
}

CString CNXPassbookPrinterX::GetInkStatus()
{
	CString result;
	GetProperty(0x4, VT_BSTR, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetInkStatus(LPCTSTR propVal)
{
	SetProperty(0x4, VT_BSTR, propVal);
}

CString CNXPassbookPrinterX::GetLampStatus()
{
	CString result;
	GetProperty(0x5, VT_BSTR, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetLampStatus(LPCTSTR propVal)
{
	SetProperty(0x5, VT_BSTR, propVal);
}

short CNXPassbookPrinterX::GetMediaOnStackerCount()
{
	short result;
	GetProperty(0x6, VT_I2, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetMediaOnStackerCount(short propVal)
{
	SetProperty(0x6, VT_I2, propVal);
}

VARIANT CNXPassbookPrinterX::GetResolution()
{
	VARIANT result;
	GetProperty(0x7, VT_VARIANT, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetResolution(const VARIANT& propVal)
{
	SetProperty(0x7, VT_VARIANT, &propVal);
}

VARIANT CNXPassbookPrinterX::GetReadTypes()
{
	VARIANT result;
	GetProperty(0x8, VT_VARIANT, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetReadTypes(const VARIANT& propVal)
{
	SetProperty(0x8, VT_VARIANT, &propVal);
}

VARIANT CNXPassbookPrinterX::GetWriteTypes()
{
	VARIANT result;
	GetProperty(0x9, VT_VARIANT, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetWriteTypes(const VARIANT& propVal)
{
	SetProperty(0x9, VT_VARIANT, &propVal);
}

VARIANT CNXPassbookPrinterX::GetControlMediaActions()
{
	VARIANT result;
	GetProperty(0xa, VT_VARIANT, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetControlMediaActions(const VARIANT& propVal)
{
	SetProperty(0xa, VT_VARIANT, &propVal);
}

short CNXPassbookPrinterX::GetMaxMediaOnStacker()
{
	short result;
	GetProperty(0xb, VT_I2, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetMaxMediaOnStacker(short propVal)
{
	SetProperty(0xb, VT_I2, propVal);
}

VARIANT CNXPassbookPrinterX::GetFormList()
{
	VARIANT result;
	GetProperty(0xc, VT_VARIANT, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetFormList(const VARIANT& propVal)
{
	SetProperty(0xc, VT_VARIANT, &propVal);
}

CString CNXPassbookPrinterX::GetFormName()
{
	CString result;
	GetProperty(0xd, VT_BSTR, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetFormName(LPCTSTR propVal)
{
	SetProperty(0xd, VT_BSTR, propVal);
}

CString CNXPassbookPrinterX::GetFormAlignment()
{
	CString result;
	GetProperty(0xe, VT_BSTR, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetFormAlignment(LPCTSTR propVal)
{
	SetProperty(0xe, VT_BSTR, propVal);
}

long CNXPassbookPrinterX::GetFormUnitX()
{
	long result;
	GetProperty(0xf, VT_I4, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetFormUnitX(long propVal)
{
	SetProperty(0xf, VT_I4, propVal);
}

long CNXPassbookPrinterX::GetFormUnitY()
{
	long result;
	GetProperty(0x10, VT_I4, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetFormUnitY(long propVal)
{
	SetProperty(0x10, VT_I4, propVal);
}

long CNXPassbookPrinterX::GetFormWidth()
{
	long result;
	GetProperty(0x11, VT_I4, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetFormWidth(long propVal)
{
	SetProperty(0x11, VT_I4, propVal);
}

long CNXPassbookPrinterX::GetFormHeight()
{
	long result;
	GetProperty(0x12, VT_I4, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetFormHeight(long propVal)
{
	SetProperty(0x12, VT_I4, propVal);
}

CString CNXPassbookPrinterX::GetFormBase()
{
	CString result;
	GetProperty(0x13, VT_BSTR, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetFormBase(LPCTSTR propVal)
{
	SetProperty(0x13, VT_BSTR, propVal);
}

CString CNXPassbookPrinterX::GetFormOrientation()
{
	CString result;
	GetProperty(0x14, VT_BSTR, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetFormOrientation(LPCTSTR propVal)
{
	SetProperty(0x14, VT_BSTR, propVal);
}

long CNXPassbookPrinterX::GetFormOffsetX()
{
	long result;
	GetProperty(0x15, VT_I4, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetFormOffsetX(long propVal)
{
	SetProperty(0x15, VT_I4, propVal);
}

long CNXPassbookPrinterX::GetFormOffsetY()
{
	long result;
	GetProperty(0x16, VT_I4, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetFormOffsetY(long propVal)
{
	SetProperty(0x16, VT_I4, propVal);
}

long CNXPassbookPrinterX::GetFormVersionMajor()
{
	long result;
	GetProperty(0x17, VT_I4, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetFormVersionMajor(long propVal)
{
	SetProperty(0x17, VT_I4, propVal);
}

long CNXPassbookPrinterX::GetFormVersionMinor()
{
	long result;
	GetProperty(0x18, VT_I4, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetFormVersionMinor(long propVal)
{
	SetProperty(0x18, VT_I4, propVal);
}

CString CNXPassbookPrinterX::GetFormUserPrompt()
{
	CString result;
	GetProperty(0x19, VT_BSTR, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetFormUserPrompt(LPCTSTR propVal)
{
	SetProperty(0x19, VT_BSTR, propVal);
}

VARIANT CNXPassbookPrinterX::GetFormFieldList()
{
	VARIANT result;
	GetProperty(0x1a, VT_VARIANT, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetFormFieldList(const VARIANT& propVal)
{
	SetProperty(0x1a, VT_VARIANT, &propVal);
}

CString CNXPassbookPrinterX::GetFormFieldName()
{
	CString result;
	GetProperty(0x1b, VT_BSTR, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetFormFieldName(LPCTSTR propVal)
{
	SetProperty(0x1b, VT_BSTR, propVal);
}

CString CNXPassbookPrinterX::GetFormFieldType()
{
	CString result;
	GetProperty(0x1c, VT_BSTR, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetFormFieldType(LPCTSTR propVal)
{
	SetProperty(0x1c, VT_BSTR, propVal);
}

CString CNXPassbookPrinterX::GetFormFieldClass()
{
	CString result;
	GetProperty(0x1d, VT_BSTR, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetFormFieldClass(LPCTSTR propVal)
{
	SetProperty(0x1d, VT_BSTR, propVal);
}

CString CNXPassbookPrinterX::GetFormFieldAccess()
{
	CString result;
	GetProperty(0x1e, VT_BSTR, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetFormFieldAccess(LPCTSTR propVal)
{
	SetProperty(0x1e, VT_BSTR, propVal);
}

CString CNXPassbookPrinterX::GetFormFieldInitialValue()
{
	CString result;
	GetProperty(0x1f, VT_BSTR, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetFormFieldInitialValue(LPCTSTR propVal)
{
	SetProperty(0x1f, VT_BSTR, propVal);
}

CString CNXPassbookPrinterX::GetFormFieldFormat()
{
	CString result;
	GetProperty(0x20, VT_BSTR, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetFormFieldFormat(LPCTSTR propVal)
{
	SetProperty(0x20, VT_BSTR, propVal);
}

VARIANT CNXPassbookPrinterX::GetMediaList()
{
	VARIANT result;
	GetProperty(0x21, VT_VARIANT, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetMediaList(const VARIANT& propVal)
{
	SetProperty(0x21, VT_VARIANT, &propVal);
}

CString CNXPassbookPrinterX::GetMediaName()
{
	CString result;
	GetProperty(0x22, VT_BSTR, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetMediaName(LPCTSTR propVal)
{
	SetProperty(0x22, VT_BSTR, propVal);
}

CString CNXPassbookPrinterX::GetMediaType()
{
	CString result;
	GetProperty(0x23, VT_BSTR, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetMediaType(LPCTSTR propVal)
{
	SetProperty(0x23, VT_BSTR, propVal);
}

CString CNXPassbookPrinterX::GetMediaBase()
{
	CString result;
	GetProperty(0x24, VT_BSTR, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetMediaBase(LPCTSTR propVal)
{
	SetProperty(0x24, VT_BSTR, propVal);
}

long CNXPassbookPrinterX::GetMediaUnitX()
{
	long result;
	GetProperty(0x25, VT_I4, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetMediaUnitX(long propVal)
{
	SetProperty(0x25, VT_I4, propVal);
}

long CNXPassbookPrinterX::GetMediaUnitY()
{
	long result;
	GetProperty(0x26, VT_I4, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetMediaUnitY(long propVal)
{
	SetProperty(0x26, VT_I4, propVal);
}

long CNXPassbookPrinterX::GetMediaSizeWidth()
{
	long result;
	GetProperty(0x27, VT_I4, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetMediaSizeWidth(long propVal)
{
	SetProperty(0x27, VT_I4, propVal);
}

long CNXPassbookPrinterX::GetMediaSizeHeight()
{
	long result;
	GetProperty(0x28, VT_I4, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetMediaSizeHeight(long propVal)
{
	SetProperty(0x28, VT_I4, propVal);
}

long CNXPassbookPrinterX::GetMediaPageCount()
{
	long result;
	GetProperty(0x29, VT_I4, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetMediaPageCount(long propVal)
{
	SetProperty(0x29, VT_I4, propVal);
}

long CNXPassbookPrinterX::GetMediaLineCount()
{
	long result;
	GetProperty(0x2a, VT_I4, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetMediaLineCount(long propVal)
{
	SetProperty(0x2a, VT_I4, propVal);
}

long CNXPassbookPrinterX::GetMediaPrintAreaX()
{
	long result;
	GetProperty(0x2b, VT_I4, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetMediaPrintAreaX(long propVal)
{
	SetProperty(0x2b, VT_I4, propVal);
}

long CNXPassbookPrinterX::GetMediaPrintAreaY()
{
	long result;
	GetProperty(0x2c, VT_I4, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetMediaPrintAreaY(long propVal)
{
	SetProperty(0x2c, VT_I4, propVal);
}

long CNXPassbookPrinterX::GetMediaPrintAreaWidth()
{
	long result;
	GetProperty(0x2d, VT_I4, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetMediaPrintAreaWidth(long propVal)
{
	SetProperty(0x2d, VT_I4, propVal);
}

long CNXPassbookPrinterX::GetMediaPrintAreaHeight()
{
	long result;
	GetProperty(0x2e, VT_I4, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetMediaPrintAreaHeight(long propVal)
{
	SetProperty(0x2e, VT_I4, propVal);
}

long CNXPassbookPrinterX::GetMediaRestrictedAreaWidth()
{
	long result;
	GetProperty(0x2f, VT_I4, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetMediaRestrictedAreaWidth(long propVal)
{
	SetProperty(0x2f, VT_I4, propVal);
}

long CNXPassbookPrinterX::GetMediaRestrictedAreaX()
{
	long result;
	GetProperty(0x30, VT_I4, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetMediaRestrictedAreaX(long propVal)
{
	SetProperty(0x30, VT_I4, propVal);
}

long CNXPassbookPrinterX::GetMediaRestrictedAreaY()
{
	long result;
	GetProperty(0x31, VT_I4, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetMediaRestrictedAreaY(long propVal)
{
	SetProperty(0x31, VT_I4, propVal);
}

long CNXPassbookPrinterX::GetMediaRestrictedAreaHeight()
{
	long result;
	GetProperty(0x32, VT_I4, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetMediaRestrictedAreaHeight(long propVal)
{
	SetProperty(0x32, VT_I4, propVal);
}

long CNXPassbookPrinterX::GetMediaStagger()
{
	long result;
	GetProperty(0x33, VT_I4, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetMediaStagger(long propVal)
{
	SetProperty(0x33, VT_I4, propVal);
}

CString CNXPassbookPrinterX::GetMediaFoldType()
{
	CString result;
	GetProperty(0x34, VT_BSTR, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetMediaFoldType(LPCTSTR propVal)
{
	SetProperty(0x34, VT_BSTR, propVal);
}

short CNXPassbookPrinterX::GetFormFieldIndexCount()
{
	short result;
	GetProperty(0x35, VT_I2, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetFormFieldIndexCount(short propVal)
{
	SetProperty(0x35, VT_I2, propVal);
}

CString CNXPassbookPrinterX::GetFormFieldOverflow()
{
	CString result;
	GetProperty(0x36, VT_BSTR, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetFormFieldOverflow(LPCTSTR propVal)
{
	SetProperty(0x36, VT_BSTR, propVal);
}

VARIANT CNXPassbookPrinterX::GetFormCharSet()
{
	VARIANT result;
	GetProperty(0x37, VT_VARIANT, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetFormCharSet(const VARIANT& propVal)
{
	SetProperty(0x37, VT_VARIANT, &propVal);
}

CString CNXPassbookPrinterX::GetMediaPaperSource()
{
	CString result;
	GetProperty(0x38, VT_BSTR, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetMediaPaperSource(LPCTSTR propVal)
{
	SetProperty(0x38, VT_BSTR, propVal);
}

VARIANT CNXPassbookPrinterX::GetPaperSupplies()
{
	VARIANT result;
	GetProperty(0x39, VT_VARIANT, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetPaperSupplies(const VARIANT& propVal)
{
	SetProperty(0x39, VT_VARIANT, &propVal);
}

VARIANT CNXPassbookPrinterX::GetSupportedCharSets()
{
	VARIANT result;
	GetProperty(0x3a, VT_VARIANT, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetSupportedCharSets(const VARIANT& propVal)
{
	SetProperty(0x3a, VT_VARIANT, &propVal);
}

BOOL CNXPassbookPrinterX::GetCanDispensePaper()
{
	BOOL result;
	GetProperty(0x3b, VT_BOOL, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetCanDispensePaper(BOOL propVal)
{
	SetProperty(0x3b, VT_BOOL, propVal);
}

BOOL CNXPassbookPrinterX::GetCanAcceptMedia()
{
	BOOL result;
	GetProperty(0x3c, VT_BOOL, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetCanAcceptMedia(BOOL propVal)
{
	SetProperty(0x3c, VT_BOOL, propVal);
}

BOOL CNXPassbookPrinterX::GetCanDetectVerticalExtents()
{
	BOOL result;
	GetProperty(0x3d, VT_BOOL, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetCanDetectVerticalExtents(BOOL propVal)
{
	SetProperty(0x3d, VT_BOOL, propVal);
}

BOOL CNXPassbookPrinterX::GetCanDetectHorizontalExtents()
{
	BOOL result;
	GetProperty(0x3e, VT_BOOL, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetCanDetectHorizontalExtents(BOOL propVal)
{
	SetProperty(0x3e, VT_BOOL, propVal);
}

short CNXPassbookPrinterX::GetNumberOfRetractBins()
{
	short result;
	GetProperty(0x3f, VT_I2, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetNumberOfRetractBins(short propVal)
{
	SetProperty(0x3f, VT_I2, propVal);
}

BOOL CNXPassbookPrinterX::GetCanPrintMultiplePages()
{
	BOOL result;
	GetProperty(0x40, VT_BOOL, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetCanPrintMultiplePages(BOOL propVal)
{
	SetProperty(0x40, VT_BOOL, propVal);
}

BOOL CNXPassbookPrinterX::GetCanDetectMediaTaken()
{
	BOOL result;
	GetProperty(0x41, VT_BOOL, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetCanDetectMediaTaken(BOOL propVal)
{
	SetProperty(0x41, VT_BOOL, propVal);
}

VARIANT CNXPassbookPrinterX::GetImageType()
{
	VARIANT result;
	GetProperty(0x42, VT_VARIANT, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetImageType(const VARIANT& propVal)
{
	SetProperty(0x42, VT_VARIANT, &propVal);
}

VARIANT CNXPassbookPrinterX::GetFrontImageColorFormat()
{
	VARIANT result;
	GetProperty(0x43, VT_VARIANT, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetFrontImageColorFormat(const VARIANT& propVal)
{
	SetProperty(0x43, VT_VARIANT, &propVal);
}

VARIANT CNXPassbookPrinterX::GetBackImageColorFormat()
{
	VARIANT result;
	GetProperty(0x44, VT_VARIANT, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetBackImageColorFormat(const VARIANT& propVal)
{
	SetProperty(0x44, VT_VARIANT, &propVal);
}

VARIANT CNXPassbookPrinterX::GetCodelineFormat()
{
	VARIANT result;
	GetProperty(0x45, VT_VARIANT, (void*)&result);
	return result;
}

void CNXPassbookPrinterX::SetCodelineFormat(const VARIANT& propVal)
{
	SetProperty(0x45, VT_VARIANT, &propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CNXPassbookPrinterX operations

long CNXPassbookPrinterX::OpenSessionSync(long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x46, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Timeout);
	return result;
}

long CNXPassbookPrinterX::CloseSessionSync()
{
	long result;
	InvokeHelper(0x47, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXPassbookPrinterX::RequestLock(long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x48, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Timeout);
	return result;
}

long CNXPassbookPrinterX::ReleaseLock()
{
	long result;
	InvokeHelper(0x49, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

CString CNXPassbookPrinterX::GetExtraStatus(LPCTSTR KeyName)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x4a, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		KeyName);
	return result;
}

CString CNXPassbookPrinterX::GetExtraCaps(LPCTSTR KeyName)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x4b, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		KeyName);
	return result;
}

long CNXPassbookPrinterX::ControlMedia(LPCTSTR Actions, long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4;
	InvokeHelper(0x4c, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Actions, Timeout);
	return result;
}

long CNXPassbookPrinterX::QueryForm(LPCTSTR FormName)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x4d, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		FormName);
	return result;
}

long CNXPassbookPrinterX::QueryFormList()
{
	long result;
	InvokeHelper(0x4e, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXPassbookPrinterX::QueryMediaList()
{
	long result;
	InvokeHelper(0x4f, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXPassbookPrinterX::QueryMedia(LPCTSTR MediaName)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x50, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		MediaName);
	return result;
}

long CNXPassbookPrinterX::QueryField(LPCTSTR FieldName)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x51, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		FieldName);
	return result;
}

long CNXPassbookPrinterX::SendRawData(long HasResponse, LPCTSTR RawData)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_BSTR;
	InvokeHelper(0x52, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		HasResponse, RawData);
	return result;
}

long CNXPassbookPrinterX::ReadForm(LPCTSTR FormName, LPCTSTR MediaName, LPCTSTR FieldNames, long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR VTS_I4;
	InvokeHelper(0x53, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		FormName, MediaName, FieldNames, Timeout);
	return result;
}

long CNXPassbookPrinterX::GetMediaExtents(LPCTSTR BaseUnit, short UnitX, short UnitY)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_I2 VTS_I2;
	InvokeHelper(0x54, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		BaseUnit, UnitX, UnitY);
	return result;
}

long CNXPassbookPrinterX::CancelAccept()
{
	long result;
	InvokeHelper(0x55, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

CString CNXPassbookPrinterX::GetFieldValue(LPCTSTR FieldName)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x56, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		FieldName);
	return result;
}

long CNXPassbookPrinterX::Reset(LPCTSTR Action, short BinNumber)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_I2;
	InvokeHelper(0x57, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Action, BinNumber);
	return result;
}

long CNXPassbookPrinterX::RetractMedia(short BinNumber)
{
	long result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x58, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		BinNumber);
	return result;
}

long CNXPassbookPrinterX::DispensePaper(LPCTSTR PaperSource)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x59, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		PaperSource);
	return result;
}

long CNXPassbookPrinterX::ResetRetractCount(short BinNumber)
{
	long result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x5a, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		BinNumber);
	return result;
}

long CNXPassbookPrinterX::PrintForm(LPCTSTR FormName, LPCTSTR MediaName, LPCTSTR Alignment, short OffsetX, short OffsetY, LPCTSTR Resolution, LPCTSTR FieldValues, long Timeout, LPCTSTR PaperSource)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR VTS_I2 VTS_I2 VTS_BSTR VTS_BSTR VTS_I4 VTS_BSTR;
	InvokeHelper(0x5b, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		FormName, MediaName, Alignment, OffsetX, OffsetY, Resolution, FieldValues, Timeout, PaperSource);
	return result;
}

long CNXPassbookPrinterX::CancelWaitForMediaTaken()
{
	long result;
	InvokeHelper(0x5c, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

CString CNXPassbookPrinterX::GetPaperStatus(LPCTSTR PaperSupply)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x5d, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, parms,
		PaperSupply);
	return result;
}

CString CNXPassbookPrinterX::GetRetractBinStatus(short BinNumber)
{
	CString result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x5e, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, parms,
		BinNumber);
	return result;
}

short CNXPassbookPrinterX::GetRetractCount(short BinNumber)
{
	short result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x5f, DISPATCH_PROPERTYGET, VT_I2, (void*)&result, parms,
		BinNumber);
	return result;
}

short CNXPassbookPrinterX::GetMaxRetract(short BinNumber)
{
	short result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x60, DISPATCH_PROPERTYGET, VT_I2, (void*)&result, parms,
		BinNumber);
	return result;
}
