// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "nxpinx.h"

/////////////////////////////////////////////////////////////////////////////
// CNXPinX 

IMPLEMENT_DYNCREATE(CNXPinX, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CNXPinX properties

CString CNXPinX::GetDeviceStatus()
{
	CString result;
	GetProperty(0x1, VT_BSTR, (void*)&result);
	return result;
}

void CNXPinX::SetDeviceStatus(LPCTSTR propVal)
{
	SetProperty(0x1, VT_BSTR, propVal);
}

long CNXPinX::GetNumberOfFDKs()
{
	long result;
	GetProperty(0x2, VT_I4, (void*)&result);
	return result;
}

void CNXPinX::SetNumberOfFDKs(long propVal)
{
	SetProperty(0x2, VT_I4, propVal);
}

CString CNXPinX::GetFunctionKeys()
{
	CString result;
	GetProperty(0x3, VT_BSTR, (void*)&result);
	return result;
}

void CNXPinX::SetFunctionKeys(LPCTSTR propVal)
{
	SetProperty(0x3, VT_BSTR, propVal);
}

CString CNXPinX::GetEncStatus()
{
	CString result;
	GetProperty(0x4, VT_BSTR, (void*)&result);
	return result;
}

void CNXPinX::SetEncStatus(LPCTSTR propVal)
{
	SetProperty(0x4, VT_BSTR, propVal);
}

BOOL CNXPinX::GetCanDESECB()
{
	BOOL result;
	GetProperty(0x5, VT_BOOL, (void*)&result);
	return result;
}

void CNXPinX::SetCanDESECB(BOOL propVal)
{
	SetProperty(0x5, VT_BOOL, propVal);
}

BOOL CNXPinX::GetCanDESCBC()
{
	BOOL result;
	GetProperty(0x6, VT_BOOL, (void*)&result);
	return result;
}

void CNXPinX::SetCanDESCBC(BOOL propVal)
{
	SetProperty(0x6, VT_BOOL, propVal);
}

BOOL CNXPinX::GetCanDESMAC()
{
	BOOL result;
	GetProperty(0x7, VT_BOOL, (void*)&result);
	return result;
}

void CNXPinX::SetCanDESMAC(BOOL propVal)
{
	SetProperty(0x7, VT_BOOL, propVal);
}

BOOL CNXPinX::GetCan3624()
{
	BOOL result;
	GetProperty(0x8, VT_BOOL, (void*)&result);
	return result;
}

void CNXPinX::SetCan3624(BOOL propVal)
{
	SetProperty(0x8, VT_BOOL, propVal);
}

BOOL CNXPinX::GetCanANSI()
{
	BOOL result;
	GetProperty(0x9, VT_BOOL, (void*)&result);
	return result;
}

void CNXPinX::SetCanANSI(BOOL propVal)
{
	SetProperty(0x9, VT_BOOL, propVal);
}

BOOL CNXPinX::GetCanISO0()
{
	BOOL result;
	GetProperty(0xa, VT_BOOL, (void*)&result);
	return result;
}

void CNXPinX::SetCanISO0(BOOL propVal)
{
	SetProperty(0xa, VT_BOOL, propVal);
}

BOOL CNXPinX::GetCanISO1()
{
	BOOL result;
	GetProperty(0xb, VT_BOOL, (void*)&result);
	return result;
}

void CNXPinX::SetCanISO1(BOOL propVal)
{
	SetProperty(0xb, VT_BOOL, propVal);
}

BOOL CNXPinX::GetCanECI2()
{
	BOOL result;
	GetProperty(0xc, VT_BOOL, (void*)&result);
	return result;
}

void CNXPinX::SetCanECI2(BOOL propVal)
{
	SetProperty(0xc, VT_BOOL, propVal);
}

BOOL CNXPinX::GetCanECI3()
{
	BOOL result;
	GetProperty(0xd, VT_BOOL, (void*)&result);
	return result;
}

void CNXPinX::SetCanECI3(BOOL propVal)
{
	SetProperty(0xd, VT_BOOL, propVal);
}

BOOL CNXPinX::GetCanDIEBOLD()
{
	BOOL result;
	GetProperty(0xe, VT_BOOL, (void*)&result);
	return result;
}

void CNXPinX::SetCanDIEBOLD(BOOL propVal)
{
	SetProperty(0xe, VT_BOOL, propVal);
}

BOOL CNXPinX::GetCanDIEBOLDCO()
{
	BOOL result;
	GetProperty(0xf, VT_BOOL, (void*)&result);
	return result;
}

void CNXPinX::SetCanDIEBOLDCO(BOOL propVal)
{
	SetProperty(0xf, VT_BOOL, propVal);
}

BOOL CNXPinX::GetCanVISA3()
{
	BOOL result;
	GetProperty(0x10, VT_BOOL, (void*)&result);
	return result;
}

void CNXPinX::SetCanVISA3(BOOL propVal)
{
	SetProperty(0x10, VT_BOOL, propVal);
}

BOOL CNXPinX::GetCanBANKSYS()
{
	BOOL result;
	GetProperty(0x11, VT_BOOL, (void*)&result);
	return result;
}

void CNXPinX::SetCanBANKSYS(BOOL propVal)
{
	SetProperty(0x11, VT_BOOL, propVal);
}

BOOL CNXPinX::GetCanTRIDESECB()
{
	BOOL result;
	GetProperty(0x12, VT_BOOL, (void*)&result);
	return result;
}

void CNXPinX::SetCanTRIDESECB(BOOL propVal)
{
	SetProperty(0x12, VT_BOOL, propVal);
}

BOOL CNXPinX::GetCanTRIDESCBC()
{
	BOOL result;
	GetProperty(0x13, VT_BOOL, (void*)&result);
	return result;
}

void CNXPinX::SetCanTRIDESCBC(BOOL propVal)
{
	SetProperty(0x13, VT_BOOL, propVal);
}

BOOL CNXPinX::GetCanTRIDESMAC()
{
	BOOL result;
	GetProperty(0x14, VT_BOOL, (void*)&result);
	return result;
}

void CNXPinX::SetCanTRIDESMAC(BOOL propVal)
{
	SetProperty(0x14, VT_BOOL, propVal);
}

CString CNXPinX::GetDeviceType()
{
	CString result;
	GetProperty(0x43, VT_BSTR, (void*)&result);
	return result;
}

void CNXPinX::SetDeviceType(LPCTSTR propVal)
{
	SetProperty(0x43, VT_BSTR, propVal);
}

BOOL CNXPinX::GetSupportedJournaling()
{
	BOOL result;
	GetProperty(0x44, VT_BOOL, (void*)&result);
	return result;
}

void CNXPinX::SetSupportedJournaling(BOOL propVal)
{
	SetProperty(0x44, VT_BOOL, propVal);
}

BOOL CNXPinX::GetSupportedMultiPartKeyImport()
{
	BOOL result;
	GetProperty(0x45, VT_BOOL, (void*)&result);
	return result;
}

void CNXPinX::SetSupportedMultiPartKeyImport(BOOL propVal)
{
	SetProperty(0x45, VT_BOOL, propVal);
}

VARIANT CNXPinX::GetKeyName()
{
	VARIANT result;
	GetProperty(0x46, VT_VARIANT, (void*)&result);
	return result;
}

void CNXPinX::SetKeyName(const VARIANT& propVal)
{
	SetProperty(0x46, VT_VARIANT, &propVal);
}

VARIANT CNXPinX::GetKeyUse()
{
	VARIANT result;
	GetProperty(0x47, VT_VARIANT, (void*)&result);
	return result;
}

void CNXPinX::SetKeyUse(const VARIANT& propVal)
{
	SetProperty(0x47, VT_VARIANT, &propVal);
}

VARIANT CNXPinX::GetKeyLoaded()
{
	VARIANT result;
	GetProperty(0x48, VT_VARIANT, (void*)&result);
	return result;
}

void CNXPinX::SetKeyLoaded(const VARIANT& propVal)
{
	SetProperty(0x48, VT_VARIANT, &propVal);
}

VARIANT CNXPinX::GetKeyGeneration()
{
	VARIANT result;
	GetProperty(0x49, VT_VARIANT, (void*)&result);
	return result;
}

void CNXPinX::SetKeyGeneration(const VARIANT& propVal)
{
	SetProperty(0x49, VT_VARIANT, &propVal);
}

VARIANT CNXPinX::GetKeyVersion()
{
	VARIANT result;
	GetProperty(0x4a, VT_VARIANT, (void*)&result);
	return result;
}

void CNXPinX::SetKeyVersion(const VARIANT& propVal)
{
	SetProperty(0x4a, VT_VARIANT, &propVal);
}

VARIANT CNXPinX::GetKeyActivatingDate()
{
	VARIANT result;
	GetProperty(0x4b, VT_VARIANT, (void*)&result);
	return result;
}

void CNXPinX::SetKeyActivatingDate(const VARIANT& propVal)
{
	SetProperty(0x4b, VT_VARIANT, &propVal);
}

VARIANT CNXPinX::GetKeyExpiryDate()
{
	VARIANT result;
	GetProperty(0x4c, VT_VARIANT, (void*)&result);
	return result;
}

void CNXPinX::SetKeyExpiryDate(const VARIANT& propVal)
{
	SetProperty(0x4c, VT_VARIANT, &propVal);
}

long CNXPinX::GetKeyCount()
{
	long result;
	GetProperty(0x4d, VT_I4, (void*)&result);
	return result;
}

void CNXPinX::SetKeyCount(long propVal)
{
	SetProperty(0x4d, VT_I4, propVal);
}

CString CNXPinX::GetSecureKeyEntryMode()
{
	CString result;
	GetProperty(0x50, VT_BSTR, (void*)&result);
	return result;
}

void CNXPinX::SetSecureKeyEntryMode(LPCTSTR propVal)
{
	SetProperty(0x50, VT_BSTR, propVal);
}

CString CNXPinX::GetSecureKeys()
{
	CString result;
	GetProperty(0x51, VT_BSTR, (void*)&result);
	return result;
}

void CNXPinX::SetSecureKeys(LPCTSTR propVal)
{
	SetProperty(0x51, VT_BSTR, propVal);
}

CString CNXPinX::GetSecureKeyClearFDK()
{
	CString result;
	GetProperty(0x52, VT_BSTR, (void*)&result);
	return result;
}

void CNXPinX::SetSecureKeyClearFDK(LPCTSTR propVal)
{
	SetProperty(0x52, VT_BSTR, propVal);
}

CString CNXPinX::GetSecureKeyCancelFDK()
{
	CString result;
	GetProperty(0x53, VT_BSTR, (void*)&result);
	return result;
}

void CNXPinX::SetSecureKeyCancelFDK(LPCTSTR propVal)
{
	SetProperty(0x53, VT_BSTR, propVal);
}

CString CNXPinX::GetSecureKeyBackspaceFDK()
{
	CString result;
	GetProperty(0x54, VT_BSTR, (void*)&result);
	return result;
}

void CNXPinX::SetSecureKeyBackspaceFDK(LPCTSTR propVal)
{
	SetProperty(0x54, VT_BSTR, propVal);
}

CString CNXPinX::GetSecureKeyEnterFDK()
{
	CString result;
	GetProperty(0x55, VT_BSTR, (void*)&result);
	return result;
}

void CNXPinX::SetSecureKeyEnterFDK(LPCTSTR propVal)
{
	SetProperty(0x55, VT_BSTR, propVal);
}

short CNXPinX::GetSecureKeyNumberOfCols()
{
	short result;
	GetProperty(0x56, VT_I2, (void*)&result);
	return result;
}

void CNXPinX::SetSecureKeyNumberOfCols(short propVal)
{
	SetProperty(0x56, VT_I2, propVal);
}

short CNXPinX::GetSecureKeyNumberOfRows()
{
	short result;
	GetProperty(0x57, VT_I2, (void*)&result);
	return result;
}

void CNXPinX::SetSecureKeyNumberOfRows(short propVal)
{
	SetProperty(0x57, VT_I2, propVal);
}

long CNXPinX::GetNumberOfSecureHexKey()
{
	long result;
	GetProperty(0x58, VT_I4, (void*)&result);
	return result;
}

void CNXPinX::SetNumberOfSecureHexKey(long propVal)
{
	SetProperty(0x58, VT_I4, propVal);
}

VARIANT CNXPinX::GetSecureHexKeyXPos()
{
	VARIANT result;
	GetProperty(0x59, VT_VARIANT, (void*)&result);
	return result;
}

void CNXPinX::SetSecureHexKeyXPos(const VARIANT& propVal)
{
	SetProperty(0x59, VT_VARIANT, &propVal);
}

VARIANT CNXPinX::GetSecureHexKeyYPos()
{
	VARIANT result;
	GetProperty(0x5a, VT_VARIANT, (void*)&result);
	return result;
}

void CNXPinX::SetSecureHexKeyYPos(const VARIANT& propVal)
{
	SetProperty(0x5a, VT_VARIANT, &propVal);
}

VARIANT CNXPinX::GetSecureHexKeyXSize()
{
	VARIANT result;
	GetProperty(0x5b, VT_VARIANT, (void*)&result);
	return result;
}

void CNXPinX::SetSecureHexKeyXSize(const VARIANT& propVal)
{
	SetProperty(0x5b, VT_VARIANT, &propVal);
}

VARIANT CNXPinX::GetSecureHexKeyYSize()
{
	VARIANT result;
	GetProperty(0x5c, VT_VARIANT, (void*)&result);
	return result;
}

void CNXPinX::SetSecureHexKeyYSize(const VARIANT& propVal)
{
	SetProperty(0x5c, VT_VARIANT, &propVal);
}

VARIANT CNXPinX::GetSecureHexKeyFK()
{
	VARIANT result;
	GetProperty(0x5d, VT_VARIANT, (void*)&result);
	return result;
}

void CNXPinX::SetSecureHexKeyFK(const VARIANT& propVal)
{
	SetProperty(0x5d, VT_VARIANT, &propVal);
}

VARIANT CNXPinX::GetSecureHexKeyShiftFK()
{
	VARIANT result;
	GetProperty(0x5e, VT_VARIANT, (void*)&result);
	return result;
}

void CNXPinX::SetSecureHexKeyShiftFK(const VARIANT& propVal)
{
	SetProperty(0x5e, VT_VARIANT, &propVal);
}

// [#RWC6-151] US Kook 2020.07.14 TR34
CString CNXPinX::GetCertificateState()
{
	CString result;
	GetProperty(0x64, VT_BSTR, (void*)&result);
	return result;
}

CString CNXPinX::GetRSAKeyCheckMode()
{
	CString result;
	GetProperty(0x65, VT_BSTR, (void*)&result);
	return result;
}

CString CNXPinX::GetAuthenticateSigner()
{
	CString result;
	GetProperty(0x66, VT_BSTR, (void*)&result);
	return result;
}
void CNXPinX::SetAuthenticateSigner(LPCTSTR propVal)
{
	SetProperty(0x66, VT_BSTR, propVal);
}

CString CNXPinX::GetAuthenticateDataToSign()
{
	CString result;
	GetProperty(0x67, VT_BSTR, (void*)&result);
	return result;
}

CString CNXPinX::GetAuthenticateSigKey()
{
	CString result;
	GetProperty(0x68, VT_BSTR, (void*)&result);
	return result;
}
void CNXPinX::SetAuthenticateSigKey(LPCTSTR propVal)
{
	SetProperty(0x68, VT_BSTR, propVal);
}

CString CNXPinX::GetAuthenticateSignedData()
{
	CString result;
	GetProperty(0x69, VT_BSTR, (void*)&result);
	return result;
}
void CNXPinX::SetAuthenticateSignedData(LPCTSTR propVal)
{
	SetProperty(0x69, VT_BSTR, propVal);
}


/////////////////////////////////////////////////////////////////////////////
// CNXPinX operations

long CNXPinX::OpenSessionSync(long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x15, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Timeout);
	return result;
}

long CNXPinX::CloseSessionSync()
{
	long result;
	InvokeHelper(0x16, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXPinX::RequestLock(long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x17, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Timeout);
	return result;
}

long CNXPinX::ReleaseLock()
{
	long result;
	InvokeHelper(0x18, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXPinX::Reset()
{
	long result;
	InvokeHelper(0x19, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

CString CNXPinX::GetExtraStatus(LPCTSTR KeyName)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x1a, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		KeyName);
	return result;
}

CString CNXPinX::GetExtraCaps(LPCTSTR KeyName)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x1b, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		KeyName);
	return result;
}

long CNXPinX::EncryptECB(LPCTSTR Algorithm, LPCTSTR Key, LPCTSTR KeyEncKey, short Padchar, LPCTSTR CryptData)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR VTS_I2 VTS_BSTR;
	InvokeHelper(0x1c, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Algorithm, Key, KeyEncKey, Padchar, CryptData);
	return result;
}

long CNXPinX::DecryptECB(LPCTSTR Algorithm, LPCTSTR Key, LPCTSTR KeyEncKey, short Padchar, LPCTSTR CryptData)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR VTS_I2 VTS_BSTR;
	InvokeHelper(0x1d, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Algorithm, Key, KeyEncKey, Padchar, CryptData);
	return result;
}

long CNXPinX::EncryptCBC(LPCTSTR Algorithm, LPCTSTR Key, LPCTSTR KeyEncKey, LPCTSTR StartValueKey, LPCTSTR StartValue, short Padchar, LPCTSTR CryptData)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR VTS_I2 VTS_BSTR;
	InvokeHelper(0x1e, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Algorithm, Key, KeyEncKey, StartValueKey, StartValue, Padchar, CryptData);
	return result;
}

long CNXPinX::DecryptCBC(LPCTSTR Algorithm, LPCTSTR Key, LPCTSTR KeyEncKey, LPCTSTR StartValueKey, LPCTSTR StartValue, short Padchar, LPCTSTR CryptData)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR VTS_I2 VTS_BSTR;
	InvokeHelper(0x1f, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Algorithm, Key, KeyEncKey, StartValueKey, StartValue, Padchar, CryptData);
	return result;
}

long CNXPinX::GenerateMAC(LPCTSTR Algorithm, LPCTSTR Key, LPCTSTR KeyEncKey, LPCTSTR StartValueKey, LPCTSTR StartValue, short Padchar, LPCTSTR CryptData)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR VTS_I2 VTS_BSTR;
	InvokeHelper(0x20, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Algorithm, Key, KeyEncKey, StartValueKey, StartValue, Padchar, CryptData);
	return result;
}

long CNXPinX::ImportKey(LPCTSTR Key, LPCTSTR KeyEncKey, LPCTSTR Value, LPCTSTR Use)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x21, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Key, KeyEncKey, Value, Use);
	return result;
}

long CNXPinX::ReadPin(short MinLen, short MaxLen, long AutoEnd, LPCTSTR ActiveKeys, LPCTSTR TerminateKeys, long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_I4 VTS_BSTR VTS_BSTR VTS_I4;
	InvokeHelper(0x22, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		MinLen, MaxLen, AutoEnd, ActiveKeys, TerminateKeys, Timeout);
	return result;
}

long CNXPinX::CancelReadPin()
{
	long result;
	InvokeHelper(0x23, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXPinX::BuildPinBlock(LPCTSTR CustomerData, LPCTSTR XORData, short Padchar, LPCTSTR Format, LPCTSTR Key, LPCTSTR KeyEncKey)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_I2 VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x24, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		CustomerData, XORData, Padchar, Format, Key, KeyEncKey);
	return result;
}

long CNXPinX::ReadData(short MaxLen, long AutoEnd, LPCTSTR ActiveKeys, LPCTSTR TerminateKeys, long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_I2 VTS_I4 VTS_BSTR VTS_BSTR VTS_I4;
	InvokeHelper(0x25, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		MaxLen, AutoEnd, ActiveKeys, TerminateKeys, Timeout);
	return result;
}

long CNXPinX::CancelReadData()
{
	long result;
	InvokeHelper(0x26, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXPinX::InitializeEDM()
{
	long result;
	InvokeHelper(0x27, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXPinX::GenerateRandomNumber()
{
	long result;
	InvokeHelper(0x28, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXPinX::VerifyLocalDES(LPCTSTR ValidationData, LPCTSTR Offset, short Padchar, short MaxPIN, short NumOfValDigits, long NoLeadingZero, LPCTSTR Key, LPCTSTR KeyEncKey, LPCTSTR DecTable)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_I2 VTS_I2 VTS_I2 VTS_I4 VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x29, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		ValidationData, Offset, Padchar, MaxPIN, NumOfValDigits, NoLeadingZero, Key, KeyEncKey, DecTable);
	return result;
}

CString CNXPinX::ImportedKey()
{
	CString result;
	InvokeHelper(0x2a, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

long CNXPinX::GenerateKCV(LPCTSTR Key, LPCTSTR KeyCheckMode)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x2b, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Key, KeyCheckMode);
	return result;
}

long CNXPinX::GetKeyDetail(LPCTSTR KeyName, long Extended)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4;
	InvokeHelper(0x2c, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		KeyName, Extended);
	return result;
}

long CNXPinX::StartKeyExchange()
{
	long result;
	InvokeHelper(0x2d, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXPinX::ImportRSAPublicKey(LPCTSTR Key, LPCTSTR Value, LPCTSTR Use, LPCTSTR SignatureKey, LPCTSTR RSASignatureAlgorithm, LPCTSTR Signature)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x2e, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Key, Value, Use, SignatureKey, RSASignatureAlgorithm, Signature);
	return result;
}

long CNXPinX::ExportRSAIssuerSignedItem(LPCTSTR ExportItemType, LPCTSTR KeyName)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x2f, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		ExportItemType, KeyName);
	return result;
}

long CNXPinX::ImportRSASignedDESKey(LPCTSTR Key, LPCTSTR DecryptKey, LPCTSTR RSAEncipherAlgorithm, LPCTSTR Value, LPCTSTR Use, LPCTSTR SignatureKey, LPCTSTR RSASignatureAlgorithm, LPCTSTR Signature)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x30, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Key, DecryptKey, RSAEncipherAlgorithm, Value, Use, SignatureKey, RSASignatureAlgorithm, Signature);
	return result;
}

long CNXPinX::ExportRSAEPPSignedItem(LPCTSTR ExportItemType, LPCTSTR Key, LPCTSTR SignatureKey, LPCTSTR SignatureAlgorithm)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x31, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		ExportItemType, Key, SignatureKey, SignatureAlgorithm);
	return result;
}

long CNXPinX::GenerateRSAKeyPair(LPCTSTR Key, LPCTSTR Use, short ModulusLength, LPCTSTR ExponentValue)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_I2 VTS_BSTR;
	InvokeHelper(0x32, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Key, Use, ModulusLength, ExponentValue);
	return result;
}

long CNXPinX::LoadCertificate(LPCTSTR Certificate)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x33, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Certificate);
	return result;
}

long CNXPinX::GetCertificate(LPCTSTR Certificate)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x34, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Certificate);
	return result;
}

long CNXPinX::ReplaceCertificate(LPCTSTR Certificate)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x35, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Certificate);
	return result;
}

long CNXPinX::ImportRSAEncipheredPKCS7Key(LPCTSTR RSAKeyIn, LPCTSTR Key, LPCTSTR Use)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x36, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		RSAKeyIn, Key, Use);
	return result;
}

BOOL CNXPinX::GetSupportedAlgorithm(LPCTSTR Algorithm)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x37, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, parms,
		Algorithm);
	return result;
}

BOOL CNXPinX::GetSupportedPinFormat(LPCTSTR PinFormat)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x38, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, parms,
		PinFormat);
	return result;
}

BOOL CNXPinX::GetSupportedValidationAlgorithm(LPCTSTR ValidationAlgorithm)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x39, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, parms,
		ValidationAlgorithm);
	return result;
}

BOOL CNXPinX::GetSupportedRemoteKeyScheme(LPCTSTR Scheme)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x3a, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, parms,
		Scheme);
	return result;
}

BOOL CNXPinX::GetSupportedRSASignAlgorithm(LPCTSTR Algorithm)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x3b, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, parms,
		Algorithm);
	return result;
}

BOOL CNXPinX::GetSupportedRSACryptAlgorithm(LPCTSTR Algorithm)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x3c, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, parms,
		Algorithm);
	return result;
}

BOOL CNXPinX::GetSupportedRSAKeyCheckMode(LPCTSTR Mode)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x3d, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, parms,
		Mode);
	return result;
}

BOOL CNXPinX::GetSupportedSignatureScheme(LPCTSTR Scheme)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x3e, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, parms,
		Scheme);
	return result;
}

BOOL CNXPinX::GetSupportedEMVImportScheme(LPCTSTR Scheme)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x3f, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, parms,
		Scheme);
	return result;
}

BOOL CNXPinX::GetSupportedEMVHash(LPCTSTR Algorithm)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x40, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, parms,
		Algorithm);
	return result;
}

BOOL CNXPinX::GetSupportedENCIOProtocol(LPCTSTR Protocol)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x41, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, parms,
		Protocol);
	return result;
}

BOOL CNXPinX::GetSupportedKeyCheckMode(LPCTSTR Mode)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x42, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, parms,
		Mode);
	return result;
}

long CNXPinX::SecureKeyEntry(short KeyLen, long AutoEnd, LPCTSTR ActiveKeys, LPCTSTR TerminateKeys, LPCTSTR VerificationType, long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_I2 VTS_I4 VTS_BSTR VTS_BSTR VTS_BSTR VTS_I4;
	InvokeHelper(0x4e, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		KeyLen, AutoEnd, ActiveKeys, TerminateKeys, VerificationType, Timeout);
	return result;
}

long CNXPinX::CancelSecureKeyEntry()
{
	long result;
	InvokeHelper(0x4f, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

// [#RWC6-151] US Kook 2020.07.14 TR34
long CNXPinX::InitializeEDMEx(LPCTSTR Indent, LPCTSTR Key)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x5f, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Indent, Key);
	return result;
}

long CNXPinX::ImportKeyBlock(LPCTSTR Key, LPCTSTR EncKey, LPCTSTR KeyBlock)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x60, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Key, EncKey, KeyBlock);
	return result;
}

long CNXPinX::LoadCertificateEx(LPCTSTR LoadOption, LPCTSTR Signer, LPCTSTR CertificateData)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x61, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		LoadOption, Signer, CertificateData);
	return result;
}

long CNXPinX::ImportRSAEncipheredPKCS7KeyEx(LPCTSTR RSAKeyIn, LPCTSTR Key, LPCTSTR Use, LPCTSTR LoadOption)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x62, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		RSAKeyIn, Key, Use, LoadOption);
	return result;
}

long CNXPinX::StartAuthenticateSync(LPCTSTR MethodName, LPCTSTR Parameters)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x63, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		MethodName, Parameters);
	return result;
}


void CNXPinX::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
