#if !defined(AFX_NXPINX_H__DBCBDF5D_7CF7_4206_A2EF_B1F18D0C462F__INCLUDED_)
#define AFX_NXPINX_H__DBCBDF5D_7CF7_4206_A2EF_B1F18D0C462F__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CNXPinX wrapper class

class CNXPinX : public CWnd
{
protected:
	DECLARE_DYNCREATE(CNXPinX)
public:
	CLSID const& GetClsid()
	{
#ifdef UNDER_CE
		static CLSID const clsid
			= { 0xd535acaf, 0x9a4a, 0x42d1, { 0xaa, 0x43, 0x4a, 0x25, 0x16, 0x66, 0x42, 0xfd } };
#else
		static CLSID const clsid
			= { 0x0b5f96bf, 0x2019, 0x478c, { 0x9f, 0xa3, 0x3b, 0x34, 0x22, 0x9d, 0x39, 0x4f} };
#endif
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	CString GetDeviceStatus();
	void SetDeviceStatus(LPCTSTR);
	long GetNumberOfFDKs();
	void SetNumberOfFDKs(long);
	CString GetFunctionKeys();
	void SetFunctionKeys(LPCTSTR);
	CString GetEncStatus();
	void SetEncStatus(LPCTSTR);
	BOOL GetCanDESECB();
	void SetCanDESECB(BOOL);
	BOOL GetCanDESCBC();
	void SetCanDESCBC(BOOL);
	BOOL GetCanDESMAC();
	void SetCanDESMAC(BOOL);
	BOOL GetCan3624();
	void SetCan3624(BOOL);
	BOOL GetCanANSI();
	void SetCanANSI(BOOL);
	BOOL GetCanISO0();
	void SetCanISO0(BOOL);
	BOOL GetCanISO1();
	void SetCanISO1(BOOL);
	BOOL GetCanECI2();
	void SetCanECI2(BOOL);
	BOOL GetCanECI3();
	void SetCanECI3(BOOL);
	BOOL GetCanDIEBOLD();
	void SetCanDIEBOLD(BOOL);
	BOOL GetCanDIEBOLDCO();
	void SetCanDIEBOLDCO(BOOL);
	BOOL GetCanVISA3();
	void SetCanVISA3(BOOL);
	BOOL GetCanBANKSYS();
	void SetCanBANKSYS(BOOL);
	BOOL GetCanTRIDESECB();
	void SetCanTRIDESECB(BOOL);
	BOOL GetCanTRIDESCBC();
	void SetCanTRIDESCBC(BOOL);
	BOOL GetCanTRIDESMAC();
	void SetCanTRIDESMAC(BOOL);
	CString GetDeviceType();
	void SetDeviceType(LPCTSTR);
	BOOL GetSupportedJournaling();
	void SetSupportedJournaling(BOOL);
	BOOL GetSupportedMultiPartKeyImport();
	void SetSupportedMultiPartKeyImport(BOOL);
	VARIANT GetKeyName();
	void SetKeyName(const VARIANT&);
	VARIANT GetKeyUse();
	void SetKeyUse(const VARIANT&);
	VARIANT GetKeyLoaded();
	void SetKeyLoaded(const VARIANT&);
	VARIANT GetKeyGeneration();
	void SetKeyGeneration(const VARIANT&);
	VARIANT GetKeyVersion();
	void SetKeyVersion(const VARIANT&);
	VARIANT GetKeyActivatingDate();
	void SetKeyActivatingDate(const VARIANT&);
	VARIANT GetKeyExpiryDate();
	void SetKeyExpiryDate(const VARIANT&);
	long GetKeyCount();
	void SetKeyCount(long);
	CString GetSecureKeyEntryMode();
	void SetSecureKeyEntryMode(LPCTSTR);
	CString GetSecureKeys();
	void SetSecureKeys(LPCTSTR);
	CString GetSecureKeyClearFDK();
	void SetSecureKeyClearFDK(LPCTSTR);
	CString GetSecureKeyCancelFDK();
	void SetSecureKeyCancelFDK(LPCTSTR);
	CString GetSecureKeyBackspaceFDK();
	void SetSecureKeyBackspaceFDK(LPCTSTR);
	CString GetSecureKeyEnterFDK();
	void SetSecureKeyEnterFDK(LPCTSTR);
	short GetSecureKeyNumberOfCols();
	void SetSecureKeyNumberOfCols(short);
	short GetSecureKeyNumberOfRows();
	void SetSecureKeyNumberOfRows(short);
	long GetNumberOfSecureHexKey();
	void SetNumberOfSecureHexKey(long);
	VARIANT GetSecureHexKeyXPos();
	void SetSecureHexKeyXPos(const VARIANT&);
	VARIANT GetSecureHexKeyYPos();
	void SetSecureHexKeyYPos(const VARIANT&);
	VARIANT GetSecureHexKeyXSize();
	void SetSecureHexKeyXSize(const VARIANT&);
	VARIANT GetSecureHexKeyYSize();
	void SetSecureHexKeyYSize(const VARIANT&);
	VARIANT GetSecureHexKeyFK();
	void SetSecureHexKeyFK(const VARIANT&);
	VARIANT GetSecureHexKeyShiftFK();
	void SetSecureHexKeyShiftFK(const VARIANT&);

	// [#RWC6-151] US Kook 2020.07.14 TR34
	CString GetCertificateState();				// read only
	CString GetRSAKeyCheckMode();				// read only
	CString GetAuthenticateSigner();
	void SetAuthenticateSigner(LPCTSTR);
	CString GetAuthenticateDataToSign();		// read only
	CString GetAuthenticateSigKey();
	void SetAuthenticateSigKey(LPCTSTR);
	CString GetAuthenticateSignedData();
	void SetAuthenticateSignedData(LPCTSTR);


// Operations
public:
	long OpenSessionSync(long Timeout);
	long CloseSessionSync();
	long RequestLock(long Timeout);
	long ReleaseLock();
	long Reset();
	CString GetExtraStatus(LPCTSTR KeyName);
	CString GetExtraCaps(LPCTSTR KeyName);
	long EncryptECB(LPCTSTR Algorithm, LPCTSTR Key, LPCTSTR KeyEncKey, short Padchar, LPCTSTR CryptData);
	long DecryptECB(LPCTSTR Algorithm, LPCTSTR Key, LPCTSTR KeyEncKey, short Padchar, LPCTSTR CryptData);
	long EncryptCBC(LPCTSTR Algorithm, LPCTSTR Key, LPCTSTR KeyEncKey, LPCTSTR StartValueKey, LPCTSTR StartValue, short Padchar, LPCTSTR CryptData);
	long DecryptCBC(LPCTSTR Algorithm, LPCTSTR Key, LPCTSTR KeyEncKey, LPCTSTR StartValueKey, LPCTSTR StartValue, short Padchar, LPCTSTR CryptData);
	long GenerateMAC(LPCTSTR Algorithm, LPCTSTR Key, LPCTSTR KeyEncKey, LPCTSTR StartValueKey, LPCTSTR StartValue, short Padchar, LPCTSTR CryptData);
	long ImportKey(LPCTSTR Key, LPCTSTR KeyEncKey, LPCTSTR Value, LPCTSTR Use);
	long ReadPin(short MinLen, short MaxLen, long AutoEnd, LPCTSTR ActiveKeys, LPCTSTR TerminateKeys, long Timeout);
	long CancelReadPin();
	long BuildPinBlock(LPCTSTR CustomerData, LPCTSTR XORData, short Padchar, LPCTSTR Format, LPCTSTR Key, LPCTSTR KeyEncKey);
	long ReadData(short MaxLen, long AutoEnd, LPCTSTR ActiveKeys, LPCTSTR TerminateKeys, long Timeout);
	long CancelReadData();
	long InitializeEDM();
	long GenerateRandomNumber();
	long VerifyLocalDES(LPCTSTR ValidationData, LPCTSTR Offset, short Padchar, short MaxPIN, short NumOfValDigits, long NoLeadingZero, LPCTSTR Key, LPCTSTR KeyEncKey, LPCTSTR DecTable);
	CString ImportedKey();
	long GenerateKCV(LPCTSTR Key, LPCTSTR KeyCheckMode);
	long GetKeyDetail(LPCTSTR KeyName, long Extended);
	long StartKeyExchange();
	long ImportRSAPublicKey(LPCTSTR Key, LPCTSTR Value, LPCTSTR Use, LPCTSTR SignatureKey, LPCTSTR RSASignatureAlgorithm, LPCTSTR Signature);
	long ExportRSAIssuerSignedItem(LPCTSTR ExportItemType, LPCTSTR KeyName);
	long ImportRSASignedDESKey(LPCTSTR Key, LPCTSTR DecryptKey, LPCTSTR RSAEncipherAlgorithm, LPCTSTR Value, LPCTSTR Use, LPCTSTR SignatureKey, LPCTSTR RSASignatureAlgorithm, LPCTSTR Signature);
	long ExportRSAEPPSignedItem(LPCTSTR ExportItemType, LPCTSTR Key, LPCTSTR SignatureKey, LPCTSTR SignatureAlgorithm);
	long GenerateRSAKeyPair(LPCTSTR Key, LPCTSTR Use, short ModulusLength, LPCTSTR ExponentValue);
	long LoadCertificate(LPCTSTR Certificate);
	long GetCertificate(LPCTSTR Certificate);
	long ReplaceCertificate(LPCTSTR Certificate);
	long ImportRSAEncipheredPKCS7Key(LPCTSTR RSAKeyIn, LPCTSTR Key, LPCTSTR Use);
	BOOL GetSupportedAlgorithm(LPCTSTR Algorithm);
	BOOL GetSupportedPinFormat(LPCTSTR PinFormat);
	BOOL GetSupportedValidationAlgorithm(LPCTSTR ValidationAlgorithm);
	BOOL GetSupportedRemoteKeyScheme(LPCTSTR Scheme);
	BOOL GetSupportedRSASignAlgorithm(LPCTSTR Algorithm);
	BOOL GetSupportedRSACryptAlgorithm(LPCTSTR Algorithm);
	BOOL GetSupportedRSAKeyCheckMode(LPCTSTR Mode);
	BOOL GetSupportedSignatureScheme(LPCTSTR Scheme);
	BOOL GetSupportedEMVImportScheme(LPCTSTR Scheme);
	BOOL GetSupportedEMVHash(LPCTSTR Algorithm);
	BOOL GetSupportedENCIOProtocol(LPCTSTR Protocol);
	BOOL GetSupportedKeyCheckMode(LPCTSTR Mode);
	long SecureKeyEntry(short KeyLen, long AutoEnd, LPCTSTR ActiveKeys, LPCTSTR TerminateKeys, LPCTSTR VerificationType, long Timeout);
	long CancelSecureKeyEntry();

	// [#RWC6-151] US Kook 2020.07.14 TR34
	long InitializeEDMEx(LPCTSTR Indent, LPCTSTR Key);
	long ImportKeyBlock(LPCTSTR Key, LPCTSTR EncKey, LPCTSTR KeyBlock);
	long LoadCertificateEx(LPCTSTR LoadOption, LPCTSTR Signer, LPCTSTR CertificateData);
	long ImportRSAEncipheredPKCS7KeyEx(LPCTSTR RSAKeyIn, LPCTSTR Key, LPCTSTR Use, LPCTSTR LoadOption);
	long StartAuthenticateSync(LPCTSTR MethodName, LPCTSTR Parameters);

	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_NXPINX_H__DBCBDF5D_7CF7_4206_A2EF_B1F18D0C462F__INCLUDED_)
