// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "nxreceiptprinterx.h"

/////////////////////////////////////////////////////////////////////////////
// CNXReceiptPrinterX

IMPLEMENT_DYNCREATE(CNXReceiptPrinterX, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CNXReceiptPrinterX properties

CString CNXReceiptPrinterX::GetDeviceStatus()
{
	CString result;
	GetProperty(0x1, VT_BSTR, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetDeviceStatus(LPCTSTR propVal)
{
	SetProperty(0x1, VT_BSTR, propVal);
}

CString CNXReceiptPrinterX::GetMediaStatus()
{
	CString result;
	GetProperty(0x2, VT_BSTR, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetMediaStatus(LPCTSTR propVal)
{
	SetProperty(0x2, VT_BSTR, propVal);
}

CString CNXReceiptPrinterX::GetTonerStatus()
{
	CString result;
	GetProperty(0x3, VT_BSTR, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetTonerStatus(LPCTSTR propVal)
{
	SetProperty(0x3, VT_BSTR, propVal);
}

CString CNXReceiptPrinterX::GetInkStatus()
{
	CString result;
	GetProperty(0x4, VT_BSTR, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetInkStatus(LPCTSTR propVal)
{
	SetProperty(0x4, VT_BSTR, propVal);
}

CString CNXReceiptPrinterX::GetLampStatus()
{
	CString result;
	GetProperty(0x5, VT_BSTR, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetLampStatus(LPCTSTR propVal)
{
	SetProperty(0x5, VT_BSTR, propVal);
}

short CNXReceiptPrinterX::GetMediaOnStackerCount()
{
	short result;
	GetProperty(0x6, VT_I2, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetMediaOnStackerCount(short propVal)
{
	SetProperty(0x6, VT_I2, propVal);
}

VARIANT CNXReceiptPrinterX::GetResolution()
{
	VARIANT result;
	GetProperty(0x7, VT_VARIANT, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetResolution(const VARIANT& propVal)
{
	SetProperty(0x7, VT_VARIANT, &propVal);
}

VARIANT CNXReceiptPrinterX::GetReadTypes()
{
	VARIANT result;
	GetProperty(0x8, VT_VARIANT, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetReadTypes(const VARIANT& propVal)
{
	SetProperty(0x8, VT_VARIANT, &propVal);
}

VARIANT CNXReceiptPrinterX::GetWriteTypes()
{
	VARIANT result;
	GetProperty(0x9, VT_VARIANT, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetWriteTypes(const VARIANT& propVal)
{
	SetProperty(0x9, VT_VARIANT, &propVal);
}

VARIANT CNXReceiptPrinterX::GetControlMediaActions()
{
	VARIANT result;
	GetProperty(0xa, VT_VARIANT, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetControlMediaActions(const VARIANT& propVal)
{
	SetProperty(0xa, VT_VARIANT, &propVal);
}

short CNXReceiptPrinterX::GetMaxMediaOnStacker()
{
	short result;
	GetProperty(0xb, VT_I2, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetMaxMediaOnStacker(short propVal)
{
	SetProperty(0xb, VT_I2, propVal);
}

VARIANT CNXReceiptPrinterX::GetFormList()
{
	VARIANT result;
	GetProperty(0xc, VT_VARIANT, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetFormList(const VARIANT& propVal)
{
	SetProperty(0xc, VT_VARIANT, &propVal);
}

CString CNXReceiptPrinterX::GetFormName()
{
	CString result;
	GetProperty(0xd, VT_BSTR, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetFormName(LPCTSTR propVal)
{
	SetProperty(0xd, VT_BSTR, propVal);
}

CString CNXReceiptPrinterX::GetFormAlignment()
{
	CString result;
	GetProperty(0xe, VT_BSTR, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetFormAlignment(LPCTSTR propVal)
{
	SetProperty(0xe, VT_BSTR, propVal);
}

long CNXReceiptPrinterX::GetFormUnitX()
{
	long result;
	GetProperty(0xf, VT_I4, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetFormUnitX(long propVal)
{
	SetProperty(0xf, VT_I4, propVal);
}

long CNXReceiptPrinterX::GetFormUnitY()
{
	long result;
	GetProperty(0x10, VT_I4, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetFormUnitY(long propVal)
{
	SetProperty(0x10, VT_I4, propVal);
}

long CNXReceiptPrinterX::GetFormWidth()
{
	long result;
	GetProperty(0x11, VT_I4, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetFormWidth(long propVal)
{
	SetProperty(0x11, VT_I4, propVal);
}

long CNXReceiptPrinterX::GetFormHeight()
{
	long result;
	GetProperty(0x12, VT_I4, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetFormHeight(long propVal)
{
	SetProperty(0x12, VT_I4, propVal);
}

CString CNXReceiptPrinterX::GetFormBase()
{
	CString result;
	GetProperty(0x13, VT_BSTR, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetFormBase(LPCTSTR propVal)
{
	SetProperty(0x13, VT_BSTR, propVal);
}

CString CNXReceiptPrinterX::GetFormOrientation()
{
	CString result;
	GetProperty(0x14, VT_BSTR, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetFormOrientation(LPCTSTR propVal)
{
	SetProperty(0x14, VT_BSTR, propVal);
}

long CNXReceiptPrinterX::GetFormOffsetX()
{
	long result;
	GetProperty(0x15, VT_I4, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetFormOffsetX(long propVal)
{
	SetProperty(0x15, VT_I4, propVal);
}

long CNXReceiptPrinterX::GetFormOffsetY()
{
	long result;
	GetProperty(0x16, VT_I4, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetFormOffsetY(long propVal)
{
	SetProperty(0x16, VT_I4, propVal);
}

long CNXReceiptPrinterX::GetFormVersionMajor()
{
	long result;
	GetProperty(0x17, VT_I4, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetFormVersionMajor(long propVal)
{
	SetProperty(0x17, VT_I4, propVal);
}

long CNXReceiptPrinterX::GetFormVersionMinor()
{
	long result;
	GetProperty(0x18, VT_I4, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetFormVersionMinor(long propVal)
{
	SetProperty(0x18, VT_I4, propVal);
}

CString CNXReceiptPrinterX::GetFormUserPrompt()
{
	CString result;
	GetProperty(0x19, VT_BSTR, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetFormUserPrompt(LPCTSTR propVal)
{
	SetProperty(0x19, VT_BSTR, propVal);
}

VARIANT CNXReceiptPrinterX::GetFormFieldList()
{
	VARIANT result;
	GetProperty(0x1a, VT_VARIANT, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetFormFieldList(const VARIANT& propVal)
{
	SetProperty(0x1a, VT_VARIANT, &propVal);
}

CString CNXReceiptPrinterX::GetFormFieldName()
{
	CString result;
	GetProperty(0x1b, VT_BSTR, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetFormFieldName(LPCTSTR propVal)
{
	SetProperty(0x1b, VT_BSTR, propVal);
}

CString CNXReceiptPrinterX::GetFormFieldType()
{
	CString result;
	GetProperty(0x1c, VT_BSTR, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetFormFieldType(LPCTSTR propVal)
{
	SetProperty(0x1c, VT_BSTR, propVal);
}

CString CNXReceiptPrinterX::GetFormFieldClass()
{
	CString result;
	GetProperty(0x1d, VT_BSTR, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetFormFieldClass(LPCTSTR propVal)
{
	SetProperty(0x1d, VT_BSTR, propVal);
}

CString CNXReceiptPrinterX::GetFormFieldAccess()
{
	CString result;
	GetProperty(0x1e, VT_BSTR, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetFormFieldAccess(LPCTSTR propVal)
{
	SetProperty(0x1e, VT_BSTR, propVal);
}

CString CNXReceiptPrinterX::GetFormFieldInitialValue()
{
	CString result;
	GetProperty(0x1f, VT_BSTR, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetFormFieldInitialValue(LPCTSTR propVal)
{
	SetProperty(0x1f, VT_BSTR, propVal);
}

CString CNXReceiptPrinterX::GetFormFieldFormat()
{
	CString result;
	GetProperty(0x20, VT_BSTR, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetFormFieldFormat(LPCTSTR propVal)
{
	SetProperty(0x20, VT_BSTR, propVal);
}

VARIANT CNXReceiptPrinterX::GetMediaList()
{
	VARIANT result;
	GetProperty(0x21, VT_VARIANT, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetMediaList(const VARIANT& propVal)
{
	SetProperty(0x21, VT_VARIANT, &propVal);
}

CString CNXReceiptPrinterX::GetMediaName()
{
	CString result;
	GetProperty(0x22, VT_BSTR, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetMediaName(LPCTSTR propVal)
{
	SetProperty(0x22, VT_BSTR, propVal);
}

CString CNXReceiptPrinterX::GetMediaType()
{
	CString result;
	GetProperty(0x23, VT_BSTR, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetMediaType(LPCTSTR propVal)
{
	SetProperty(0x23, VT_BSTR, propVal);
}

CString CNXReceiptPrinterX::GetMediaBase()
{
	CString result;
	GetProperty(0x24, VT_BSTR, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetMediaBase(LPCTSTR propVal)
{
	SetProperty(0x24, VT_BSTR, propVal);
}

long CNXReceiptPrinterX::GetMediaUnitX()
{
	long result;
	GetProperty(0x25, VT_I4, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetMediaUnitX(long propVal)
{
	SetProperty(0x25, VT_I4, propVal);
}

long CNXReceiptPrinterX::GetMediaUnitY()
{
	long result;
	GetProperty(0x26, VT_I4, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetMediaUnitY(long propVal)
{
	SetProperty(0x26, VT_I4, propVal);
}

long CNXReceiptPrinterX::GetMediaSizeWidth()
{
	long result;
	GetProperty(0x27, VT_I4, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetMediaSizeWidth(long propVal)
{
	SetProperty(0x27, VT_I4, propVal);
}

long CNXReceiptPrinterX::GetMediaSizeHeight()
{
	long result;
	GetProperty(0x28, VT_I4, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetMediaSizeHeight(long propVal)
{
	SetProperty(0x28, VT_I4, propVal);
}

long CNXReceiptPrinterX::GetMediaPageCount()
{
	long result;
	GetProperty(0x29, VT_I4, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetMediaPageCount(long propVal)
{
	SetProperty(0x29, VT_I4, propVal);
}

long CNXReceiptPrinterX::GetMediaLineCount()
{
	long result;
	GetProperty(0x2a, VT_I4, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetMediaLineCount(long propVal)
{
	SetProperty(0x2a, VT_I4, propVal);
}

long CNXReceiptPrinterX::GetMediaPrintAreaX()
{
	long result;
	GetProperty(0x2b, VT_I4, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetMediaPrintAreaX(long propVal)
{
	SetProperty(0x2b, VT_I4, propVal);
}

long CNXReceiptPrinterX::GetMediaPrintAreaY()
{
	long result;
	GetProperty(0x2c, VT_I4, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetMediaPrintAreaY(long propVal)
{
	SetProperty(0x2c, VT_I4, propVal);
}

long CNXReceiptPrinterX::GetMediaPrintAreaWidth()
{
	long result;
	GetProperty(0x2d, VT_I4, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetMediaPrintAreaWidth(long propVal)
{
	SetProperty(0x2d, VT_I4, propVal);
}

long CNXReceiptPrinterX::GetMediaPrintAreaHeight()
{
	long result;
	GetProperty(0x2e, VT_I4, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetMediaPrintAreaHeight(long propVal)
{
	SetProperty(0x2e, VT_I4, propVal);
}

long CNXReceiptPrinterX::GetMediaRestrictedAreaWidth()
{
	long result;
	GetProperty(0x2f, VT_I4, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetMediaRestrictedAreaWidth(long propVal)
{
	SetProperty(0x2f, VT_I4, propVal);
}

long CNXReceiptPrinterX::GetMediaRestrictedAreaX()
{
	long result;
	GetProperty(0x30, VT_I4, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetMediaRestrictedAreaX(long propVal)
{
	SetProperty(0x30, VT_I4, propVal);
}

long CNXReceiptPrinterX::GetMediaRestrictedAreaY()
{
	long result;
	GetProperty(0x31, VT_I4, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetMediaRestrictedAreaY(long propVal)
{
	SetProperty(0x31, VT_I4, propVal);
}

long CNXReceiptPrinterX::GetMediaRestrictedAreaHeight()
{
	long result;
	GetProperty(0x32, VT_I4, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetMediaRestrictedAreaHeight(long propVal)
{
	SetProperty(0x32, VT_I4, propVal);
}

long CNXReceiptPrinterX::GetMediaStagger()
{
	long result;
	GetProperty(0x33, VT_I4, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetMediaStagger(long propVal)
{
	SetProperty(0x33, VT_I4, propVal);
}

CString CNXReceiptPrinterX::GetMediaFoldType()
{
	CString result;
	GetProperty(0x34, VT_BSTR, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetMediaFoldType(LPCTSTR propVal)
{
	SetProperty(0x34, VT_BSTR, propVal);
}

short CNXReceiptPrinterX::GetFormFieldIndexCount()
{
	short result;
	GetProperty(0x35, VT_I2, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetFormFieldIndexCount(short propVal)
{
	SetProperty(0x35, VT_I2, propVal);
}

CString CNXReceiptPrinterX::GetFormFieldOverflow()
{
	CString result;
	GetProperty(0x36, VT_BSTR, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetFormFieldOverflow(LPCTSTR propVal)
{
	SetProperty(0x36, VT_BSTR, propVal);
}

VARIANT CNXReceiptPrinterX::GetFormCharSet()
{
	VARIANT result;
	GetProperty(0x37, VT_VARIANT, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetFormCharSet(const VARIANT& propVal)
{
	SetProperty(0x37, VT_VARIANT, &propVal);
}

CString CNXReceiptPrinterX::GetMediaPaperSource()
{
	CString result;
	GetProperty(0x38, VT_BSTR, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetMediaPaperSource(LPCTSTR propVal)
{
	SetProperty(0x38, VT_BSTR, propVal);
}

VARIANT CNXReceiptPrinterX::GetPaperSupplies()
{
	VARIANT result;
	GetProperty(0x39, VT_VARIANT, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetPaperSupplies(const VARIANT& propVal)
{
	SetProperty(0x39, VT_VARIANT, &propVal);
}

VARIANT CNXReceiptPrinterX::GetSupportedCharSets()
{
	VARIANT result;
	GetProperty(0x3a, VT_VARIANT, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetSupportedCharSets(const VARIANT& propVal)
{
	SetProperty(0x3a, VT_VARIANT, &propVal);
}

BOOL CNXReceiptPrinterX::GetCanDispensePaper()
{
	BOOL result;
	GetProperty(0x3b, VT_BOOL, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetCanDispensePaper(BOOL propVal)
{
	SetProperty(0x3b, VT_BOOL, propVal);
}

BOOL CNXReceiptPrinterX::GetCanAcceptMedia()
{
	BOOL result;
	GetProperty(0x3c, VT_BOOL, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetCanAcceptMedia(BOOL propVal)
{
	SetProperty(0x3c, VT_BOOL, propVal);
}

BOOL CNXReceiptPrinterX::GetCanDetectVerticalExtents()
{
	BOOL result;
	GetProperty(0x3d, VT_BOOL, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetCanDetectVerticalExtents(BOOL propVal)
{
	SetProperty(0x3d, VT_BOOL, propVal);
}

BOOL CNXReceiptPrinterX::GetCanDetectHorizontalExtents()
{
	BOOL result;
	GetProperty(0x3e, VT_BOOL, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetCanDetectHorizontalExtents(BOOL propVal)
{
	SetProperty(0x3e, VT_BOOL, propVal);
}

short CNXReceiptPrinterX::GetNumberOfRetractBins()
{
	short result;
	GetProperty(0x3f, VT_I2, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetNumberOfRetractBins(short propVal)
{
	SetProperty(0x3f, VT_I2, propVal);
}

BOOL CNXReceiptPrinterX::GetCanPrintMultiplePages()
{
	BOOL result;
	GetProperty(0x40, VT_BOOL, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetCanPrintMultiplePages(BOOL propVal)
{
	SetProperty(0x40, VT_BOOL, propVal);
}

BOOL CNXReceiptPrinterX::GetCanDetectMediaTaken()
{
	BOOL result;
	GetProperty(0x41, VT_BOOL, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetCanDetectMediaTaken(BOOL propVal)
{
	SetProperty(0x41, VT_BOOL, propVal);
}

VARIANT CNXReceiptPrinterX::GetImageType()
{
	VARIANT result;
	GetProperty(0x42, VT_VARIANT, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetImageType(const VARIANT& propVal)
{
	SetProperty(0x42, VT_VARIANT, &propVal);
}

VARIANT CNXReceiptPrinterX::GetFrontImageColorFormat()
{
	VARIANT result;
	GetProperty(0x43, VT_VARIANT, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetFrontImageColorFormat(const VARIANT& propVal)
{
	SetProperty(0x43, VT_VARIANT, &propVal);
}

VARIANT CNXReceiptPrinterX::GetBackImageColorFormat()
{
	VARIANT result;
	GetProperty(0x44, VT_VARIANT, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetBackImageColorFormat(const VARIANT& propVal)
{
	SetProperty(0x44, VT_VARIANT, &propVal);
}

VARIANT CNXReceiptPrinterX::GetCodelineFormat()
{
	VARIANT result;
	GetProperty(0x45, VT_VARIANT, (void*)&result);
	return result;
}

void CNXReceiptPrinterX::SetCodelineFormat(const VARIANT& propVal)
{
	SetProperty(0x45, VT_VARIANT, &propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CNXReceiptPrinterX operations

long CNXReceiptPrinterX::OpenSessionSync(long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x46, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Timeout);
	return result;
}

long CNXReceiptPrinterX::CloseSessionSync()
{
	long result;
	InvokeHelper(0x47, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXReceiptPrinterX::RequestLock(long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x48, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Timeout);
	return result;
}

long CNXReceiptPrinterX::ReleaseLock()
{
	long result;
	InvokeHelper(0x49, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

CString CNXReceiptPrinterX::GetExtraStatus(LPCTSTR KeyName)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x4a, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		KeyName);
	return result;
}

CString CNXReceiptPrinterX::GetExtraCaps(LPCTSTR KeyName)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x4b, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		KeyName);
	return result;
}

long CNXReceiptPrinterX::ControlMedia(LPCTSTR Action, long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4;
	InvokeHelper(0x4c, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Action, Timeout);
	return result;
}

long CNXReceiptPrinterX::QueryForm(LPCTSTR FormName)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x4d, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		FormName);
	return result;
}

long CNXReceiptPrinterX::QueryFormList()
{
	long result;
	InvokeHelper(0x4e, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXReceiptPrinterX::QueryMediaList()
{
	long result;
	InvokeHelper(0x4f, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXReceiptPrinterX::QueryMedia(LPCTSTR MediaName)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x50, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		MediaName);
	return result;
}

long CNXReceiptPrinterX::QueryField(LPCTSTR FieldName)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x51, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		FieldName);
	return result;
}

long CNXReceiptPrinterX::SendRawData(long HasResponse, LPCTSTR RawData)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_BSTR;
	InvokeHelper(0x52, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		HasResponse, RawData);
	return result;
}

long CNXReceiptPrinterX::ReadForm(LPCTSTR FormName, LPCTSTR MediaName, LPCTSTR FieldNames, long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR VTS_I4;
	InvokeHelper(0x53, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		FormName, MediaName, FieldNames, Timeout);
	return result;
}

long CNXReceiptPrinterX::GetMediaExtents(LPCTSTR BaseUnit, short UnitX, short UnitY)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_I2 VTS_I2;
	InvokeHelper(0x54, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		BaseUnit, UnitX, UnitY);
	return result;
}

long CNXReceiptPrinterX::CancelAccept()
{
	long result;
	InvokeHelper(0x55, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

CString CNXReceiptPrinterX::GetFieldValue(LPCTSTR FieldName)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x56, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		FieldName);
	return result;
}

long CNXReceiptPrinterX::Reset(LPCTSTR Action, short BinNumber)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_I2;
	InvokeHelper(0x57, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Action, BinNumber);
	return result;
}

long CNXReceiptPrinterX::RetractMedia(short BinNumber)
{
	long result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x58, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		BinNumber);
	return result;
}

long CNXReceiptPrinterX::DispensePaper(LPCTSTR PaperSource)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x59, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		PaperSource);
	return result;
}

long CNXReceiptPrinterX::ResetRetractCount(short BinNumber)
{
	long result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x5a, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		BinNumber);
	return result;
}

long CNXReceiptPrinterX::PrintForm(LPCTSTR FormName, LPCTSTR MediaName, LPCTSTR Alignment, short OffsetX, short OffsetY, LPCTSTR Resolution, LPCTSTR FieldValues, long Timeout, LPCTSTR PaperSource)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR VTS_I2 VTS_I2 VTS_BSTR VTS_BSTR VTS_I4 VTS_BSTR;
	InvokeHelper(0x5b, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		FormName, MediaName, Alignment, OffsetX, OffsetY, Resolution, FieldValues, Timeout, PaperSource);
	return result;
}

long CNXReceiptPrinterX::CancelWaitForMediaTaken()
{
	long result;
	InvokeHelper(0x5c, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

CString CNXReceiptPrinterX::GetPaperStatus(LPCTSTR PaperSupply)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x5d, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, parms,
		PaperSupply);
	return result;
}

CString CNXReceiptPrinterX::GetRetractBinStatus(short BinNumber)
{
	CString result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x5e, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, parms,
		BinNumber);
	return result;
}

short CNXReceiptPrinterX::GetRetractCount(short BinNumber)
{
	short result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x5f, DISPATCH_PROPERTYGET, VT_I2, (void*)&result, parms,
		BinNumber);
	return result;
}

short CNXReceiptPrinterX::GetMaxRetract(short RetractBin)
{
	short result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x60, DISPATCH_PROPERTYGET, VT_I2, (void*)&result, parms,
		RetractBin);
	return result;
}
