#if !defined(AFX_NXRECEIPTPRINTERX_H__FE34E4AA_D3C7_4880_B028_8A802BE79CB3__INCLUDED_)
#define AFX_NXRECEIPTPRINTERX_H__FE34E4AA_D3C7_4880_B028_8A802BE79CB3__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CNXReceiptPrinterX wrapper class

class CNXReceiptPrinterX : public CWnd
{
protected:
	DECLARE_DYNCREATE(CNXReceiptPrinterX)
public:
	CLSID const& GetClsid()
	{
#ifdef UNDER_CE
		static CLSID const clsid
			= { 0xaa62b7b8, 0x3d06, 0x4453, { 0x9b, 0x56, 0x48, 0x56, 0xc8, 0x66, 0xa3, 0x44 } };
#else
		static CLSID const clsid
			= { 0x43A0D7F5, 0xF858, 0x4DAD, { 0x80, 0x32, 0x95, 0xC0, 0xF5, 0x89, 0xE0, 0x35 } };
#endif
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	CString GetDeviceStatus();
	void SetDeviceStatus(LPCTSTR);
	CString GetMediaStatus();
	void SetMediaStatus(LPCTSTR);
	CString GetTonerStatus();
	void SetTonerStatus(LPCTSTR);
	CString GetInkStatus();
	void SetInkStatus(LPCTSTR);
	CString GetLampStatus();
	void SetLampStatus(LPCTSTR);
	short GetMediaOnStackerCount();
	void SetMediaOnStackerCount(short);
	VARIANT GetResolution();
	void SetResolution(const VARIANT&);
	VARIANT GetReadTypes();
	void SetReadTypes(const VARIANT&);
	VARIANT GetWriteTypes();
	void SetWriteTypes(const VARIANT&);
	VARIANT GetControlMediaActions();
	void SetControlMediaActions(const VARIANT&);
	short GetMaxMediaOnStacker();
	void SetMaxMediaOnStacker(short);
	VARIANT GetFormList();
	void SetFormList(const VARIANT&);
	CString GetFormName();
	void SetFormName(LPCTSTR);
	CString GetFormAlignment();
	void SetFormAlignment(LPCTSTR);
	long GetFormUnitX();
	void SetFormUnitX(long);
	long GetFormUnitY();
	void SetFormUnitY(long);
	long GetFormWidth();
	void SetFormWidth(long);
	long GetFormHeight();
	void SetFormHeight(long);
	CString GetFormBase();
	void SetFormBase(LPCTSTR);
	CString GetFormOrientation();
	void SetFormOrientation(LPCTSTR);
	long GetFormOffsetX();
	void SetFormOffsetX(long);
	long GetFormOffsetY();
	void SetFormOffsetY(long);
	long GetFormVersionMajor();
	void SetFormVersionMajor(long);
	long GetFormVersionMinor();
	void SetFormVersionMinor(long);
	CString GetFormUserPrompt();
	void SetFormUserPrompt(LPCTSTR);
	VARIANT GetFormFieldList();
	void SetFormFieldList(const VARIANT&);
	CString GetFormFieldName();
	void SetFormFieldName(LPCTSTR);
	CString GetFormFieldType();
	void SetFormFieldType(LPCTSTR);
	CString GetFormFieldClass();
	void SetFormFieldClass(LPCTSTR);
	CString GetFormFieldAccess();
	void SetFormFieldAccess(LPCTSTR);
	CString GetFormFieldInitialValue();
	void SetFormFieldInitialValue(LPCTSTR);
	CString GetFormFieldFormat();
	void SetFormFieldFormat(LPCTSTR);
	VARIANT GetMediaList();
	void SetMediaList(const VARIANT&);
	CString GetMediaName();
	void SetMediaName(LPCTSTR);
	CString GetMediaType();
	void SetMediaType(LPCTSTR);
	CString GetMediaBase();
	void SetMediaBase(LPCTSTR);
	long GetMediaUnitX();
	void SetMediaUnitX(long);
	long GetMediaUnitY();
	void SetMediaUnitY(long);
	long GetMediaSizeWidth();
	void SetMediaSizeWidth(long);
	long GetMediaSizeHeight();
	void SetMediaSizeHeight(long);
	long GetMediaPageCount();
	void SetMediaPageCount(long);
	long GetMediaLineCount();
	void SetMediaLineCount(long);
	long GetMediaPrintAreaX();
	void SetMediaPrintAreaX(long);
	long GetMediaPrintAreaY();
	void SetMediaPrintAreaY(long);
	long GetMediaPrintAreaWidth();
	void SetMediaPrintAreaWidth(long);
	long GetMediaPrintAreaHeight();
	void SetMediaPrintAreaHeight(long);
	long GetMediaRestrictedAreaWidth();
	void SetMediaRestrictedAreaWidth(long);
	long GetMediaRestrictedAreaX();
	void SetMediaRestrictedAreaX(long);
	long GetMediaRestrictedAreaY();
	void SetMediaRestrictedAreaY(long);
	long GetMediaRestrictedAreaHeight();
	void SetMediaRestrictedAreaHeight(long);
	long GetMediaStagger();
	void SetMediaStagger(long);
	CString GetMediaFoldType();
	void SetMediaFoldType(LPCTSTR);
	short GetFormFieldIndexCount();
	void SetFormFieldIndexCount(short);
	CString GetFormFieldOverflow();
	void SetFormFieldOverflow(LPCTSTR);
	VARIANT GetFormCharSet();
	void SetFormCharSet(const VARIANT&);
	CString GetMediaPaperSource();
	void SetMediaPaperSource(LPCTSTR);
	VARIANT GetPaperSupplies();
	void SetPaperSupplies(const VARIANT&);
	VARIANT GetSupportedCharSets();
	void SetSupportedCharSets(const VARIANT&);
	BOOL GetCanDispensePaper();
	void SetCanDispensePaper(BOOL);
	BOOL GetCanAcceptMedia();
	void SetCanAcceptMedia(BOOL);
	BOOL GetCanDetectVerticalExtents();
	void SetCanDetectVerticalExtents(BOOL);
	BOOL GetCanDetectHorizontalExtents();
	void SetCanDetectHorizontalExtents(BOOL);
	short GetNumberOfRetractBins();
	void SetNumberOfRetractBins(short);
	BOOL GetCanPrintMultiplePages();
	void SetCanPrintMultiplePages(BOOL);
	BOOL GetCanDetectMediaTaken();
	void SetCanDetectMediaTaken(BOOL);
	VARIANT GetImageType();
	void SetImageType(const VARIANT&);
	VARIANT GetFrontImageColorFormat();
	void SetFrontImageColorFormat(const VARIANT&);
	VARIANT GetBackImageColorFormat();
	void SetBackImageColorFormat(const VARIANT&);
	VARIANT GetCodelineFormat();
	void SetCodelineFormat(const VARIANT&);

// Operations
public:
	long OpenSessionSync(long Timeout);
	long CloseSessionSync();
	long RequestLock(long Timeout);
	long ReleaseLock();
	CString GetExtraStatus(LPCTSTR KeyName);
	CString GetExtraCaps(LPCTSTR KeyName);
	long ControlMedia(LPCTSTR Action, long Timeout);
	long QueryForm(LPCTSTR FormName);
	long QueryFormList();
	long QueryMediaList();
	long QueryMedia(LPCTSTR MediaName);
	long QueryField(LPCTSTR FieldName);
	long SendRawData(long HasResponse, LPCTSTR RawData);
	long ReadForm(LPCTSTR FormName, LPCTSTR MediaName, LPCTSTR FieldNames, long Timeout);
	long GetMediaExtents(LPCTSTR BaseUnit, short UnitX, short UnitY);
	long CancelAccept();
	CString GetFieldValue(LPCTSTR FieldName);
	long Reset(LPCTSTR Action, short BinNumber);
	long RetractMedia(short BinNumber);
	long DispensePaper(LPCTSTR PaperSource);
	long ResetRetractCount(short BinNumber);
	long PrintForm(LPCTSTR FormName, LPCTSTR MediaName, LPCTSTR Alignment, short OffsetX, short OffsetY, LPCTSTR Resolution, LPCTSTR FieldValues, long Timeout, LPCTSTR PaperSource);
	long CancelWaitForMediaTaken();
	CString GetPaperStatus(LPCTSTR PaperSupply);
	CString GetRetractBinStatus(short BinNumber);
	short GetRetractCount(short BinNumber);
	short GetMaxRetract(short RetractBin);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_NXRECEIPTPRINTERX_H__FE34E4AA_D3C7_4880_B028_8A802BE79CB3__INCLUDED_)
