// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "nxrfidreaderx.h"

/////////////////////////////////////////////////////////////////////////////
// CNXRFIDReaderX

IMPLEMENT_DYNCREATE(CNXRFIDReaderX, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CNXRFIDReaderX properties

CString CNXRFIDReaderX::GetDeviceStatus()
{
	CString result;
	GetProperty(0x1, VT_BSTR, (void*)&result);
	return result;
}

void CNXRFIDReaderX::SetDeviceStatus(LPCTSTR propVal)
{
	SetProperty(0x1, VT_BSTR, propVal);
}

CString CNXRFIDReaderX::GetMediaStatus()
{
	CString result;
	GetProperty(0x2, VT_BSTR, (void*)&result);
	return result;
}

void CNXRFIDReaderX::SetMediaStatus(LPCTSTR propVal)
{
	SetProperty(0x2, VT_BSTR, propVal);
}

CString CNXRFIDReaderX::GetRetainBinStatus()
{
	CString result;
	GetProperty(0x3, VT_BSTR, (void*)&result);
	return result;
}

void CNXRFIDReaderX::SetRetainBinStatus(LPCTSTR propVal)
{
	SetProperty(0x3, VT_BSTR, propVal);
}

short CNXRFIDReaderX::GetMaxRetainCount()
{
	short result;
	GetProperty(0x4, VT_I2, (void*)&result);
	return result;
}

void CNXRFIDReaderX::SetMaxRetainCount(short propVal)
{
	SetProperty(0x4, VT_I2, propVal);
}

short CNXRFIDReaderX::GetRetainCount()
{
	short result;
	GetProperty(0x5, VT_I2, (void*)&result);
	return result;
}

void CNXRFIDReaderX::SetRetainCount(short propVal)
{
	SetProperty(0x5, VT_I2, propVal);
}

BOOL CNXRFIDReaderX::GetCanReadISO1Track()
{
	BOOL result;
	GetProperty(0x6, VT_BOOL, (void*)&result);
	return result;
}

void CNXRFIDReaderX::SetCanReadISO1Track(BOOL propVal)
{
	SetProperty(0x6, VT_BOOL, propVal);
}

BOOL CNXRFIDReaderX::GetCanReadISO2Track()
{
	BOOL result;
	GetProperty(0x7, VT_BOOL, (void*)&result);
	return result;
}

void CNXRFIDReaderX::SetCanReadISO2Track(BOOL propVal)
{
	SetProperty(0x7, VT_BOOL, propVal);
}

BOOL CNXRFIDReaderX::GetCanReadISO3Track()
{
	BOOL result;
	GetProperty(0x8, VT_BOOL, (void*)&result);
	return result;
}

void CNXRFIDReaderX::SetCanReadISO3Track(BOOL propVal)
{
	SetProperty(0x8, VT_BOOL, propVal);
}

BOOL CNXRFIDReaderX::GetCanWriteISO1Track()
{
	BOOL result;
	GetProperty(0x9, VT_BOOL, (void*)&result);
	return result;
}

void CNXRFIDReaderX::SetCanWriteISO1Track(BOOL propVal)
{
	SetProperty(0x9, VT_BOOL, propVal);
}

BOOL CNXRFIDReaderX::GetCanWriteISO2Track()
{
	BOOL result;
	GetProperty(0xa, VT_BOOL, (void*)&result);
	return result;
}

void CNXRFIDReaderX::SetCanWriteISO2Track(BOOL propVal)
{
	SetProperty(0xa, VT_BOOL, propVal);
}

BOOL CNXRFIDReaderX::GetCanWriteISO3Track()
{
	BOOL result;
	GetProperty(0xb, VT_BOOL, (void*)&result);
	return result;
}

void CNXRFIDReaderX::SetCanWriteISO3Track(BOOL propVal)
{
	SetProperty(0xb, VT_BOOL, propVal);
}

CString CNXRFIDReaderX::GetSecurityType()
{
	CString result;
	GetProperty(0xc, VT_BSTR, (void*)&result);
	return result;
}

void CNXRFIDReaderX::SetSecurityType(LPCTSTR propVal)
{
	SetProperty(0xc, VT_BSTR, propVal);
}

CString CNXRFIDReaderX::GetDeviceType()
{
	CString result;
	GetProperty(0xd, VT_BSTR, (void*)&result);
	return result;
}

void CNXRFIDReaderX::SetDeviceType(LPCTSTR propVal)
{
	SetProperty(0xd, VT_BSTR, propVal);
}

CString CNXRFIDReaderX::GetFormName()
{
	CString result;
	GetProperty(0xe, VT_BSTR, (void*)&result);
	return result;
}

void CNXRFIDReaderX::SetFormName(LPCTSTR propVal)
{
	SetProperty(0xe, VT_BSTR, propVal);
}

CString CNXRFIDReaderX::GetFormAction()
{
	CString result;
	GetProperty(0xf, VT_BSTR, (void*)&result);
	return result;
}

void CNXRFIDReaderX::SetFormAction(LPCTSTR propVal)
{
	SetProperty(0xf, VT_BSTR, propVal);
}

VARIANT CNXRFIDReaderX::GetTrack1Fields()
{
	VARIANT result;
	GetProperty(0x10, VT_VARIANT, (void*)&result);
	return result;
}

void CNXRFIDReaderX::SetTrack1Fields(const VARIANT& propVal)
{
	SetProperty(0x10, VT_VARIANT, &propVal);
}

VARIANT CNXRFIDReaderX::GetTrack2Fields()
{
	VARIANT result;
	GetProperty(0x11, VT_VARIANT, (void*)&result);
	return result;
}

void CNXRFIDReaderX::SetTrack2Fields(const VARIANT& propVal)
{
	SetProperty(0x11, VT_VARIANT, &propVal);
}

VARIANT CNXRFIDReaderX::GetTrack3Fields()
{
	VARIANT result;
	GetProperty(0x12, VT_VARIANT, (void*)&result);
	return result;
}

void CNXRFIDReaderX::SetTrack3Fields(const VARIANT& propVal)
{
	SetProperty(0x12, VT_VARIANT, &propVal);
}

CString CNXRFIDReaderX::GetTrack1Separator()
{
	CString result;
	GetProperty(0x13, VT_BSTR, (void*)&result);
	return result;
}

void CNXRFIDReaderX::SetTrack1Separator(LPCTSTR propVal)
{
	SetProperty(0x13, VT_BSTR, propVal);
}

CString CNXRFIDReaderX::GetTrack2Separator()
{
	CString result;
	GetProperty(0x14, VT_BSTR, (void*)&result);
	return result;
}

void CNXRFIDReaderX::SetTrack2Separator(LPCTSTR propVal)
{
	SetProperty(0x14, VT_BSTR, propVal);
}

CString CNXRFIDReaderX::GetTrack3Separator()
{
	CString result;
	GetProperty(0x15, VT_BSTR, (void*)&result);
	return result;
}

void CNXRFIDReaderX::SetTrack3Separator(LPCTSTR propVal)
{
	SetProperty(0x15, VT_BSTR, propVal);
}

CString CNXRFIDReaderX::GetTracks()
{
	CString result;
	GetProperty(0x16, VT_BSTR, (void*)&result);
	return result;
}

void CNXRFIDReaderX::SetTracks(LPCTSTR propVal)
{
	SetProperty(0x16, VT_BSTR, propVal);
}

CString CNXRFIDReaderX::GetTrack1Data()
{
	CString result;
	GetProperty(0x17, VT_BSTR, (void*)&result);
	return result;
}

void CNXRFIDReaderX::SetTrack1Data(LPCTSTR propVal)
{
	SetProperty(0x17, VT_BSTR, propVal);
}

CString CNXRFIDReaderX::GetTrack2Data()
{
	CString result;
	GetProperty(0x18, VT_BSTR, (void*)&result);
	return result;
}

void CNXRFIDReaderX::SetTrack2Data(LPCTSTR propVal)
{
	SetProperty(0x18, VT_BSTR, propVal);
}

CString CNXRFIDReaderX::GetTrack3Data()
{
	CString result;
	GetProperty(0x19, VT_BSTR, (void*)&result);
	return result;
}

void CNXRFIDReaderX::SetTrack3Data(LPCTSTR propVal)
{
	SetProperty(0x19, VT_BSTR, propVal);
}

CString CNXRFIDReaderX::GetSecurityData()
{
	CString result;
	GetProperty(0x1a, VT_BSTR, (void*)&result);
	return result;
}

void CNXRFIDReaderX::SetSecurityData(LPCTSTR propVal)
{
	SetProperty(0x1a, VT_BSTR, propVal);
}

VARIANT CNXRFIDReaderX::GetChipData()
{
	VARIANT result;
	GetProperty(0x1b, VT_VARIANT, (void*)&result);
	return result;
}

void CNXRFIDReaderX::SetChipData(const VARIANT& propVal)
{
	SetProperty(0x1b, VT_VARIANT, &propVal);
}

CString CNXRFIDReaderX::GetTrack1Status()
{
	CString result;
	GetProperty(0x1c, VT_BSTR, (void*)&result);
	return result;
}

void CNXRFIDReaderX::SetTrack1Status(LPCTSTR propVal)
{
	SetProperty(0x1c, VT_BSTR, propVal);
}

CString CNXRFIDReaderX::GetTrack2Status()
{
	CString result;
	GetProperty(0x1d, VT_BSTR, (void*)&result);
	return result;
}

void CNXRFIDReaderX::SetTrack2Status(LPCTSTR propVal)
{
	SetProperty(0x1d, VT_BSTR, propVal);
}

CString CNXRFIDReaderX::GetTrack3Status()
{
	CString result;
	GetProperty(0x1e, VT_BSTR, (void*)&result);
	return result;
}

void CNXRFIDReaderX::SetTrack3Status(LPCTSTR propVal)
{
	SetProperty(0x1e, VT_BSTR, propVal);
}

CString CNXRFIDReaderX::GetSecurityStatus()
{
	CString result;
	GetProperty(0x1f, VT_BSTR, (void*)&result);
	return result;
}

void CNXRFIDReaderX::SetSecurityStatus(LPCTSTR propVal)
{
	SetProperty(0x1f, VT_BSTR, propVal);
}

CString CNXRFIDReaderX::GetChipStatus()
{
	CString result;
	GetProperty(0x20, VT_BSTR, (void*)&result);
	return result;
}

void CNXRFIDReaderX::SetChipStatus(LPCTSTR propVal)
{
	SetProperty(0x20, VT_BSTR, propVal);
}

CString CNXRFIDReaderX::GetPowerOnOptions()
{
	CString result;
	GetProperty(0x21, VT_BSTR, (void*)&result);
	return result;
}

void CNXRFIDReaderX::SetPowerOnOptions(LPCTSTR propVal)
{
	SetProperty(0x21, VT_BSTR, propVal);
}

CString CNXRFIDReaderX::GetPowerOffOptions()
{
	CString result;
	GetProperty(0x22, VT_BSTR, (void*)&result);
	return result;
}

void CNXRFIDReaderX::SetPowerOffOptions(LPCTSTR propVal)
{
	SetProperty(0x22, VT_BSTR, propVal);
}

CString CNXRFIDReaderX::GetChipProtocols()
{
	CString result;
	GetProperty(0x23, VT_BSTR, (void*)&result);
	return result;
}

void CNXRFIDReaderX::SetChipProtocols(LPCTSTR propVal)
{
	SetProperty(0x23, VT_BSTR, propVal);
}

BOOL CNXRFIDReaderX::GetFluxSensorProgrammable()
{
	BOOL result;
	GetProperty(0x24, VT_BOOL, (void*)&result);
	return result;
}

void CNXRFIDReaderX::SetFluxSensorProgrammable(BOOL propVal)
{
	SetProperty(0x24, VT_BOOL, propVal);
}

BOOL CNXRFIDReaderX::GetCanRWFollowingEject()
{
	BOOL result;
	GetProperty(0x25, VT_BOOL, (void*)&result);
	return result;
}

void CNXRFIDReaderX::SetCanRWFollowingEject(BOOL propVal)
{
	SetProperty(0x25, VT_BOOL, propVal);
}

CString CNXRFIDReaderX::GetChipPowerStatus()
{
	CString result;
	GetProperty(0x26, VT_BSTR, (void*)&result);
	return result;
}

void CNXRFIDReaderX::SetChipPowerStatus(LPCTSTR propVal)
{
	SetProperty(0x26, VT_BSTR, propVal);
}

CString CNXRFIDReaderX::GetWriteMode()
{
	CString result;
	GetProperty(0x27, VT_BSTR, (void*)&result);
	return result;
}

void CNXRFIDReaderX::SetWriteMode(LPCTSTR propVal)
{
	SetProperty(0x27, VT_BSTR, propVal);
}

CString CNXRFIDReaderX::GetChipPowerType()
{
	CString result;
	GetProperty(0x28, VT_BSTR, (void*)&result);
	return result;
}

void CNXRFIDReaderX::SetChipPowerType(LPCTSTR propVal)
{
	SetProperty(0x28, VT_BSTR, propVal);
}

BOOL CNXRFIDReaderX::GetCanReadWMTrack()
{
	BOOL result;
	GetProperty(0x29, VT_BOOL, (void*)&result);
	return result;
}

void CNXRFIDReaderX::SetCanReadWMTrack(BOOL propVal)
{
	SetProperty(0x29, VT_BOOL, propVal);
}

BOOL CNXRFIDReaderX::GetCanWriteWMTrack()
{
	BOOL result;
	GetProperty(0x2a, VT_BOOL, (void*)&result);
	return result;
}

void CNXRFIDReaderX::SetCanWriteWMTrack(BOOL propVal)
{
	SetProperty(0x2a, VT_BOOL, propVal);
}

CString CNXRFIDReaderX::GetTrackWMStatus()
{
	CString result;
	GetProperty(0x2b, VT_BSTR, (void*)&result);
	return result;
}

void CNXRFIDReaderX::SetTrackWMStatus(LPCTSTR propVal)
{
	SetProperty(0x2b, VT_BSTR, propVal);
}

CString CNXRFIDReaderX::GetTrackWMData()
{
	CString result;
	GetProperty(0x2c, VT_BSTR, (void*)&result);
	return result;
}

void CNXRFIDReaderX::SetTrackWMData(LPCTSTR propVal)
{
	SetProperty(0x2c, VT_BSTR, propVal);
}

BOOL CNXRFIDReaderX::GetCanReadMPTrack()
{
	BOOL result;
	GetProperty(0x42, VT_BOOL, (void*)&result);
	return result;
}

void CNXRFIDReaderX::SetCanReadMPTrack(BOOL propVal)
{
	SetProperty(0x42, VT_BOOL, propVal);
}

CString CNXRFIDReaderX::GetTrackMPStatus()
{
	CString result;
	GetProperty(0x43, VT_BSTR, (void*)&result);
	return result;
}

void CNXRFIDReaderX::SetTrackMPStatus(LPCTSTR propVal)
{
	SetProperty(0x43, VT_BSTR, propVal);
}

CString CNXRFIDReaderX::GetTrackMPData()
{
	CString result;
	GetProperty(0x44, VT_BSTR, (void*)&result);
	return result;
}

void CNXRFIDReaderX::SetTrackMPData(LPCTSTR propVal)
{
	SetProperty(0x44, VT_BSTR, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CNXRFIDReaderX operations

long CNXRFIDReaderX::OpenSessionSync(long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x2d, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Timeout);
	return result;
}

long CNXRFIDReaderX::CloseSessionSync()
{
	long result;
	InvokeHelper(0x2e, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXRFIDReaderX::RequestLock(long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x2f, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Timeout);
	return result;
}

long CNXRFIDReaderX::ReleaseLock()
{
	long result;
	InvokeHelper(0x30, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

CString CNXRFIDReaderX::GetExtraStatus(LPCTSTR KeyName)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x31, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		KeyName);
	return result;
}

CString CNXRFIDReaderX::GetExtraCaps(LPCTSTR KeyName)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x32, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		KeyName);
	return result;
}

long CNXRFIDReaderX::ReadForm(LPCTSTR FormName, long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4;
	InvokeHelper(0x33, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		FormName, Timeout);
	return result;
}

long CNXRFIDReaderX::ReadRawData(LPCTSTR Tracks, long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4;
	InvokeHelper(0x34, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Tracks, Timeout);
	return result;
}

long CNXRFIDReaderX::ReadAvailableRawData(LPCTSTR Tracks, long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4;
	InvokeHelper(0x35, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Tracks, Timeout);
	return result;
}

long CNXRFIDReaderX::CancelAccept()
{
	long result;
	InvokeHelper(0x36, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXRFIDReaderX::EjectMedia(long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x37, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Timeout);
	return result;
}

long CNXRFIDReaderX::RetainMedia()
{
	long result;
	InvokeHelper(0x38, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXRFIDReaderX::ResetRetainCount()
{
	long result;
	InvokeHelper(0x39, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXRFIDReaderX::WriteForm(LPCTSTR FormName, LPCTSTR TrackData, LPCTSTR WriteMethod)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x3a, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		FormName, TrackData, WriteMethod);
	return result;
}

long CNXRFIDReaderX::WriteRawData(LPCTSTR Tracks, const VARIANT& TrackData, LPCTSTR WriteMethod)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_VARIANT VTS_BSTR;
	InvokeHelper(0x3b, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Tracks, &TrackData, WriteMethod);
	return result;
}

BOOL CNXRFIDReaderX::GetFieldValue(LPCTSTR FieldName, BSTR* FieldValue)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_PBSTR;
	InvokeHelper(0x3c, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		FieldName, FieldValue);
	return result;
}

long CNXRFIDReaderX::ChipIO(short Protocol, LPCTSTR Token, const VARIANT& Bytes, long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_I2 VTS_BSTR VTS_VARIANT VTS_I4;
	InvokeHelper(0x3d, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Protocol, Token, &Bytes, Timeout);
	return result;
}

long CNXRFIDReaderX::QueryFormList(VARIANT* FormList)
{
	long result;
	static BYTE parms[] =
		VTS_PVARIANT;
	InvokeHelper(0x3e, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		FormList);
	return result;
}

long CNXRFIDReaderX::QueryForm(LPCTSTR FormName)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x3f, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		FormName);
	return result;
}

long CNXRFIDReaderX::Reset(LPCTSTR ResetIn)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x40, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		ResetIn);
	return result;
}

long CNXRFIDReaderX::ChipPower(LPCTSTR ChipPower)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x41, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		ChipPower);
	return result;
}
