#if !defined(AFX_NXRFIDREADERX_H__8ECE82FF_6F81_47D9_9AC4_B804AA09EC79__INCLUDED_)
#define AFX_NXRFIDREADERX_H__8ECE82FF_6F81_47D9_9AC4_B804AA09EC79__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CNXRFIDReaderX wrapper class

class CNXRFIDReaderX : public CWnd
{
protected:
	DECLARE_DYNCREATE(CNXRFIDReaderX)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xddf7d417, 0xfb61, 0x44a0, { 0x80, 0x23, 0x6, 0xfc, 0x57, 0xab, 0xa9, 0xcf } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	CString GetDeviceStatus();
	void SetDeviceStatus(LPCTSTR);
	CString GetMediaStatus();
	void SetMediaStatus(LPCTSTR);
	CString GetRetainBinStatus();
	void SetRetainBinStatus(LPCTSTR);
	short GetMaxRetainCount();
	void SetMaxRetainCount(short);
	short GetRetainCount();
	void SetRetainCount(short);
	BOOL GetCanReadISO1Track();
	void SetCanReadISO1Track(BOOL);
	BOOL GetCanReadISO2Track();
	void SetCanReadISO2Track(BOOL);
	BOOL GetCanReadISO3Track();
	void SetCanReadISO3Track(BOOL);
	BOOL GetCanWriteISO1Track();
	void SetCanWriteISO1Track(BOOL);
	BOOL GetCanWriteISO2Track();
	void SetCanWriteISO2Track(BOOL);
	BOOL GetCanWriteISO3Track();
	void SetCanWriteISO3Track(BOOL);
	CString GetSecurityType();
	void SetSecurityType(LPCTSTR);
	CString GetDeviceType();
	void SetDeviceType(LPCTSTR);
	CString GetFormName();
	void SetFormName(LPCTSTR);
	CString GetFormAction();
	void SetFormAction(LPCTSTR);
	VARIANT GetTrack1Fields();
	void SetTrack1Fields(const VARIANT&);
	VARIANT GetTrack2Fields();
	void SetTrack2Fields(const VARIANT&);
	VARIANT GetTrack3Fields();
	void SetTrack3Fields(const VARIANT&);
	CString GetTrack1Separator();
	void SetTrack1Separator(LPCTSTR);
	CString GetTrack2Separator();
	void SetTrack2Separator(LPCTSTR);
	CString GetTrack3Separator();
	void SetTrack3Separator(LPCTSTR);
	CString GetTracks();
	void SetTracks(LPCTSTR);
	CString GetTrack1Data();
	void SetTrack1Data(LPCTSTR);
	CString GetTrack2Data();
	void SetTrack2Data(LPCTSTR);
	CString GetTrack3Data();
	void SetTrack3Data(LPCTSTR);
	CString GetSecurityData();
	void SetSecurityData(LPCTSTR);
	VARIANT GetChipData();
	void SetChipData(const VARIANT&);
	CString GetTrack1Status();
	void SetTrack1Status(LPCTSTR);
	CString GetTrack2Status();
	void SetTrack2Status(LPCTSTR);
	CString GetTrack3Status();
	void SetTrack3Status(LPCTSTR);
	CString GetSecurityStatus();
	void SetSecurityStatus(LPCTSTR);
	CString GetChipStatus();
	void SetChipStatus(LPCTSTR);
	CString GetPowerOnOptions();
	void SetPowerOnOptions(LPCTSTR);
	CString GetPowerOffOptions();
	void SetPowerOffOptions(LPCTSTR);
	CString GetChipProtocols();
	void SetChipProtocols(LPCTSTR);
	BOOL GetFluxSensorProgrammable();
	void SetFluxSensorProgrammable(BOOL);
	BOOL GetCanRWFollowingEject();
	void SetCanRWFollowingEject(BOOL);
	CString GetChipPowerStatus();
	void SetChipPowerStatus(LPCTSTR);
	CString GetWriteMode();
	void SetWriteMode(LPCTSTR);
	CString GetChipPowerType();
	void SetChipPowerType(LPCTSTR);
	BOOL GetCanReadWMTrack();
	void SetCanReadWMTrack(BOOL);
	BOOL GetCanWriteWMTrack();
	void SetCanWriteWMTrack(BOOL);
	CString GetTrackWMStatus();
	void SetTrackWMStatus(LPCTSTR);
	CString GetTrackWMData();
	void SetTrackWMData(LPCTSTR);
	BOOL GetCanReadMPTrack();
	void SetCanReadMPTrack(BOOL);
	CString GetTrackMPStatus();
	void SetTrackMPStatus(LPCTSTR);
	CString GetTrackMPData();
	void SetTrackMPData(LPCTSTR);

// Operations
public:
	long OpenSessionSync(long Timeout);
	long CloseSessionSync();
	long RequestLock(long Timeout);
	long ReleaseLock();
	CString GetExtraStatus(LPCTSTR KeyName);
	CString GetExtraCaps(LPCTSTR KeyName);
	long ReadForm(LPCTSTR FormName, long Timeout);
	long ReadRawData(LPCTSTR Tracks, long Timeout);
	long ReadAvailableRawData(LPCTSTR Tracks, long Timeout);
	long CancelAccept();
	long EjectMedia(long Timeout);
	long RetainMedia();
	long ResetRetainCount();
	long WriteForm(LPCTSTR FormName, LPCTSTR TrackData, LPCTSTR WriteMethod);
	long WriteRawData(LPCTSTR Tracks, const VARIANT& TrackData, LPCTSTR WriteMethod);
	BOOL GetFieldValue(LPCTSTR FieldName, BSTR* FieldValue);
	long ChipIO(short Protocol, LPCTSTR Token, const VARIANT& Bytes, long Timeout);
	long QueryFormList(VARIANT* FormList);
	long QueryForm(LPCTSTR FormName);
	long Reset(LPCTSTR ResetIn);
	long ChipPower(LPCTSTR ChipPower);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_NXRFIDREADERX_H__8ECE82FF_6F81_47D9_9AC4_B804AA09EC79__INCLUDED_)
