// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "nxscannerprinterx.h"

/////////////////////////////////////////////////////////////////////////////
// CNXScannerPrinterX

IMPLEMENT_DYNCREATE(CNXScannerPrinterX, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CNXScannerPrinterX properties

CString CNXScannerPrinterX::GetDeviceStatus()
{
	CString result;
	GetProperty(0x1, VT_BSTR, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetDeviceStatus(LPCTSTR propVal)
{
	SetProperty(0x1, VT_BSTR, propVal);
}

CString CNXScannerPrinterX::GetMediaStatus()
{
	CString result;
	GetProperty(0x2, VT_BSTR, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetMediaStatus(LPCTSTR propVal)
{
	SetProperty(0x2, VT_BSTR, propVal);
}

CString CNXScannerPrinterX::GetTonerStatus()
{
	CString result;
	GetProperty(0x3, VT_BSTR, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetTonerStatus(LPCTSTR propVal)
{
	SetProperty(0x3, VT_BSTR, propVal);
}

CString CNXScannerPrinterX::GetInkStatus()
{
	CString result;
	GetProperty(0x4, VT_BSTR, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetInkStatus(LPCTSTR propVal)
{
	SetProperty(0x4, VT_BSTR, propVal);
}

CString CNXScannerPrinterX::GetLampStatus()
{
	CString result;
	GetProperty(0x5, VT_BSTR, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetLampStatus(LPCTSTR propVal)
{
	SetProperty(0x5, VT_BSTR, propVal);
}

short CNXScannerPrinterX::GetMediaOnStackerCount()
{
	short result;
	GetProperty(0x6, VT_I2, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetMediaOnStackerCount(short propVal)
{
	SetProperty(0x6, VT_I2, propVal);
}

VARIANT CNXScannerPrinterX::GetResolution()
{
	VARIANT result;
	GetProperty(0x7, VT_VARIANT, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetResolution(const VARIANT& propVal)
{
	SetProperty(0x7, VT_VARIANT, &propVal);
}

VARIANT CNXScannerPrinterX::GetReadTypes()
{
	VARIANT result;
	GetProperty(0x8, VT_VARIANT, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetReadTypes(const VARIANT& propVal)
{
	SetProperty(0x8, VT_VARIANT, &propVal);
}

VARIANT CNXScannerPrinterX::GetWriteTypes()
{
	VARIANT result;
	GetProperty(0x9, VT_VARIANT, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetWriteTypes(const VARIANT& propVal)
{
	SetProperty(0x9, VT_VARIANT, &propVal);
}

VARIANT CNXScannerPrinterX::GetControlMediaActions()
{
	VARIANT result;
	GetProperty(0xa, VT_VARIANT, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetControlMediaActions(const VARIANT& propVal)
{
	SetProperty(0xa, VT_VARIANT, &propVal);
}

short CNXScannerPrinterX::GetMaxMediaOnStacker()
{
	short result;
	GetProperty(0xb, VT_I2, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetMaxMediaOnStacker(short propVal)
{
	SetProperty(0xb, VT_I2, propVal);
}

VARIANT CNXScannerPrinterX::GetFormList()
{
	VARIANT result;
	GetProperty(0xc, VT_VARIANT, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetFormList(const VARIANT& propVal)
{
	SetProperty(0xc, VT_VARIANT, &propVal);
}

CString CNXScannerPrinterX::GetFormName()
{
	CString result;
	GetProperty(0xd, VT_BSTR, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetFormName(LPCTSTR propVal)
{
	SetProperty(0xd, VT_BSTR, propVal);
}

CString CNXScannerPrinterX::GetFormAlignment()
{
	CString result;
	GetProperty(0xe, VT_BSTR, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetFormAlignment(LPCTSTR propVal)
{
	SetProperty(0xe, VT_BSTR, propVal);
}

long CNXScannerPrinterX::GetFormUnitX()
{
	long result;
	GetProperty(0xf, VT_I4, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetFormUnitX(long propVal)
{
	SetProperty(0xf, VT_I4, propVal);
}

long CNXScannerPrinterX::GetFormUnitY()
{
	long result;
	GetProperty(0x10, VT_I4, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetFormUnitY(long propVal)
{
	SetProperty(0x10, VT_I4, propVal);
}

long CNXScannerPrinterX::GetFormWidth()
{
	long result;
	GetProperty(0x11, VT_I4, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetFormWidth(long propVal)
{
	SetProperty(0x11, VT_I4, propVal);
}

long CNXScannerPrinterX::GetFormHeight()
{
	long result;
	GetProperty(0x12, VT_I4, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetFormHeight(long propVal)
{
	SetProperty(0x12, VT_I4, propVal);
}

CString CNXScannerPrinterX::GetFormBase()
{
	CString result;
	GetProperty(0x13, VT_BSTR, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetFormBase(LPCTSTR propVal)
{
	SetProperty(0x13, VT_BSTR, propVal);
}

CString CNXScannerPrinterX::GetFormOrientation()
{
	CString result;
	GetProperty(0x14, VT_BSTR, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetFormOrientation(LPCTSTR propVal)
{
	SetProperty(0x14, VT_BSTR, propVal);
}

long CNXScannerPrinterX::GetFormOffsetX()
{
	long result;
	GetProperty(0x15, VT_I4, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetFormOffsetX(long propVal)
{
	SetProperty(0x15, VT_I4, propVal);
}

long CNXScannerPrinterX::GetFormOffsetY()
{
	long result;
	GetProperty(0x16, VT_I4, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetFormOffsetY(long propVal)
{
	SetProperty(0x16, VT_I4, propVal);
}

long CNXScannerPrinterX::GetFormVersionMajor()
{
	long result;
	GetProperty(0x17, VT_I4, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetFormVersionMajor(long propVal)
{
	SetProperty(0x17, VT_I4, propVal);
}

long CNXScannerPrinterX::GetFormVersionMinor()
{
	long result;
	GetProperty(0x18, VT_I4, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetFormVersionMinor(long propVal)
{
	SetProperty(0x18, VT_I4, propVal);
}

CString CNXScannerPrinterX::GetFormUserPrompt()
{
	CString result;
	GetProperty(0x19, VT_BSTR, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetFormUserPrompt(LPCTSTR propVal)
{
	SetProperty(0x19, VT_BSTR, propVal);
}

VARIANT CNXScannerPrinterX::GetFormFieldList()
{
	VARIANT result;
	GetProperty(0x1a, VT_VARIANT, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetFormFieldList(const VARIANT& propVal)
{
	SetProperty(0x1a, VT_VARIANT, &propVal);
}

CString CNXScannerPrinterX::GetFormFieldName()
{
	CString result;
	GetProperty(0x1b, VT_BSTR, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetFormFieldName(LPCTSTR propVal)
{
	SetProperty(0x1b, VT_BSTR, propVal);
}

CString CNXScannerPrinterX::GetFormFieldType()
{
	CString result;
	GetProperty(0x1c, VT_BSTR, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetFormFieldType(LPCTSTR propVal)
{
	SetProperty(0x1c, VT_BSTR, propVal);
}

CString CNXScannerPrinterX::GetFormFieldClass()
{
	CString result;
	GetProperty(0x1d, VT_BSTR, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetFormFieldClass(LPCTSTR propVal)
{
	SetProperty(0x1d, VT_BSTR, propVal);
}

CString CNXScannerPrinterX::GetFormFieldAccess()
{
	CString result;
	GetProperty(0x1e, VT_BSTR, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetFormFieldAccess(LPCTSTR propVal)
{
	SetProperty(0x1e, VT_BSTR, propVal);
}

CString CNXScannerPrinterX::GetFormFieldInitialValue()
{
	CString result;
	GetProperty(0x1f, VT_BSTR, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetFormFieldInitialValue(LPCTSTR propVal)
{
	SetProperty(0x1f, VT_BSTR, propVal);
}

CString CNXScannerPrinterX::GetFormFieldFormat()
{
	CString result;
	GetProperty(0x20, VT_BSTR, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetFormFieldFormat(LPCTSTR propVal)
{
	SetProperty(0x20, VT_BSTR, propVal);
}

VARIANT CNXScannerPrinterX::GetMediaList()
{
	VARIANT result;
	GetProperty(0x21, VT_VARIANT, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetMediaList(const VARIANT& propVal)
{
	SetProperty(0x21, VT_VARIANT, &propVal);
}

CString CNXScannerPrinterX::GetMediaName()
{
	CString result;
	GetProperty(0x22, VT_BSTR, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetMediaName(LPCTSTR propVal)
{
	SetProperty(0x22, VT_BSTR, propVal);
}

CString CNXScannerPrinterX::GetMediaType()
{
	CString result;
	GetProperty(0x23, VT_BSTR, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetMediaType(LPCTSTR propVal)
{
	SetProperty(0x23, VT_BSTR, propVal);
}

CString CNXScannerPrinterX::GetMediaBase()
{
	CString result;
	GetProperty(0x24, VT_BSTR, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetMediaBase(LPCTSTR propVal)
{
	SetProperty(0x24, VT_BSTR, propVal);
}

long CNXScannerPrinterX::GetMediaUnitX()
{
	long result;
	GetProperty(0x25, VT_I4, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetMediaUnitX(long propVal)
{
	SetProperty(0x25, VT_I4, propVal);
}

long CNXScannerPrinterX::GetMediaUnitY()
{
	long result;
	GetProperty(0x26, VT_I4, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetMediaUnitY(long propVal)
{
	SetProperty(0x26, VT_I4, propVal);
}

long CNXScannerPrinterX::GetMediaSizeWidth()
{
	long result;
	GetProperty(0x27, VT_I4, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetMediaSizeWidth(long propVal)
{
	SetProperty(0x27, VT_I4, propVal);
}

long CNXScannerPrinterX::GetMediaSizeHeight()
{
	long result;
	GetProperty(0x28, VT_I4, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetMediaSizeHeight(long propVal)
{
	SetProperty(0x28, VT_I4, propVal);
}

long CNXScannerPrinterX::GetMediaPageCount()
{
	long result;
	GetProperty(0x29, VT_I4, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetMediaPageCount(long propVal)
{
	SetProperty(0x29, VT_I4, propVal);
}

long CNXScannerPrinterX::GetMediaLineCount()
{
	long result;
	GetProperty(0x2a, VT_I4, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetMediaLineCount(long propVal)
{
	SetProperty(0x2a, VT_I4, propVal);
}

long CNXScannerPrinterX::GetMediaPrintAreaX()
{
	long result;
	GetProperty(0x2b, VT_I4, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetMediaPrintAreaX(long propVal)
{
	SetProperty(0x2b, VT_I4, propVal);
}

long CNXScannerPrinterX::GetMediaPrintAreaY()
{
	long result;
	GetProperty(0x2c, VT_I4, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetMediaPrintAreaY(long propVal)
{
	SetProperty(0x2c, VT_I4, propVal);
}

long CNXScannerPrinterX::GetMediaPrintAreaWidth()
{
	long result;
	GetProperty(0x2d, VT_I4, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetMediaPrintAreaWidth(long propVal)
{
	SetProperty(0x2d, VT_I4, propVal);
}

long CNXScannerPrinterX::GetMediaPrintAreaHeight()
{
	long result;
	GetProperty(0x2e, VT_I4, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetMediaPrintAreaHeight(long propVal)
{
	SetProperty(0x2e, VT_I4, propVal);
}

long CNXScannerPrinterX::GetMediaRestrictedAreaX()
{
	long result;
	GetProperty(0x2f, VT_I4, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetMediaRestrictedAreaX(long propVal)
{
	SetProperty(0x2f, VT_I4, propVal);
}

long CNXScannerPrinterX::GetMediaRestrictedAreaY()
{
	long result;
	GetProperty(0x30, VT_I4, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetMediaRestrictedAreaY(long propVal)
{
	SetProperty(0x30, VT_I4, propVal);
}

long CNXScannerPrinterX::GetMediaRestrictedAreaWidth()
{
	long result;
	GetProperty(0x31, VT_I4, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetMediaRestrictedAreaWidth(long propVal)
{
	SetProperty(0x31, VT_I4, propVal);
}

long CNXScannerPrinterX::GetMediaRestrictedAreaHeight()
{
	long result;
	GetProperty(0x32, VT_I4, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetMediaRestrictedAreaHeight(long propVal)
{
	SetProperty(0x32, VT_I4, propVal);
}

long CNXScannerPrinterX::GetMediaStagger()
{
	long result;
	GetProperty(0x33, VT_I4, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetMediaStagger(long propVal)
{
	SetProperty(0x33, VT_I4, propVal);
}

CString CNXScannerPrinterX::GetMediaFoldType()
{
	CString result;
	GetProperty(0x34, VT_BSTR, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetMediaFoldType(LPCTSTR propVal)
{
	SetProperty(0x34, VT_BSTR, propVal);
}

short CNXScannerPrinterX::GetFormFieldIndexCount()
{
	short result;
	GetProperty(0x35, VT_I2, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetFormFieldIndexCount(short propVal)
{
	SetProperty(0x35, VT_I2, propVal);
}

CString CNXScannerPrinterX::GetFormFieldOverflow()
{
	CString result;
	GetProperty(0x36, VT_BSTR, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetFormFieldOverflow(LPCTSTR propVal)
{
	SetProperty(0x36, VT_BSTR, propVal);
}

VARIANT CNXScannerPrinterX::GetFormCharSet()
{
	VARIANT result;
	GetProperty(0x37, VT_VARIANT, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetFormCharSet(const VARIANT& propVal)
{
	SetProperty(0x37, VT_VARIANT, &propVal);
}

CString CNXScannerPrinterX::GetMediaPaperSource()
{
	CString result;
	GetProperty(0x38, VT_BSTR, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetMediaPaperSource(LPCTSTR propVal)
{
	SetProperty(0x38, VT_BSTR, propVal);
}

VARIANT CNXScannerPrinterX::GetPaperSupplies()
{
	VARIANT result;
	GetProperty(0x39, VT_VARIANT, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetPaperSupplies(const VARIANT& propVal)
{
	SetProperty(0x39, VT_VARIANT, &propVal);
}

VARIANT CNXScannerPrinterX::GetSupportedCharSets()
{
	VARIANT result;
	GetProperty(0x3a, VT_VARIANT, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetSupportedCharSets(const VARIANT& propVal)
{
	SetProperty(0x3a, VT_VARIANT, &propVal);
}

BOOL CNXScannerPrinterX::GetCanDispensePaper()
{
	BOOL result;
	GetProperty(0x3b, VT_BOOL, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetCanDispensePaper(BOOL propVal)
{
	SetProperty(0x3b, VT_BOOL, propVal);
}

BOOL CNXScannerPrinterX::GetCanAcceptMedia()
{
	BOOL result;
	GetProperty(0x3c, VT_BOOL, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetCanAcceptMedia(BOOL propVal)
{
	SetProperty(0x3c, VT_BOOL, propVal);
}

BOOL CNXScannerPrinterX::GetCanDetectVerticalExtents()
{
	BOOL result;
	GetProperty(0x3d, VT_BOOL, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetCanDetectVerticalExtents(BOOL propVal)
{
	SetProperty(0x3d, VT_BOOL, propVal);
}

BOOL CNXScannerPrinterX::GetCanDetectHorizontalExtents()
{
	BOOL result;
	GetProperty(0x3e, VT_BOOL, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetCanDetectHorizontalExtents(BOOL propVal)
{
	SetProperty(0x3e, VT_BOOL, propVal);
}

short CNXScannerPrinterX::GetNumberOfRetractBins()
{
	short result;
	GetProperty(0x3f, VT_I2, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetNumberOfRetractBins(short propVal)
{
	SetProperty(0x3f, VT_I2, propVal);
}

BOOL CNXScannerPrinterX::GetCanPrintMultiplePages()
{
	BOOL result;
	GetProperty(0x40, VT_BOOL, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetCanPrintMultiplePages(BOOL propVal)
{
	SetProperty(0x40, VT_BOOL, propVal);
}

BOOL CNXScannerPrinterX::GetCanDetectMediaTaken()
{
	BOOL result;
	GetProperty(0x41, VT_BOOL, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetCanDetectMediaTaken(BOOL propVal)
{
	SetProperty(0x41, VT_BOOL, propVal);
}

VARIANT CNXScannerPrinterX::GetImageType()
{
	VARIANT result;
	GetProperty(0x42, VT_VARIANT, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetImageType(const VARIANT& propVal)
{
	SetProperty(0x42, VT_VARIANT, &propVal);
}

VARIANT CNXScannerPrinterX::GetFrontImageColorFormat()
{
	VARIANT result;
	GetProperty(0x43, VT_VARIANT, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetFrontImageColorFormat(const VARIANT& propVal)
{
	SetProperty(0x43, VT_VARIANT, &propVal);
}

VARIANT CNXScannerPrinterX::GetBackImageColorFormat()
{
	VARIANT result;
	GetProperty(0x44, VT_VARIANT, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetBackImageColorFormat(const VARIANT& propVal)
{
	SetProperty(0x44, VT_VARIANT, &propVal);
}

VARIANT CNXScannerPrinterX::GetCodelineFormat()
{
	VARIANT result;
	GetProperty(0x45, VT_VARIANT, (void*)&result);
	return result;
}

void CNXScannerPrinterX::SetCodelineFormat(const VARIANT& propVal)
{
	SetProperty(0x45, VT_VARIANT, &propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CNXScannerPrinterX operations

long CNXScannerPrinterX::OpenSessionSync(long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x46, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Timeout);
	return result;
}

long CNXScannerPrinterX::CloseSessionSync()
{
	long result;
	InvokeHelper(0x47, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXScannerPrinterX::RequestLock(long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x48, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Timeout);
	return result;
}

long CNXScannerPrinterX::ReleaseLock()
{
	long result;
	InvokeHelper(0x49, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

CString CNXScannerPrinterX::GetExtraStatus(LPCTSTR KeyName)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x4a, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		KeyName);
	return result;
}

CString CNXScannerPrinterX::GetExtraCaps(LPCTSTR KeyName)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x4b, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		KeyName);
	return result;
}

long CNXScannerPrinterX::ControlMedia(LPCTSTR Actions, long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4;
	InvokeHelper(0x4c, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Actions, Timeout);
	return result;
}

long CNXScannerPrinterX::QueryForm(LPCTSTR FormName)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x4d, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		FormName);
	return result;
}

long CNXScannerPrinterX::QueryFormList()
{
	long result;
	InvokeHelper(0x4e, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXScannerPrinterX::QueryMediaList()
{
	long result;
	InvokeHelper(0x4f, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXScannerPrinterX::QueryMedia(LPCTSTR MediaName)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x50, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		MediaName);
	return result;
}

long CNXScannerPrinterX::QueryField(LPCTSTR FieldName)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x51, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		FieldName);
	return result;
}

long CNXScannerPrinterX::SendRawData(long HasResponse, LPCTSTR RawData)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_BSTR;
	InvokeHelper(0x52, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		HasResponse, RawData);
	return result;
}

long CNXScannerPrinterX::ReadImage(LPCTSTR ImageSources, LPCTSTR FrontImageColorFormat, LPCTSTR BackImageColorFormat, LPCTSTR CodelineFormat, LPCTSTR FrontImageType, LPCTSTR BackImageType, LPCTSTR FrontFileName, LPCTSTR BackFileName, long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR VTS_I4;
	InvokeHelper(0x53, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		ImageSources, FrontImageColorFormat, BackImageColorFormat, CodelineFormat, FrontImageType, BackImageType, FrontFileName, BackFileName, Timeout);
	return result;
}

long CNXScannerPrinterX::GetMediaExtents(LPCTSTR BaseUnit, short UnitX, short UnitY)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_I2 VTS_I2;
	InvokeHelper(0x54, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		BaseUnit, UnitX, UnitY);
	return result;
}

long CNXScannerPrinterX::CancelAccept()
{
	long result;
	InvokeHelper(0x55, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXScannerPrinterX::Reset(LPCTSTR Action, short BinNumber)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_I2;
	InvokeHelper(0x57, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Action, BinNumber);
	return result;
}

long CNXScannerPrinterX::RetractMedia(short BinNumber)
{
	long result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x58, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		BinNumber);
	return result;
}

long CNXScannerPrinterX::DispensePaper(LPCTSTR PaperSource)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x59, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		PaperSource);
	return result;
}

long CNXScannerPrinterX::ResetRetractCount(short BinNumber)
{
	long result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x5a, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		BinNumber);
	return result;
}

long CNXScannerPrinterX::PrintForm(LPCTSTR FormName, LPCTSTR MediaName, LPCTSTR Alignment, short OffsetX, short OffsetY, LPCTSTR Resolution, LPCTSTR FieldValues, long Timeout, LPCTSTR PaperSource)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR VTS_I2 VTS_I2 VTS_BSTR VTS_BSTR VTS_I4 VTS_BSTR;
	InvokeHelper(0x5b, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		FormName, MediaName, Alignment, OffsetX, OffsetY, Resolution, FieldValues, Timeout, PaperSource);
	return result;
}

long CNXScannerPrinterX::CancelWaitForMediaTaken()
{
	long result;
	InvokeHelper(0x5c, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

CString CNXScannerPrinterX::GetPaperStatus(LPCTSTR PaperSupply)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x5d, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, parms,
		PaperSupply);
	return result;
}

CString CNXScannerPrinterX::GetRetractBinStatus(short BinNumber)
{
	CString result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x5e, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, parms,
		BinNumber);
	return result;
}

short CNXScannerPrinterX::GetRetractCount(short BinNumber)
{
	short result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x5f, DISPATCH_PROPERTYGET, VT_I2, (void*)&result, parms,
		BinNumber);
	return result;
}

short CNXScannerPrinterX::GetMaxRetract(short BinNumber)
{
	short result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x60, DISPATCH_PROPERTYGET, VT_I2, (void*)&result, parms,
		BinNumber);
	return result;
}

