#if !defined(AFX_NXSENSORSX_H__A16E0BA8_9BC3_49F8_8BF9_8D709E5150D4__INCLUDED_)
#define AFX_NXSENSORSX_H__A16E0BA8_9BC3_49F8_8BF9_8D709E5150D4__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CNXSensorsX wrapper class

class CNXSensorsX : public CWnd
{
protected:
	DECLARE_DYNCREATE(CNXSensorsX)
public:
	CLSID const& GetClsid()
	{
#ifdef UNDER_CE
		static CLSID const clsid
			= { 0xb3a81453, 0x7a24, 0x4bc0, { 0xb1, 0x41, 0x69, 0x2d, 0xb9, 0x3c, 0xbd, 0x79 } };
#else
		static CLSID const clsid
			//= { 0xb3a81453, 0x7a24, 0x4bc0, { 0xb1, 0x41, 0x69, 0x2d, 0xb9, 0x3c, 0xbd, 0x79 } };
			//= { 0x8741ef24, 0x21f2, 0x46ad, { 0xa8, 0x20, 0x94, 0xa0, 0x2e, 0x73, 0xe3, 0x7e } };
			//= { 0xc0343098, 0x6573, 0x42c9, { 0xb3, 0xea, 0x7c, 0xfe, 0x8d, 0x85, 0x03, 0xc5 } };
			= { 0x76ba752c, 0x1feb, 0x4ac6, { 0x95, 0xd8, 0xb8, 0xb8, 0xa4, 0x6d, 0x9f, 0x12 } };
#endif
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	CString GetOperatorSwitchStatus();
	void SetOperatorSwitchStatus(LPCTSTR);
	CString GetTamperStatus();
	void SetTamperStatus(LPCTSTR);
	CString GetInternalTamperStatus();
	void SetInternalTamperStatus(LPCTSTR);
	CString GetSeismicStatus();
	void SetSeismicStatus(LPCTSTR);
	CString GetHeatStatus();
	void SetHeatStatus(LPCTSTR);
	CString GetProximityStatus();
	void SetProximityStatus(LPCTSTR);
	BOOL GetHasOperatorSwitch();
	void SetHasOperatorSwitch(BOOL);
	BOOL GetCanOPSwitchRun();
	void SetCanOPSwitchRun(BOOL);
	BOOL GetCanOPSwitchMaintenance();
	void SetCanOPSwitchMaintenance(BOOL);
	BOOL GetCanOPSwitchSupervisor();
	void SetCanOPSwitchSupervisor(BOOL);
	BOOL GetHasTamper();
	void SetHasTamper(BOOL);
	BOOL GetHasInternalTamper();
	void SetHasInternalTamper(BOOL);
	BOOL GetHasSeismic();
	void SetHasSeismic(BOOL);
	BOOL GetHasHeat();
	void SetHasHeat(BOOL);
	BOOL GetHasProximity();
	void SetHasProximity(BOOL);
	CString GetDeviceStatus();
	void SetDeviceStatus(LPCTSTR);
	CString GetAmblightStatus();
	void SetAmblightStatus(LPCTSTR);
	BOOL GetHasAmblight();
	void SetHasAmblight(BOOL);
	CString GetEnhancedAudioStatus();
	void SetEnhancedAudioStatus(LPCTSTR);
	BOOL GetHasEnhancedAudio();
	void SetHasEnhancedAudio(BOOL);
	BOOL GetCanAudioAuto();
	void SetCanAudioAuto(BOOL);
	BOOL GetCanAudioManual();
	void SetCanAudioManual(BOOL);
	BOOL GetCanAudioSemiAuto();
	void SetCanAudioSemiAuto(BOOL);
	CString GetLogicalServiceName();
	void SetLogicalServiceName(LPCTSTR);

// Operations
public:
	long OpenSessionSync(long Timeout);
	long CloseSessionSync();
	long RequestLock(long Timeout);
	long ReleaseLock();
	long Reset();
	CString GetExtraStatus(LPCTSTR KeyName);
	CString GetExtraCaps(LPCTSTR KeyName);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_NXSENSORSX_H__A16E0BA8_9BC3_49F8_8BF9_8D709E5150D4__INCLUDED_)
