// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "nxsensorsx.h"

/////////////////////////////////////////////////////////////////////////////
// CNXSensorsX

IMPLEMENT_DYNCREATE(CNXSensorsX, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CNXSensorsX properties

CString CNXSensorsX::GetOperatorSwitchStatus()
{
	CString result;
	GetProperty(0x1, VT_BSTR, (void*)&result);
	return result;
}

void CNXSensorsX::SetOperatorSwitchStatus(LPCTSTR propVal)
{
	SetProperty(0x1, VT_BSTR, propVal);
}

CString CNXSensorsX::GetTamperStatus()
{
	CString result;
	GetProperty(0x2, VT_BSTR, (void*)&result);
	return result;
}

void CNXSensorsX::SetTamperStatus(LPCTSTR propVal)
{
	SetProperty(0x2, VT_BSTR, propVal);
}

CString CNXSensorsX::GetInternalTamperStatus()
{
	CString result;
	GetProperty(0x3, VT_BSTR, (void*)&result);
	return result;
}

void CNXSensorsX::SetInternalTamperStatus(LPCTSTR propVal)
{
	SetProperty(0x3, VT_BSTR, propVal);
}

CString CNXSensorsX::GetSeismicStatus()
{
	CString result;
	GetProperty(0x4, VT_BSTR, (void*)&result);
	return result;
}

void CNXSensorsX::SetSeismicStatus(LPCTSTR propVal)
{
	SetProperty(0x4, VT_BSTR, propVal);
}

CString CNXSensorsX::GetHeatStatus()
{
	CString result;
	GetProperty(0x5, VT_BSTR, (void*)&result);
	return result;
}

void CNXSensorsX::SetHeatStatus(LPCTSTR propVal)
{
	SetProperty(0x5, VT_BSTR, propVal);
}

CString CNXSensorsX::GetProximityStatus()
{
	CString result;
	GetProperty(0x6, VT_BSTR, (void*)&result);
	return result;
}

void CNXSensorsX::SetProximityStatus(LPCTSTR propVal)
{
	SetProperty(0x6, VT_BSTR, propVal);
}

BOOL CNXSensorsX::GetHasOperatorSwitch()
{
	BOOL result;
	GetProperty(0x7, VT_BOOL, (void*)&result);
	return result;
}

void CNXSensorsX::SetHasOperatorSwitch(BOOL propVal)
{
	SetProperty(0x7, VT_BOOL, propVal);
}

BOOL CNXSensorsX::GetCanOPSwitchRun()
{
	BOOL result;
	GetProperty(0x8, VT_BOOL, (void*)&result);
	return result;
}

void CNXSensorsX::SetCanOPSwitchRun(BOOL propVal)
{
	SetProperty(0x8, VT_BOOL, propVal);
}

BOOL CNXSensorsX::GetCanOPSwitchMaintenance()
{
	BOOL result;
	GetProperty(0x9, VT_BOOL, (void*)&result);
	return result;
}

void CNXSensorsX::SetCanOPSwitchMaintenance(BOOL propVal)
{
	SetProperty(0x9, VT_BOOL, propVal);
}

BOOL CNXSensorsX::GetCanOPSwitchSupervisor()
{
	BOOL result;
	GetProperty(0xa, VT_BOOL, (void*)&result);
	return result;
}

void CNXSensorsX::SetCanOPSwitchSupervisor(BOOL propVal)
{
	SetProperty(0xa, VT_BOOL, propVal);
}

BOOL CNXSensorsX::GetHasTamper()
{
	BOOL result;
	GetProperty(0xb, VT_BOOL, (void*)&result);
	return result;
}

void CNXSensorsX::SetHasTamper(BOOL propVal)
{
	SetProperty(0xb, VT_BOOL, propVal);
}

BOOL CNXSensorsX::GetHasInternalTamper()
{
	BOOL result;
	GetProperty(0xc, VT_BOOL, (void*)&result);
	return result;
}

void CNXSensorsX::SetHasInternalTamper(BOOL propVal)
{
	SetProperty(0xc, VT_BOOL, propVal);
}

BOOL CNXSensorsX::GetHasSeismic()
{
	BOOL result;
	GetProperty(0xd, VT_BOOL, (void*)&result);
	return result;
}

void CNXSensorsX::SetHasSeismic(BOOL propVal)
{
	SetProperty(0xd, VT_BOOL, propVal);
}

BOOL CNXSensorsX::GetHasHeat()
{
	BOOL result;
	GetProperty(0xe, VT_BOOL, (void*)&result);
	return result;
}

void CNXSensorsX::SetHasHeat(BOOL propVal)
{
	SetProperty(0xe, VT_BOOL, propVal);
}

BOOL CNXSensorsX::GetHasProximity()
{
	BOOL result;
	GetProperty(0xf, VT_BOOL, (void*)&result);
	return result;
}

void CNXSensorsX::SetHasProximity(BOOL propVal)
{
	SetProperty(0xf, VT_BOOL, propVal);
}

CString CNXSensorsX::GetDeviceStatus()
{
	CString result;
	GetProperty(0x10, VT_BSTR, (void*)&result);
	return result;
}

void CNXSensorsX::SetDeviceStatus(LPCTSTR propVal)
{
	SetProperty(0x10, VT_BSTR, propVal);
}

CString CNXSensorsX::GetAmblightStatus()
{
	CString result;
	GetProperty(0x11, VT_BSTR, (void*)&result);
	return result;
}

void CNXSensorsX::SetAmblightStatus(LPCTSTR propVal)
{
	SetProperty(0x11, VT_BSTR, propVal);
}

BOOL CNXSensorsX::GetHasAmblight()
{
	BOOL result;
	GetProperty(0x12, VT_BOOL, (void*)&result);
	return result;
}

void CNXSensorsX::SetHasAmblight(BOOL propVal)
{
	SetProperty(0x12, VT_BOOL, propVal);
}

CString CNXSensorsX::GetEnhancedAudioStatus()
{
	CString result;
	GetProperty(0x13, VT_BSTR, (void*)&result);
	return result;
}

void CNXSensorsX::SetEnhancedAudioStatus(LPCTSTR propVal)
{
	SetProperty(0x13, VT_BSTR, propVal);
}

BOOL CNXSensorsX::GetHasEnhancedAudio()
{
	BOOL result;
	GetProperty(0x14, VT_BOOL, (void*)&result);
	return result;
}

void CNXSensorsX::SetHasEnhancedAudio(BOOL propVal)
{
	SetProperty(0x14, VT_BOOL, propVal);
}

BOOL CNXSensorsX::GetCanAudioAuto()
{
	BOOL result;
	GetProperty(0x15, VT_BOOL, (void*)&result);
	return result;
}

void CNXSensorsX::SetCanAudioAuto(BOOL propVal)
{
	SetProperty(0x15, VT_BOOL, propVal);
}

BOOL CNXSensorsX::GetCanAudioManual()
{
	BOOL result;
	GetProperty(0x16, VT_BOOL, (void*)&result);
	return result;
}

void CNXSensorsX::SetCanAudioManual(BOOL propVal)
{
	SetProperty(0x16, VT_BOOL, propVal);
}

BOOL CNXSensorsX::GetCanAudioSemiAuto()
{
	BOOL result;
	GetProperty(0x17, VT_BOOL, (void*)&result);
	return result;
}

void CNXSensorsX::SetCanAudioSemiAuto(BOOL propVal)
{
	SetProperty(0x17, VT_BOOL, propVal);
}

CString CNXSensorsX::GetLogicalServiceName()
{
	CString result;
	GetProperty(0x18, VT_BSTR, (void*)&result);
	return result;
}

void CNXSensorsX::SetLogicalServiceName(LPCTSTR propVal)
{
	SetProperty(0x18, VT_BSTR, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CNXSensorsX operations

long CNXSensorsX::OpenSessionSync(long Timeout)
{
#ifdef UNDER_CE
#  define OPENSSESSION_ID 0x19
#else
#  define OPENSSESSION_ID 0x18
#endif

	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(OPENSSESSION_ID, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Timeout);
	return result;
}

long CNXSensorsX::CloseSessionSync()
{
	long result;
	InvokeHelper(0x1a, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXSensorsX::RequestLock(long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x1b, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Timeout);
	return result;
}

long CNXSensorsX::ReleaseLock()
{
	long result;
	InvokeHelper(0x1c, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXSensorsX::Reset()
{
	long result;
	InvokeHelper(0x1d, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

CString CNXSensorsX::GetExtraStatus(LPCTSTR KeyName)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x1e, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		KeyName);
	return result;
}

CString CNXSensorsX::GetExtraCaps(LPCTSTR KeyName)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x1f, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		KeyName);
	return result;
}

void CNXSensorsX::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
