// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "nxtracex.h"

/////////////////////////////////////////////////////////////////////////////
// CNXTraceX

IMPLEMENT_DYNCREATE(CNXTraceX, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CNXTraceX properties

CString CNXTraceX::GetApplicationId()
{
	CString result;
	GetProperty(0x1, VT_BSTR, (void*)&result);
	return result;
}

void CNXTraceX::SetApplicationId(LPCTSTR propVal)
{
	SetProperty(0x1, VT_BSTR, propVal);
}

short CNXTraceX::GetStSpaceLeft()
{
	short result;
	GetProperty(0x2, VT_I2, (void*)&result);
	return result;
}

void CNXTraceX::SetStSpaceLeft(short propVal)
{
	SetProperty(0x2, VT_I2, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CNXTraceX operations

long CNXTraceX::LogEventSync(LPCTSTR szCategory1, LPCTSTR szCategory2, LPCTSTR szEvent)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x3, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		szCategory1, szCategory2, szEvent);
	return result;
}

short CNXTraceX::FlushSync()
{
	short result;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_I2, (void*)&result, NULL);
	return result;
}

CString CNXTraceX::MoveFirstSync()
{
	CString result;
	InvokeHelper(0x5, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString CNXTraceX::MoveLastSync()
{
	CString result;
	InvokeHelper(0x6, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString CNXTraceX::MoveNextSync()
{
	CString result;
	InvokeHelper(0x7, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString CNXTraceX::MovePrevSync()
{
	CString result;
	InvokeHelper(0x8, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

VARIANT CNXTraceX::ReadSync()
{
	VARIANT result;
	InvokeHelper(0x9, DISPATCH_METHOD, VT_VARIANT, (void*)&result, NULL);
	return result;
}

LPDISPATCH CNXTraceX::GetRecordSync(long EventID)
{
	LPDISPATCH result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xa, DISPATCH_METHOD, VT_DISPATCH, (void*)&result, parms,
		EventID);
	return result;
}

LPDISPATCH CNXTraceX::GetNextNewRecordSync()
{
	LPDISPATCH result;
	InvokeHelper(0xb, DISPATCH_METHOD, VT_DISPATCH, (void*)&result, NULL);
	return result;
}

short CNXTraceX::SaveToFile(LPCTSTR szFilePath, LPCTSTR szFilterExpression, long bForward, long bOverwrite, long MaxSize)
{
	short result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0xc, DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		szFilePath, szFilterExpression, bForward, bOverwrite, MaxSize);
	return result;
}

short CNXTraceX::ArchiveToFile(LPCTSTR szFilePath, LPCTSTR szFilterExpression, long MaxSize)
{
	short result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_I4;
	InvokeHelper(0xd, DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		szFilePath, szFilterExpression, MaxSize);
	return result;
}

BOOL CNXTraceX::IsValidFilterExpressionSync(LPCTSTR szFilterExpression)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0xe, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		szFilterExpression);
	return result;
}

void CNXTraceX::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
