#if !defined(AFX_NXTRACEX_H__AA80906F_875D_4F5C_8947_52EDF2410ED2__INCLUDED_)
#define AFX_NXTRACEX_H__AA80906F_875D_4F5C_8947_52EDF2410ED2__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CNXTraceX wrapper class

class CNXTraceX : public CWnd
{
protected:
	DECLARE_DYNCREATE(CNXTraceX)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xbe777b1, 0xbb3e, 0x4a34, { 0x8f, 0x39, 0xcd, 0x83, 0xea, 0xcd, 0x6e, 0x6e } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	CString GetApplicationId();
	void SetApplicationId(LPCTSTR);
	short GetStSpaceLeft();
	void SetStSpaceLeft(short);

// Operations
public:
	long LogEventSync(LPCTSTR szCategory1, LPCTSTR szCategory2, LPCTSTR szEvent);
	short FlushSync();
	CString MoveFirstSync();
	CString MoveLastSync();
	CString MoveNextSync();
	CString MovePrevSync();
	VARIANT ReadSync();
	LPDISPATCH GetRecordSync(long EventID);
	LPDISPATCH GetNextNewRecordSync();
	short SaveToFile(LPCTSTR szFilePath, LPCTSTR szFilterExpression, long bForward, long bOverwrite, long MaxSize);
	short ArchiveToFile(LPCTSTR szFilePath, LPCTSTR szFilterExpression, long MaxSize);
	BOOL IsValidFilterExpressionSync(LPCTSTR szFilterExpression);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_NXTRACEX_H__AA80906F_875D_4F5C_8947_52EDF2410ED2__INCLUDED_)
