// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "nxvendordependentmodex.h"

/////////////////////////////////////////////////////////////////////////////
// CNXVendorDependentModeX

IMPLEMENT_DYNCREATE(CNXVendorDependentModeX, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CNXVendorDependentModeX properties

CString CNXVendorDependentModeX::GetServiceStatus()
{
	CString result;
	GetProperty(0x1, VT_BSTR, (void*)&result);
	return result;
}

void CNXVendorDependentModeX::SetServiceStatus(LPCTSTR propVal)
{
	SetProperty(0x1, VT_BSTR, propVal);
}

CString CNXVendorDependentModeX::GetLogicalServiceName()
{
	CString result;
	GetProperty(0x2, VT_BSTR, (void*)&result);
	return result;
}

void CNXVendorDependentModeX::SetLogicalServiceName(LPCTSTR propVal)
{
	SetProperty(0x2, VT_BSTR, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CNXVendorDependentModeX operations

long CNXVendorDependentModeX::OpenSessionSync(long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x3, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Timeout);
	return result;
}

long CNXVendorDependentModeX::CloseSessionSync()
{
	long result;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXVendorDependentModeX::RequestLock(long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x5, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Timeout);
	return result;
}

long CNXVendorDependentModeX::ReleaseLock()
{
	long result;
	InvokeHelper(0x6, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXVendorDependentModeX::Initialize()
{
	long result;
	InvokeHelper(0x7, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

CString CNXVendorDependentModeX::GetExtraStatus(LPCTSTR KeyName)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x8, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		KeyName);
	return result;
}

CString CNXVendorDependentModeX::GetExtraCaps(LPCTSTR KeyName)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x9, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		KeyName);
	return result;
}

long CNXVendorDependentModeX::EnterVDM(long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xa, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Timeout);
	return result;
}

long CNXVendorDependentModeX::ExitVDM(long Timeout)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xb, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Timeout);
	return result;
}

long CNXVendorDependentModeX::AcknowledgeEnterVDM()
{
	long result;
	InvokeHelper(0xc, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNXVendorDependentModeX::AcknowledgeExitVDM()
{
	long result;
	InvokeHelper(0xd, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

void CNXVendorDependentModeX::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
