#if !defined(AFX_NXVENDORDEPENDENTMODEX_H__F305FD35_6CFE_4E45_8880_17D3320EB0ED__INCLUDED_)
#define AFX_NXVENDORDEPENDENTMODEX_H__F305FD35_6CFE_4E45_8880_17D3320EB0ED__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CNXVendorDependentModeX wrapper class

class CNXVendorDependentModeX : public CWnd
{
protected:
	DECLARE_DYNCREATE(CNXVendorDependentModeX)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x18195ff3, 0x7df5, 0x4539, { 0x87, 0x9, 0x3b, 0x12, 0x60, 0x16, 0x58, 0xb } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	CString GetServiceStatus();
	void SetServiceStatus(LPCTSTR);
	CString GetLogicalServiceName();
	void SetLogicalServiceName(LPCTSTR);

// Operations
public:
	long OpenSessionSync(long Timeout);
	long CloseSessionSync();
	long RequestLock(long Timeout);
	long ReleaseLock();
	long Initialize();
	CString GetExtraStatus(LPCTSTR KeyName);
	CString GetExtraCaps(LPCTSTR KeyName);
	long EnterVDM(long Timeout);
	long ExitVDM(long Timeout);
	long AcknowledgeEnterVDM();
	long AcknowledgeExitVDM();
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_NXVENDORDEPENDENTMODEX_H__F305FD35_6CFE_4E45_8880_17D3320EB0ED__INCLUDED_)
