//
// For EMV
#include "emvapi_mfs.h"


// CDR 메시지 정의
//
#define WM_EAGLE_CDR_OFFSET													(WM_USER + 0x300)
#define WM_EAGLE_CDR_MSDATA													(WM_EAGLE_CDR_OFFSET + 0)
#define WM_EAGLE_CDR_STATUS													(WM_EAGLE_CDR_OFFSET + 1)
#define WM_EAGLE_CDR_RETAINED												(WM_EAGLE_CDR_OFFSET + 2)
#define WM_EAGLE_CDR_PWRON_RSP												(WM_EAGLE_CDR_OFFSET + 3)
#define WM_EAGLE_CDR_DIRECT													(WM_EAGLE_CDR_OFFSET + 4)
#define WM_EAGLE_CDR_ERROR													(WM_EAGLE_CDR_OFFSET + 5)


//
// CDR 커맨드
//
#define SANKYO_CDR_CMD_INITIAL												0x30
#define SANKYO_CDR_CMD_STATUS												0x31
#define SANKYO_CDR_CMD_READ													0x32
#define SANKYO_CDR_CMD_LED_CONTOL											0x33
#define SANKYO_CDR_CMD_INFORMATION											0x36
#define SANKYO_CDR_CMD_SHUTTER												0x40
#define SANKYO_CDR_CMD_REVISION												0x41
#define SANKYO_CDR_CMD_KEY_GEN												0x47
#define SANKYO_CDR_CMD_ICC_CONTROL											0x49
#define SANKYO_CDR_CMD_SAM_CONTROL											0x49
#define SANKYO_CDR_CMD_SWITCH												0x4B
#define SANKYO_CDR_CMD_SMART_CONTROL										0x4D
#define SANKYO_CDR_CMD_SIMENS_CONTROL										0x52
#define SANKYO_CDR_CMD_I2C_CONTROL											0x53
#define SANKYO_CDR_CMD_TIMER_SET											0x57
#define SANKYO_CDR_CMD_PERFORMANCE_LOG										0x66
#define SANKYO_CDR_CMD_ERROR_LOG											0x66
#define SANKYO_CDR_CMD_PERFORMANCE_LOG_CLEAR								0x67
#define SANKYO_CDR_CMD_RESET												0x7A


//
// CDR 파라미터
//
#define SANKYO_CDR_PM_INITIAL												0x40
#define SANKYO_CDR_PM_STATUS_INQUIRE										0x30
#define SANKYO_CDR_PM_STATUS_INTAKE											0x31
#define SANKYO_CDR_PM_STATUS_WITHDRAW										0x32
#define SANKYO_CDR_PM_READ_ISO1												0x31
#define SANKYO_CDR_PM_READ_ISO2												0x32
#define SANKYO_CDR_PM_READ_ISO3												0x33
#define SANKYO_CDR_PM_READ_CLEAR_BUFF										0x36
#define SANKYO_CDR_PM_READ_ISO1_ENCRYT										0x41
#define SANKYO_CDR_PM_READ_ISO2_ENCRYT										0x42
#define SANKYO_CDR_PM_READ_ISO3_ENCRYT										0x43
#define SANKYO_CDR_PM_LED_CONTROL_LED_OFF									0x30
#define SANKYO_CDR_PM_LED_CONTROL_LED_RED									0x31
#define SANKYO_CDR_PM_LED_CONTROL_LED_GREEN									0x32
#define SANKYO_CDR_PM_LED_CONTROL_LED_YELLOW								0x33
#define SANKYO_CDR_PM_INFORMATION_EMV										0x30
#define SANKYO_CDR_PM_INFORMATION_GIE_CB									0x31
#define SANKYO_CDR_PM_INFORMATION_PASS_COUNT								0x32
#define SANKYO_CDR_PM_SHUTTER_OPEN											0x30
#define SANKYO_CDR_PM_REVISION_SUPERVISOR									0x30
#define SANKYO_CDR_PM_REVISION_USER											0x31
#define SANKYO_CDR_PM_REVISION_EMV2000										0x32
#define SANKYO_CDR_PM_REVISION_USER_CRC										0x3B
#define SANKYO_CDR_PM_REVISION_ICC_CRC										0x3C
#define SANKYO_CDR_PM_KEY_GEN_DEVICE										0x30
#define SANKYO_CDR_PM_KEY_GEN_MAGNETIC										0x31
#define SANKYO_CDR_PM_KEY_GEN_PIN_VERIFY									0x32
#define SANKYO_CDR_PM_KEY_GEN_APDU											0x33
#define SANKYO_CDR_PM_ICC_CONTROL_ACTIVATE									0x30
#define SANKYO_CDR_PM_ICC_CONTROL_DEACTIVATE								0x31
#define SANKYO_CDR_PM_ICC_CONTROL_STATUS									0x32
#define SANKYO_CDR_PM_ICC_CONTROL_COM1										0x34
#define SANKYO_CDR_PM_ICC_CONTROL_COM1_1									0x35
#define SANKYO_CDR_PM_ICC_CONTROL_COM1_2									0x36
#define SANKYO_CDR_PM_ICC_CONTROL_COM1_3									0x37
#define SANKYO_CDR_PM_ICC_CONTROL_RESET										0x38
#define SANKYO_CDR_PM_ICC_CONTROL_COM0										0x33
#define SANKYO_CDR_PM_ICC_CONTROL_AUTOMATIC									0x39
#define SANKYO_CDR_PM_ICC_CONTROL_DES_TRIPLE_0								0x53
#define SANKYO_CDR_PM_ICC_CONTROL_DES_TRIPLE_1								0x54
#define SANKYO_CDR_PM_ICC_CONTROL_DES_TRIPLE_2								0x59
#define SANKYO_CDR_PM_ICC_CONTROL_DES_SINGLE_0								0x63
#define SANKYO_CDR_PM_ICC_CONTROL_DES_SINGLE_1								0x64
#define SANKYO_CDR_PM_ICC_CONTROL_DES_SINGLE_2								0x69
#define SANKYO_CDR_PM_ICC_CONTROL_DES_TRIPLE_APDU_AUTOMATIC					0x79
#define SANKYO_CDR_PM_SAM_CONTROL_ACTIVATE									0x40
#define SANKYO_CDR_PM_SAM_CONTROL_DEACTIVATE								0x41
#define SANKYO_CDR_PM_SAM_CONTROL_STATUS									0x42
#define SANKYO_CDR_PM_SAM_CONTROL_COM0										0x43
#define SANKYO_CDR_PM_SAM_CONTROL_COM1										0x44
#define SANKYO_CDR_PM_SAM_CONTROL_COM1_1									0x45
#define SANKYO_CDR_PM_SAM_CONTROL_COM1_2									0x46
#define SANKYO_CDR_PM_SAM_CONTROL_COM1_3									0x47
#define SANKYO_CDR_PM_SAM_CONTROL_RESET										0x48
#define SANKYO_CDR_PM_SAM_CONTROL_AUTOMATIC									0x49
#define SANKYO_CDR_PM_SAM_CONTROL_SELECT									0x50
#define SANKYO_CDR_PM_SWITCH												0x30
#define SANKYO_CDR_PM_SMART_CONTROL_ACTIVATE								0x30
#define SANKYO_CDR_PM_SMART_CONTROL_DEACTIVATE								0x31
#define SANKYO_CDR_PM_SMART_CONTROL_STATUE									0x32
#define SANKYO_CDR_PM_SMART_CONTROL_COMM									0x33
#define SANKYO_CDR_PM_SIMENS_CONTROL_ACTIVATE								0x30
#define SANKYO_CDR_PM_SIMENS_CONTROL_DEACTIVATE								0x31
#define SANKYO_CDR_PM_SIMENS_CONTROL_STATUS									0x32
#define SANKYO_CDR_PM_SIMENS_CONTROL_COMM4442								0x33
#define SANKYO_CDR_PM_SIMENS_CONTROL_COMM4428								0x34
#define SANKYO_CDR_PM_I2C_CONTROL_ACTIVATE									0x30
#define SANKYO_CDR_PM_I2C_CONTROL_DEACTIVATE								0x31
#define SANKYO_CDR_PM_I2C_CONTROL_STATUS									0x32
#define SANKYO_CDR_PM_I2C_CONTROL_COMM										0x33
#define SANKYO_CDR_PM_TIMER_SET_INSERTION									0x30
#define SANKYO_CDR_PM_TIMER_SET_WITHDRAWAL									0x31
#define SANKYO_CDR_PM_TIMER_SET_READ_METHOD									0x32
#define SANKYO_CDR_PM_PERFORMANCE_LOG										0x30
#define SANKYO_CDR_PM_ERROR_LOG												0x31
#define SANKYO_CDR_PM_PERFORMANCE_LOG_CLEAR_PASS_COUNTER					0x31
#define SANKYO_CDR_PM_PERFORMANCE_LOG_CLEAR_MAGNETIC						0x32
#define SANKYO_CDR_PM_PERFORMANCE_LOG_CLEAR_ICC								0x33
#define SANKYO_CDR_PM_PERFORMANCE_LOG_CLEAR_SAM1							0x34
#define SANKYO_CDR_PM_PERFORMANCE_LOG_CLEAR_SAM2_SAM5						0x35
#define SANKYO_CDR_PM_PERFORMANCE_LOG_CLEAR_LATCH							0x36
#define SANKYO_CDR_PM_RESET													0x30


//
// Return Code : ALL API
//
#define	EAGLE_CDR_ERROR_CODE_ORIGIN											(0x0000)
#define	EAGLE_CDR_NO_ERROR													(EAGLE_CDR_ERROR_CODE_ORIGIN + 0x00)
#define	EAGLE_CDR_DEVICE_NOT_CONNECTED_ERROR								(EAGLE_CDR_ERROR_CODE_ORIGIN + 0x01)
#define	EAGLE_CDR_CANCEL_COMMAND_SESSION_ERROR								(EAGLE_CDR_ERROR_CODE_ORIGIN + 0x02)
#define	EAGLE_CDR_FAILED_TO_SEND_COMMAND_ERROR								(EAGLE_CDR_ERROR_CODE_ORIGIN + 0x03)
#define EAGLE_CDR_FAILED_TO_RECEIVE_REPLY_ERROR								(EAGLE_CDR_ERROR_CODE_ORIGIN + 0x04)
#define EAGLE_CDR_COMMAND_CANCELED											(EAGLE_CDR_ERROR_CODE_ORIGIN + 0x05)
#define EAGLE_CDR_REPLY_TIMEOUT												(EAGLE_CDR_ERROR_CODE_ORIGIN + 0x06)


//
// Return codes : ConnectDevice
//
#define	EAGLE_CDR_CANNOT_CREATE_OBJECT_ERROR								(EAGLE_CDR_ERROR_CODE_ORIGIN + 0x0101)
#define	EAGLE_CDR_DEVICE_NOT_READY_ERROR									(EAGLE_CDR_ERROR_CODE_ORIGIN + 0x0102)
#define	EAGLE_CDR_CANNOT_OPEN_PORT_ERROR									(EAGLE_CDR_ERROR_CODE_ORIGIN + 0x0103)
#define	EAGLE_CDR_FAILED_TO_BEGIN_THREAD_ERROR								(EAGLE_CDR_ERROR_CODE_ORIGIN + 0x0104)
#define	EAGLE_CDR_DEVICE_ALREADY_CONNECTED_ERROR							(EAGLE_CDR_ERROR_CODE_ORIGIN + 0x0105)


//
// Return codes : UpdateFirmware
//
#define	EAGLE_CDR_UPDATE_FIRMWARE_UNEXPECTED_ERROR							(EAGLE_CDR_ERROR_CODE_ORIGIN + 0x1001)
#define	EAGLE_CDR_UPDATE_FIRMWARE_UNKNOWN_FILE_TYPE_ERROR					(EAGLE_CDR_ERROR_CODE_ORIGIN + 0x1002)
#define	EAGLE_CDR_UPDATE_FIRMWARE_CANNOT_OPEN_FILE_ERROR					(EAGLE_CDR_ERROR_CODE_ORIGIN + 0x1003)
#define	EAGLE_CDR_UPDATE_FIRMWARE_FAILED_TO_ALLOCATE_MEMORY_REGION_ERROR	(EAGLE_CDR_ERROR_CODE_ORIGIN + 0x1004)
#define	EAGLE_CDR_UPDATE_FIRMWARE_CANNOT_READ_FILE_ERROR					(EAGLE_CDR_ERROR_CODE_ORIGIN + 0x1005)
#define	EAGLE_CDR_UPDATE_FIRMWARE_CONNECT_DEVICE_FAILED_ERROR				(EAGLE_CDR_ERROR_CODE_ORIGIN + 0x1006)
#define	EAGLE_CDR_UPDATE_FIRMWARE_DEVICE_ALREADY_CONNECTED_ERROR			(EAGLE_CDR_ERROR_CODE_ORIGIN + 0x1007)
#define	EAGLE_CDR_UPDATE_FIRMWARE_COMMAND_EXECUTION_FAILED_ERROR			(EAGLE_CDR_ERROR_CODE_ORIGIN + 0x1008)
#define	EAGLE_CDR_UPDATE_FIRMWARE_NEGATIVE_REPLY_RECEIVED_ERROR				(EAGLE_CDR_ERROR_CODE_ORIGIN + 0x1009)
#define	EAGLE_CDR_UPDATE_FIRMWARE_DISCONNECT_DEVICE_FAILED_ERROR			(EAGLE_CDR_ERROR_CODE_ORIGIN + 0x100A)
#define	EAGLE_CDR_UPDATE_FIRMWARE_UNEXPECTED_FILE_CONTENTS_ERROR			(EAGLE_CDR_ERROR_CODE_ORIGIN + 0x100B)
#define	EAGLE_CDR_UPDATE_FIRMWARE_IDENTICAL_REVISION_ERROR					(EAGLE_CDR_ERROR_CODE_ORIGIN + 0x100C)


//
// Return codes : ICCardTransmit
//
#define	EAGLE_CDR_ICC_TRANSMIT_UNEXPECTED_ERROR								(EAGLE_CDR_ERROR_CODE_ORIGIN + 0x2001)
#define	EAGLE_CDR_ICC_TRANSMIT_FAILED_TO_ALLOCATE_MEMORY_REGION_ERROR		(EAGLE_CDR_ERROR_CODE_ORIGIN + 0x2002)
#define	EAGLE_CDR_ICC_TRANSMIT_ABORT_REQUEST_RECEIVED_ERROR					(EAGLE_CDR_ERROR_CODE_ORIGIN + 0x2003)
#define	EAGLE_CDR_ICC_TRANSMIT_COMMAND_EXECUTION_FAILED_ERROR				(EAGLE_CDR_ERROR_CODE_ORIGIN + 0x2004)
#define	EAGLE_CDR_ICC_TRANSMIT_NEGATIVE_REPLY_RECEIVED_ERROR				(EAGLE_CDR_ERROR_CODE_ORIGIN + 0x2005)


//
// Return codes : SAMTransmit
//
#define	EAGLE_CDR_SAM_TRANSMIT_UNEXPECTED_ERROR								(EAGLE_CDR_ERROR_CODE_ORIGIN + 0x3001)
#define	EAGLE_CDR_SAM_TRANSMIT_FAILED_TO_ALLOCATE_MEMORY_REGION_ERROR		(EAGLE_CDR_ERROR_CODE_ORIGIN + 0x3002)
#define	EAGLE_CDR_SAM_TRANSMIT_ABORT_REQUEST_RECEIVED_ERROR					(EAGLE_CDR_ERROR_CODE_ORIGIN + 0x3003)
#define	EAGLE_CDR_SAM_TRANSMIT_COMMAND_EXECUTION_FAILED_ERROR				(EAGLE_CDR_ERROR_CODE_ORIGIN + 0x3004)
#define	EAGLE_CDR_SAM_TRANSMIT_NEGATIVE_REPLY_RECEIVED_ERROR				(EAGLE_CDR_ERROR_CODE_ORIGIN + 0x3005)


#define	MAX_DATA_ARRAY_SIZE		(1024)

// Define Card Position
#define		CARD_EMPTY					(BYTE)0x30
#define		CARD_FRONT_DETECT			(BYTE)0x01
#define		CARD_REAR_DETECT			(BYTE)0x02
#define		CARD_LOCK_DETECT			(BYTE)0x04

// Define Card Status
#define		CARD_NORMAL			0
#define		CARD_ERROR			1

#define		ENCRYPTION_KEY_LENGTH	16
#define		ENCRYPTION_IV_LENGTH	8
#define		GENERATED_KEY_DATA_LENGTH	(ENCRYPTION_KEY_LENGTH+ENCRYPTION_IV_LENGTH)
#define		DATA_PADDING_SIZE		8

#define CDR_CERTIFICATION_ERROR	_T("C0000B")
#define NO_ENCRYPT_KEY			_T("C00006")
#define WEAK_ENCRYPT_KEY		_T("C00004")
#define CARDDATA_ERROR			_T("C00025")


typedef VOID(WINAPI *CALL_BACK_FUNCTION) (WPARAM, LPARAM);


typedef	struct
{
	struct
	{
		CHAR	szFilename[_MAX_FNAME];
		CHAR	szRevision[32];
	}
	upperDll;

	struct
	{
		TCHAR	szFilename[_MAX_FNAME];
		TCHAR	szRevision[32];
	}
	middleDll;

	struct
	{
		CHAR	szFilename[_MAX_FNAME];
		CHAR	szRevision[32];
	}
	lowerDll;
}
DLL_INFORMATION, *LPDLL_INFORMATION;


/* Data structure for command message	*/
typedef	struct
{
	BYTE	bCommandCode;
	BYTE	bParameterCode;

	struct
	{
		DWORD	dwSize;
		LPBYTE	lpbBody;
	}
	Data;
}
COMMAND, *LPCOMMAND;


/* Received message type	*/
typedef	enum
{
	PositiveReply,
	NegativeReply,
	ReplyReceivingFailure,
	CommandCancellation,
	ReplyTimeout,
}
REPLY_TYPE, *LPREPLY_TYPE;

/* Return Value	*/
typedef	enum
{
	NoError,
	DeviceNotConnectedError,
	CancelCommandSessionError,
	FailedToSendCommandError,
	FailedToReceiveReplyError,
	CommandCanceled,
	ReturnReplyTimeout,
}
RETURN_VALUE, *LPRETURN_VALUE;


/* Data structure for positive reply message	*/
typedef	struct
{
	BYTE	bCommandCode;
	BYTE	bParameterCode;

	struct
	{
		BYTE	bSt1;
		BYTE	bSt0;
	}
	StatusCode;

	struct
	{
		DWORD	dwSize;
		BYTE	bBody[MAX_DATA_ARRAY_SIZE];
	}
	Data;
}
POSITIVE_REPLY, *LPPOSITIVE_REPLY;


/* Data structure for negative reply message	*/
typedef	struct
{
	BYTE	bCommandCode;
	BYTE	bParameterCode;

	struct
	{
		BYTE	bE1;
		BYTE	bE0;
	}
	ErrorCode;	// code = E1,E0

	struct
	{
		DWORD	dwSize;
		BYTE	bBody[MAX_DATA_ARRAY_SIZE];
	}
	Data;
}
NEGATIVE_REPLY, *LPNEGATIVE_REPLY;


/* Data structure for reply message	*/
typedef struct
{
	REPLY_TYPE		replyType;

	union
	{
		POSITIVE_REPLY	positiveReply;
		NEGATIVE_REPLY	negativeReply;
	}
	message;

}
REPLY, *LPREPLY;

