// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "nhmwi.h"

/////////////////////////////////////////////////////////////////////////////
// CNHMWI

IMPLEMENT_DYNCREATE(CNHMWI, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CNHMWI properties

/////////////////////////////////////////////////////////////////////////////
// CNHMWI operations

CString CNHMWI::TestMethod(LPCTSTR szParam1, LPCTSTR szParam2, LPCTSTR szParam3)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x1, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		szParam1, szParam2, szParam3);
	return result;
}

void CNHMWI::ProcSetDeviceEvent(LPCTSTR szDeviceName, LPCTSTR szEventName, LPCTSTR szEventValue)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 szDeviceName, szEventName, szEventValue);
}

void CNHMWI::ProcSetDeviceStatus(LPCTSTR szDeviceName, LPCTSTR szProperty, LPCTSTR szStatus)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x3, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 szDeviceName, szProperty, szStatus);
}

long CNHMWI::McuEntryDisable()
{
	long result;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

CString CNHMWI::McuGetCardData()
{
	CString result;
	InvokeHelper(0x5, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

long CNHMWI::McuInitialize()
{
	long result;
	InvokeHelper(0x6, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::McuRead()
{
	long result;
	InvokeHelper(0x7, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::McuRetract()
{
	long result;
	InvokeHelper(0x8, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::McuWrite(LPCTSTR szTrackData)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x9, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		szTrackData);
	return result;
}

long CNHMWI::SprGetPaperStatus()
{
	long result;
	InvokeHelper(0xa, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::JprEmbossPrint()
{
	long result;
	InvokeHelper(0xb, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::JprGetPaperStatus()
{
	long result;
	InvokeHelper(0xc, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::JprInitialize()
{
	long result;
	InvokeHelper(0xd, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::McuDeinitialize()
{
	long result;
	InvokeHelper(0xe, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

CString CNHMWI::CheckDeviceAction(long nDevID, long nWaitSec)
{
	CString result;
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0xf, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		nDevID, nWaitSec);
	return result;
}

long CNHMWI::McuWaitTaken()
{
	long result;
	InvokeHelper(0x10, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::SprDeinitialize()
{
	long result;
	InvokeHelper(0x11, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::SprWaitTaken()
{
	long result;
	InvokeHelper(0x12, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::ScanDeviceAction(long nDevID, long nWaitSec, long nEventKind)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0x13, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nDevID, nWaitSec, nEventKind);
	return result;
}

long CNHMWI::McuEntryEnable(long nWaitSec)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x14, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nWaitSec);
	return result;
}

long CNHMWI::GetErrorDevice(long nDevID)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x15, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nDevID);
	return result;
}

long CNHMWI::McuGetMaterialInfo()
{
	long result;
	InvokeHelper(0x16, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::SprGetMaterialInfo()
{
	long result;
	InvokeHelper(0x17, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::JprGetMaterialInfo()
{
	long result;
	InvokeHelper(0x18, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::SprInitialize()
{
	long result;
	InvokeHelper(0x19, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::JprDeinitialize()
{
	long result;
	InvokeHelper(0x1a, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::McuEject(long nWaitSec)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x1b, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nWaitSec);
	return result;
}

long CNHMWI::SprPrint(LPCTSTR szPrintData)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x1c, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		szPrintData);
	return result;
}

long CNHMWI::JprPrint(LPCTSTR szPrintData)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x1d, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		szPrintData);
	return result;
}

long CNHMWI::JprGetDeviceStatus()
{
	long result;
	InvokeHelper(0x1e, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::SprGetDeviceStatus()
{
	long result;
	InvokeHelper(0x1f, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::SprEject(long nWaitSec)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x20, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nWaitSec);
	return result;
}

long CNHMWI::SprRetract()
{
	long result;
	InvokeHelper(0x21, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::McuGetDeviceStatus()
{
	long result;
	InvokeHelper(0x22, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::DorInitialize()
{
	long result;
	InvokeHelper(0x23, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::DorDeinitialize()
{
	long result;
	InvokeHelper(0x24, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::DorGetDeviceStatus()
{
	long result;
	InvokeHelper(0x25, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::DorGetDoorStatus()
{
	long result;
	InvokeHelper(0x26, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::LgtInitialize()
{
	long result;
	InvokeHelper(0x27, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::LgtDeinitialize()
{
	long result;
	InvokeHelper(0x28, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::LgtSetFlicker(long nIndex, long nValue)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0x29, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nIndex, nValue);
	return result;
}

long CNHMWI::LgtSetIndicator(long nValue)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x2a, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nValue);
	return result;
}

long CNHMWI::McuCancelWaitTaken()
{
	long result;
	InvokeHelper(0x2b, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

CString CNHMWI::McuGetErrorCode()
{
	CString result;
	InvokeHelper(0x2c, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString CNHMWI::SprGetErrorCode()
{
	CString result;
	InvokeHelper(0x2d, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString CNHMWI::JprGetErrorCode()
{
	CString result;
	InvokeHelper(0x2e, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

long CNHMWI::SprClearErrorCode()
{
	long result;
	InvokeHelper(0x2f, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::JprClearErrorCode()
{
	long result;
	InvokeHelper(0x30, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::McuClearErrorCode()
{
	long result;
	InvokeHelper(0x31, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::DorClearErrorCode()
{
	long result;
	InvokeHelper(0x32, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

CString CNHMWI::JprGetSensorInfo()
{
	CString result;
	InvokeHelper(0x33, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString CNHMWI::SprGetSensorInfo()
{
	CString result;
	InvokeHelper(0x34, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString CNHMWI::McuGetSensorInfo()
{
	CString result;
	InvokeHelper(0x35, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

long CNHMWI::SprClearRetractCnt()
{
	long result;
	InvokeHelper(0x36, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::McuClearRetractCnt()
{
	long result;
	InvokeHelper(0x37, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

CString CNHMWI::DorGetErrorCode()
{
	CString result;
	InvokeHelper(0x38, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString CNHMWI::SprGetRetractCnt()
{
	CString result;
	InvokeHelper(0x39, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString CNHMWI::McuGetRetractCnt()
{
	CString result;
	InvokeHelper(0x3a, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

long CNHMWI::ScrInitialize()
{
	long result;
	InvokeHelper(0x3b, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

CString CNHMWI::ScrGetKeyString(long nWaitSec)
{
	CString result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x3c, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		nWaitSec);
	return result;
}

long CNHMWI::ScrSetData(LPCTSTR szDataName, LPCTSTR szDataValue)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x3d, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		szDataName, szDataValue);
	return result;
}

long CNHMWI::ScrDisplayScreen(LPCTSTR szTag, long nIndex, LPCTSTR szData)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4 VTS_BSTR;
	InvokeHelper(0x3e, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		szTag, nIndex, szData);
	return result;
}

long CNHMWI::SprCancelWaitTaken()
{
	long result;
	InvokeHelper(0x3f, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::LgtClearErrorCode()
{
	long result;
	InvokeHelper(0x40, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::LgtGetDeviceStatus()
{
	long result;
	InvokeHelper(0x41, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

CString CNHMWI::LgtGetErrorCode()
{
	CString result;
	InvokeHelper(0x42, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString CNHMWI::ScrGetScreenData(long nWaitSec)
{
	CString result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x43, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		nWaitSec);
	return result;
}

long CNHMWI::ScrSetScreenData(LPCTSTR szDataName, LPCTSTR szDataValue)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x44, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		szDataName, szDataValue);
	return result;
}

long CNHMWI::ScrSetDisplayData(LPCTSTR szDataName, LPCTSTR szDataValue)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x45, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		szDataName, szDataValue);
	return result;
}

CString CNHMWI::ScrGetKeyData(long nWaitSec)
{
	CString result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x46, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		nWaitSec);
	return result;
}

long CNHMWI::ScrClearKeyData()
{
	long result;
	InvokeHelper(0x47, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::GetTimeoutDevice(long nDevID)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x48, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nDevID);
	return result;
}

CString CNHMWI::McuGetICData()
{
	CString result;
	InvokeHelper(0x49, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

long CNHMWI::McuICEntryEnable(long nWaitSec)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x4a, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nWaitSec);
	return result;
}

long CNHMWI::McuICEntryDisable()
{
	long result;
	InvokeHelper(0x4b, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::McuICSendData(long ProtocolID, LPCTSTR szSendData, long nWaitSec)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_BSTR VTS_I4;
	InvokeHelper(0x4c, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		ProtocolID, szSendData, nWaitSec);
	return result;
}

long CNHMWI::McuICChipInitialize()
{
	long result;
	InvokeHelper(0x4d, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::CduInitialize(long InitialType)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x4e, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		InitialType);
	return result;
}

long CNHMWI::CduDeinitialize()
{
	long result;
	InvokeHelper(0x4f, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

CString CNHMWI::CduGetErrorCode()
{
	CString result;
	InvokeHelper(0x50, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

long CNHMWI::CduClearErrorCode()
{
	long result;
	InvokeHelper(0x51, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

CString CNHMWI::CduGetSensorInfo()
{
	CString result;
	InvokeHelper(0x52, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

long CNHMWI::CduGetDeviceStatus()
{
	long result;
	InvokeHelper(0x53, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::CduGetPosition()
{
	long result;
	InvokeHelper(0x54, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::CduGetRejectCSTStatus()
{
	long result;
	InvokeHelper(0x55, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::CduGetRecycleBoxStatus()
{
	long result;
	InvokeHelper(0x56, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::CduGetMaterialInfo()
{
	long result;
	InvokeHelper(0x57, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::CduGetAvailWithdraw()
{
	long result;
	InvokeHelper(0x58, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::CduOpenShutter()
{
	long result;
	InvokeHelper(0x59, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::CduCloseShutter()
{
	long result;
	InvokeHelper(0x5a, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::CduWaitTaken()
{
	long result;
	InvokeHelper(0x5b, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::CduCancelWaitTaken()
{
	long result;
	InvokeHelper(0x5c, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::CduRetract()
{
	long result;
	InvokeHelper(0x5d, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::CduPresent(long nWaitSec)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x5e, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nWaitSec);
	return result;
}

long CNHMWI::PinInitialize()
{
	long result;
	InvokeHelper(0x5f, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::PinDeinitialize()
{
	long result;
	InvokeHelper(0x60, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

CString CNHMWI::PinGetErrorCode()
{
	CString result;
	InvokeHelper(0x61, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

long CNHMWI::PinClearErrorCode()
{
	long result;
	InvokeHelper(0x62, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::PinEntryDisable()
{
	long result;
	InvokeHelper(0x63, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

CString CNHMWI::PinGetPinKeyData()
{
	CString result;
	InvokeHelper(0x64, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

long CNHMWI::CduGetCSTStatus(long nType)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x65, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nType);
	return result;
}

long CNHMWI::CduGetNumberOfCST()
{
	long result;
	InvokeHelper(0x66, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::CduGetValueOfCash(long nCSTNo)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x67, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nCSTNo);
	return result;
}

long CNHMWI::CduGetNumberOfCash(long nCSTNo)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x68, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nCSTNo);
	return result;
}

long CNHMWI::CduGetNumberOfSetCash(long nCSTNo)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x69, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nCSTNo);
	return result;
}

long CNHMWI::CduDispenseCount(long nCST1Cnt, long nCST2Cnt, long nCST3Cnt, long nCST4Cnt)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0x6a, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nCST1Cnt, nCST2Cnt, nCST3Cnt, nCST4Cnt);
	return result;
}

long CNHMWI::CduDispenseAmount(long nAmount)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x6b, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nAmount);
	return result;
}

long CNHMWI::CduDispenseAndPresentAmount(long nAmount, long nWaitSec)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0x6c, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nAmount, nWaitSec);
	return result;
}

long CNHMWI::PinEntryEnable(long nEnableMode, long nMinKeyCount, long nMaxKeyCount, long bAutoEnd, LPCTSTR szActiveKeys, LPCTSTR szTerminatorKeys, LPCTSTR szCardData, long nTimeout)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_BSTR VTS_BSTR VTS_BSTR VTS_I4;
	InvokeHelper(0x6d, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nEnableMode, nMinKeyCount, nMaxKeyCount, bAutoEnd, szActiveKeys, szTerminatorKeys, szCardData, nTimeout);
	return result;
}

long CNHMWI::PinMacingData(LPCTSTR szMacData)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x6e, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		szMacData);
	return result;
}

CString CNHMWI::PinGetMacingData()
{
	CString result;
	InvokeHelper(0x6f, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

long CNHMWI::PinLoadIV(LPCTSTR szKeyName)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x70, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		szKeyName);
	return result;
}

long CNHMWI::PinLoadKey(LPCTSTR szKeyName, LPCTSTR szKeyValue)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x71, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		szKeyName, szKeyValue);
	return result;
}

long CNHMWI::PinGetDeviceStatus()
{
	long result;
	InvokeHelper(0x72, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

CString CNHMWI::CduGetDispenseOfCST(long nAmount)
{
	CString result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x73, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		nAmount);
	return result;
}

long CNHMWI::SnsDeinitialize()
{
	long result;
	InvokeHelper(0x74, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::SnsClearErrorCode()
{
	long result;
	InvokeHelper(0x75, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

CString CNHMWI::SnsGetErrorCode()
{
	CString result;
	InvokeHelper(0x76, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

long CNHMWI::SnsGetDeviceStatus()
{
	long result;
	InvokeHelper(0x77, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::SnsGetOperatorSwitch()
{
	long result;
	InvokeHelper(0x78, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::SnsClearOperatorSwitch()
{
	long result;
	InvokeHelper(0x79, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::ClearEventDevice(long nDevID)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x7a, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nDevID);
	return result;
}

long CNHMWI::ClearStatusDevice(long nDevID)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x7b, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nDevID);
	return result;
}

long CNHMWI::GetEventDevice(long nDevID)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x7c, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nDevID);
	return result;
}

long CNHMWI::GetStatusDevice(long nDevID)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x7d, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nDevID);
	return result;
}

long CNHMWI::CduSetMinMaxCST(LPCTSTR szMinCntData, LPCTSTR szMaxCntData)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x7e, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		szMinCntData, szMaxCntData);
	return result;
}

long CNHMWI::CduSetNumberOfCash(LPCTSTR szCashCntData)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x7f, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		szCashCntData);
	return result;
}

long CNHMWI::CduSetValueOfCash(LPCTSTR szCashValueData)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x80, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		szCashValueData);
	return result;
}

long CNHMWI::SnsInitialize()
{
	long result;
	InvokeHelper(0x81, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::CduGetLastDispensedAmount()
{
	long result;
	InvokeHelper(0x82, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::CduAddNumberOfCash(LPCTSTR szInitialCnt, LPCTSTR szAddCnt)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x83, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		szInitialCnt, szAddCnt);
	return result;
}

long CNHMWI::ProcBackupTrace(LPCTSTR szFileName, long nFileSize)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4;
	InvokeHelper(0x84, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		szFileName, nFileSize);
	return result;
}

long CNHMWI::CduDispenseAndPresentCount(long nCST1Cnt, long nCST2Cnt, long nCST3Cnt, long nCST4Cnt, long nWaitSec)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0x85, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nCST1Cnt, nCST2Cnt, nCST3Cnt, nCST4Cnt, nWaitSec);
	return result;
}

long CNHMWI::PinLoadEncryptedKey(LPCTSTR KeyUse, LPCTSTR strKeyName, LPCTSTR strKeyValue, LPCTSTR strEncKeyName)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x86, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		KeyUse, strKeyName, strKeyValue, strEncKeyName);
	return result;
}

BOOL CNHMWI::CduGetShutterStatus()
{
	BOOL result;
	InvokeHelper(0x87, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

long CNHMWI::SnsGetEnhancedAudio()
{
	long result;
	InvokeHelper(0x88, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::CduGetLastDispensedCount(long nCstNum)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x89, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nCstNum);
	return result;
}

long CNHMWI::McuICChipPower(long nActType)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x8a, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nActType);
	return result;
}
// Get Currency : 2007.11.23 V01.02.19
CString CNHMWI::CduGetCurrencyID(long nCSTNo)
{
	CString result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x8b, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		nCSTNo);
	return result;
}

// [#68] UK HWANG 2008.04.02 EMV Level2 
long CNHMWI::PinBuildPinBlock(LPCTSTR CustomerData, LPCTSTR XORData, short Padchar, LPCTSTR Format, LPCTSTR Key, LPCTSTR KeyEncKey)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_I2 VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x8c, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		CustomerData, XORData, Padchar, Format, Key, KeyEncKey);
	return result;
}
// end of [#68]

// Set Currency : [#514] [MX] 2009.3.10
long CNHMWI::CduSetCurrencyID(LPCTSTR CurrencyID)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x8d, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		CurrencyID);
	return result;
}
// end of [#514]

// [#554] NH KSK 2009.08.10 RKT 관련 함수 추가
long CNHMWI::RKT_ExportRSAIssuerSignedItem(LPCTSTR ExportItemType, LPCTSTR KeyName)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x8e, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		ExportItemType, KeyName);
	return result;
}

// [#GLDV-2797] AU Kook 2020.05.07 Support Host PK Removal
//long CNHMWI::RKT_ImportRSAPublicKey(LPCTSTR Recv_HSM_PublicKey, LPCTSTR Recv_HSM_Signature)
  long CNHMWI::RKT_ImportRSAPublicKey(LPCTSTR Recv_HSM_PublicKey, LPCTSTR Recv_HSM_Signature, LPCTSTR Usage)
// end of [#GLDV-2797]
{
	long result;
// [#GLDV-2797] AU Kook 2020.05.07 Support Host PK Removal
//	static BYTE parms[] = VTS_BSTR VTS_BSTR;
//	InvokeHelper(0x8f, DISPATCH_METHOD, VT_I4, (void*)&result, parms, Recv_HSM_PublicKey, Recv_HSM_Signature);
	static BYTE parms[] = VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x8f, DISPATCH_METHOD, VT_I4, (void*)&result, parms, Recv_HSM_PublicKey, Recv_HSM_Signature, Usage);
// end of [#GLDV-2797]

	return result;
}

long CNHMWI::RKT_StartKeyExchange()
{
	long result;
	InvokeHelper(0x90, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::RKT_ImportRSASignedDESKey(long KeyType, LPCTSTR Recv_EPP_RSACrypt, LPCTSTR Recv_TMK_RSACrypt, LPCTSTR Recv_HSM_Signature)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x91, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		KeyType, Recv_EPP_RSACrypt, Recv_TMK_RSACrypt, Recv_HSM_Signature);
	return result;
}

CString CNHMWI::RKT_GetExportedKey()
{
	CString result;
	InvokeHelper(0x92, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString CNHMWI::RKT_GetExportedSignedValue()
{
	CString result;
	InvokeHelper(0x93, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString CNHMWI::RKT_GetEPP_RandomNumber()
{
	CString result;
	InvokeHelper(0x94, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString CNHMWI::RKT_GetEPP_KCV()
{
	CString result;
	InvokeHelper(0x95, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}
// end of [#554]

CString CNHMWI::EMV_SendRecvMsgWithIFM(long ProtocolID, LPCTSTR szSendData, long nWaitSec)
{
	CString result;
	static BYTE parms[] =
		VTS_I4 VTS_BSTR VTS_I4;
	InvokeHelper(0x96, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		ProtocolID, szSendData, nWaitSec);
	return result;
}

long CNHMWI::SnsGetProximity()
{
	long result;
	InvokeHelper(0x97, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

// [#2057] NH KSK 2011.05.04
long CNHMWI::PinInitializeEDM()
{
	long result;
	InvokeHelper(0x98, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}
// end of [#2057]

// [#2080] NH KSK 2011.07.13
long CNHMWI::RKT_GetExtraCaps()
{
	long result;
	InvokeHelper(0x99, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}
// end of [#2080]

// [#2253] NH KSK 2014.02.21
CString CNHMWI::PIN_GenerateKCV_512K(LPCTSTR KeyName)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x9a, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		KeyName);
	return result;
}
// end of [#2253]

// [#2325] NH KSK 2015.01.21
long CNHMWI::RFIDInitialize()
{
	long result;
	InvokeHelper(0x9b, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}
// end of [#2325]

// [#2325] NH KSK 2015.01.21
long CNHMWI::RFIDDeinitialize()
{
	long result;
	InvokeHelper(0x9c, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}
// end of [#2325]

// [#2325] NH KSK 2015.01.21
CString CNHMWI::RFIDGetErrorCode()
{
	CString result;
	InvokeHelper(0x9d, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}
// end of [#2325]

// [#2325] NH KSK 2015.01.21
long CNHMWI::RFIDClearErrorCode()
{
	long result;
	InvokeHelper(0x9e, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}
// end of [#2325]

// [#2325] NH KSK 2015.01.21
long CNHMWI::RFIDGetDeviceStatus()
{
	long result;
	InvokeHelper(0x9f, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}
// end of [#2325]

// [#2325] NH KSK 2015.01.21
CString CNHMWI::RFIDGetCardData()
{
	CString result;
	InvokeHelper(0xa0, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}
// end of [#2325]

// [#2325] NH KSK 2015.01.21
long CNHMWI::RFIDEntryEnable(long nWaitSec)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xa1, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nWaitSec);
	return result;
}
// end of [#2325]

// [#2325] NH KSK 2015.01.21
long CNHMWI::RFIDEntryDisable()
{
	long result;
	InvokeHelper(0xa2, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}
// end of [#2325]

// [#RWC6-151] US Kook 2020.07.20 TR34
long CNHMWI::PinGetCertificate(LPCTSTR Certificate)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0xa3, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Certificate);
	return result;
}

long CNHMWI::PinInitializeEDMEx(LPCTSTR Indent, LPCTSTR Key)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0xa4, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Indent, Key);
	return result;
}

long CNHMWI::PinImportKeyBlock(LPCTSTR Key, LPCTSTR EncKey, LPCTSTR KeyBlock)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0xa5, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Key, EncKey, KeyBlock);
	return result;
}

long CNHMWI::PinLoadCertificateEx(LPCTSTR LoadOption, LPCTSTR Signer, LPCTSTR CertificateData)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0xa6, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		LoadOption, Signer, CertificateData);
	return result;
}

long CNHMWI::PinImportRSAEncipheredPKCS7KeyEx(LPCTSTR RSAKeyIn, LPCTSTR Key, LPCTSTR Use, LPCTSTR LoadOption)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0xa7, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		RSAKeyIn, Key, Use, LoadOption);
	return result;
}

CString CNHMWI::PinGetCertificateData()
{
	CString result;
	InvokeHelper(0xa8, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString CNHMWI::PinGetCertificateState()
{
	CString result;
	InvokeHelper(0xa9, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

long CNHMWI::PinStartAuthenticateSync(LPCTSTR MethodName, LPCTSTR Parameters)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0xaa, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		MethodName, Parameters);
	return result;
}

CString CNHMWI::PinGetAuthenticateDataToSign()
{
	CString result;
	InvokeHelper(0xab, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString CNHMWI::PinGetAuthenticateSigner()
{
	CString result;
	InvokeHelper(0xac, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

void CNHMWI::PinSetAuthenticateSigner(LPCTSTR Signer)
{
	static BYTE parms[] = VTS_BSTR;
	InvokeHelper(0xad, DISPATCH_METHOD, VT_EMPTY, NULL, parms, Signer);
}

void CNHMWI::PinSetAuthenticateSigKey(LPCTSTR SigKey)
{
	static BYTE parms[] = VTS_BSTR;
	InvokeHelper(0xae, DISPATCH_METHOD, VT_EMPTY, NULL, parms, SigKey);
}

void CNHMWI::PinSetAuthenticateSignedData(LPCTSTR SignedData)
{
	static BYTE parms[] = VTS_BSTR;
	InvokeHelper(0xaf, DISPATCH_METHOD, VT_EMPTY, NULL, parms, SignedData);
}


// [#GLDV-3005] US Kook 2021.11.08 Support Side Car
// From here I'm going to use 176L (0xb0, same as enum definition in NHMWICtl.h, method id in NHMWI.odl) instead of 0xa3 for better readability and less error-prone.
// BCR Functions
long CNHMWI::BcrInitialize()
{
	long result;
	InvokeHelper(176L, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::BcrDeinitialize()
{
	long result;
	InvokeHelper(177L, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

CString CNHMWI::BcrGetErrorCode()
{
	CString result;
	InvokeHelper(178L, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

long CNHMWI::BcrClearErrorCode()
{
	long result;
	InvokeHelper(179L, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::BcrGetDeviceStatus()
{
	long result;
	InvokeHelper(180L, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::BcrSendRawData()
{
	long result;
	InvokeHelper(181L, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::BcrCancelAccept()
{
	long result;
	InvokeHelper(182L, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::BcrReset()
{
	long result;
	InvokeHelper(183L, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

CString CNHMWI::BcrGetBarcodeData()
{
	CString result;
	InvokeHelper(184L, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

// BNA Functions
long CNHMWI::BnaInitialize()
{
	long result;
	InvokeHelper(185L, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::BnaDeinitialize()
{
	long result;
	InvokeHelper(186L, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

CString CNHMWI::BnaGetErrorCode()
{
	CString result;
	InvokeHelper(187L, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

long CNHMWI::BnaClearErrorCode()
{
	long result;
	InvokeHelper(188L, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::BnaGetDeviceStatus()
{
	long result;
	InvokeHelper(189L, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

CString CNHMWI::BnaGetExtraStatus(LPCTSTR KeyName)
{
	CString result;
	static BYTE parms[] = VTS_BSTR;
	InvokeHelper(190L, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms, KeyName);
	return result;
}

long CNHMWI::BnaStartCashIn()
{
	long result;
	InvokeHelper(191L, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::BnaAcceptCash(long InsertionTimeOut, long TakenTimeOut)
{
	long result;
	static BYTE parms[] = VTS_I4 VTS_I4;
	InvokeHelper(192L, DISPATCH_METHOD, VT_I4, (void*)&result, parms, InsertionTimeOut, TakenTimeOut);
	return result;
}

long CNHMWI::BnaCancelAccept()
{
	long result;
	InvokeHelper(193L, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::BnaStoreCash()
{
	long result;
	InvokeHelper(194L, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::BnaRollbackCash(long TakenTimeOut)
{
	long result;
	static BYTE parms[] = VTS_I4;
	InvokeHelper(195L, DISPATCH_METHOD, VT_I4, (void*)&result, parms, TakenTimeOut);
	return result;
}

long CNHMWI::BnaReset(short UnitNumber)
{
	long result;
	static BYTE parms[] = VTS_I2;
	InvokeHelper(196L, DISPATCH_METHOD, VT_I4, (void*)&result, parms, UnitNumber);
	return result;
}

long CNHMWI::BnaConfigureNoteTypeSync()
{
	long result;
	InvokeHelper(197L, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::BnaSetCashUnitInfo()
{
	long result;
	InvokeHelper(198L, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}



CString CNHMWI::BnaGetLastCashInStatus()
{
	CString result;
	InvokeHelper(199L, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

long CNHMWI::BnaGetNumberOfCashInStatus()
{
	long result;
	InvokeHelper(200L, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::BnaGetNumberOfLogicalUnit()
{
	long result;
	InvokeHelper(201L, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

LPDISPATCH CNHMWI::BnaGetCashInStatus(long Index)
{
	LPDISPATCH result;
	static BYTE parms[] = VTS_I4;
	InvokeHelper(202L, DISPATCH_METHOD, VT_DISPATCH, (void*)&result, parms, Index);
	return result;
}

LPDISPATCH CNHMWI::BnaGetLogicalUnit(long Index)
{
	LPDISPATCH result;
	static BYTE parms[] = VTS_I4;
	InvokeHelper(203L, DISPATCH_METHOD, VT_DISPATCH, (void*)&result, parms, Index);
	return result;
}

CString CNHMWI::BnaGetAcceptorStatus()
{
	CString result;
	InvokeHelper(204L, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString CNHMWI::BnaGetStackerStatus()
{
	CString result;
	InvokeHelper(205L, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

long CNHMWI::BnaGetMaxCashInItem()
{
	long result;
	InvokeHelper(206L, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::BnaGetMaxStackerItem()
{
	long result;
	InvokeHelper(207L, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CNHMWI::BnaGetLastRefusedCount()
{
	long result;
	InvokeHelper(208L, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}
// end of [#GLDV-3005]

// [RWC6-676] Start SKKim 2024.05.17
CString CNHMWI::BnaGetPositionStatus()
{
	CString result;
	InvokeHelper(209L, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}
// [RWC6-676] End SKKim 2024.05.17

// [RWC6-676] Start SKKim 2024.05.27
long CNHMWI::BnaGetRefusedStatus()
{
	long result;
	InvokeHelper(210L, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}
// [RWC6-676] End SKKim 2024.05.27


void CNHMWI::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
