#if !defined(AFX_NHMWI_H__B8A03A76_7BEB_4EF2_A33C_59386400747C__INCLUDED_)
#define AFX_NHMWI_H__B8A03A76_7BEB_4EF2_A33C_59386400747C__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CNHMWI wrapper class

class CNHMWI : public CWnd
{
protected:
	DECLARE_DYNCREATE(CNHMWI)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x984454bc, 0x621a, 0x41be, { 0xac, 0x67, 0x63, 0x6c, 0x0, 0x80, 0x1a, 0xfc } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	CString TestMethod(LPCTSTR szParam1, LPCTSTR szParam2, LPCTSTR szParam3);
	void ProcSetDeviceEvent(LPCTSTR szDeviceName, LPCTSTR szEventName, LPCTSTR szEventValue);
	void ProcSetDeviceStatus(LPCTSTR szDeviceName, LPCTSTR szProperty, LPCTSTR szStatus);
	long McuEntryDisable();
	CString McuGetCardData();
	long McuInitialize();
	long McuRead();
	long McuRetract();
	long McuWrite(LPCTSTR szTrackData);
	long SprGetPaperStatus();
	long JprEmbossPrint();
	long JprGetPaperStatus();
	long JprInitialize();
	long McuDeinitialize();
	CString CheckDeviceAction(long nDevID, long nWaitSec);
	long McuWaitTaken();
	long SprDeinitialize();
	long SprWaitTaken();
	long ScanDeviceAction(long nDevID, long nWaitSec, long nEventKind);
	long McuEntryEnable(long nWaitSec);
	long GetErrorDevice(long nDevID);
	long McuGetMaterialInfo();
	long SprGetMaterialInfo();
	long JprGetMaterialInfo();
	long SprInitialize();
	long JprDeinitialize();
	long McuEject(long nWaitSec);
	long SprPrint(LPCTSTR szPrintData);
	long JprPrint(LPCTSTR szPrintData);
	long JprGetDeviceStatus();
	long SprGetDeviceStatus();
	long SprEject(long nWaitSec);
	long SprRetract();
	long McuGetDeviceStatus();
	long DorInitialize();
	long DorDeinitialize();
	long DorGetDeviceStatus();
	long DorGetDoorStatus();
	long LgtInitialize();
	long LgtDeinitialize();
	long LgtSetFlicker(long nIndex, long nValue);
	long LgtSetIndicator(long nValue);
	long McuCancelWaitTaken();
	CString McuGetErrorCode();
	CString SprGetErrorCode();
	CString JprGetErrorCode();
	long SprClearErrorCode();
	long JprClearErrorCode();
	long McuClearErrorCode();
	long DorClearErrorCode();
	CString JprGetSensorInfo();
	CString SprGetSensorInfo();
	CString McuGetSensorInfo();
	long SprClearRetractCnt();
	long McuClearRetractCnt();
	CString DorGetErrorCode();
	CString SprGetRetractCnt();
	CString McuGetRetractCnt();
	long ScrInitialize();
	CString ScrGetKeyString(long nWaitSec);
	long ScrSetData(LPCTSTR szDataName, LPCTSTR szDataValue);
	long ScrDisplayScreen(LPCTSTR szTag, long nIndex, LPCTSTR szData);
	long SprCancelWaitTaken();
	long LgtClearErrorCode();
	long LgtGetDeviceStatus();
	CString LgtGetErrorCode();
	CString ScrGetScreenData(long nWaitSec);
	long ScrSetScreenData(LPCTSTR szDataName, LPCTSTR szDataValue);
	long ScrSetDisplayData(LPCTSTR szDataName, LPCTSTR szDataValue);
	CString ScrGetKeyData(long nWaitSec);
	long ScrClearKeyData();
	long GetTimeoutDevice(long nDevID);
	CString McuGetICData();
	long McuICEntryEnable(long nWaitSec);
	long McuICEntryDisable();
	long McuICSendData(long ProtocolID, LPCTSTR szSendData, long nWaitSec);
	long McuICChipInitialize();
	long CduInitialize(long InitialType);
	long CduDeinitialize();
	CString CduGetErrorCode();
	long CduClearErrorCode();
	CString CduGetSensorInfo();
	long CduGetDeviceStatus();
	long CduGetPosition();
	long CduGetRejectCSTStatus();
	long CduGetRecycleBoxStatus();
	long CduGetMaterialInfo();
	long CduGetAvailWithdraw();
	long CduOpenShutter();
	long CduCloseShutter();
	long CduWaitTaken();
	long CduCancelWaitTaken();
	long CduRetract();
	long CduPresent(long nWaitSec);
	long PinInitialize();
	long PinDeinitialize();
	CString PinGetErrorCode();
	long PinClearErrorCode();
	long PinEntryDisable();
	CString PinGetPinKeyData();
	long CduGetCSTStatus(long nType);
	long CduGetNumberOfCST();
	long CduGetValueOfCash(long nCSTNo);
	long CduGetNumberOfCash(long nCSTNo);
	long CduGetNumberOfSetCash(long nCSTNo);
	long CduDispenseCount(long nCST1Cnt, long nCST2Cnt, long nCST3Cnt, long nCST4Cnt);
	long CduDispenseAmount(long nAmount);
	long CduDispenseAndPresentAmount(long nAmount, long nWaitSec);
	long PinEntryEnable(long nEnableMode, long nMinKeyCount, long nMaxKeyCount, long bAutoEnd, LPCTSTR szActiveKeys, LPCTSTR szTerminatorKeys, LPCTSTR szCardData, long nTimeout);
	long PinMacingData(LPCTSTR szMacData);
	CString PinGetMacingData();
	long PinLoadIV(LPCTSTR szKeyName);
	long PinLoadKey(LPCTSTR szKeyName, LPCTSTR szKeyValue);
	long PinGetDeviceStatus();
	CString CduGetDispenseOfCST(long nAmount);
	long SnsDeinitialize();
	long SnsClearErrorCode();
	CString SnsGetErrorCode();
	long SnsGetDeviceStatus();
	long SnsGetOperatorSwitch();
	long SnsClearOperatorSwitch();
	long ClearEventDevice(long nDevID);
	long ClearStatusDevice(long nDevID);
	long GetEventDevice(long nDevID);
	long GetStatusDevice(long nDevID);
	long CduSetMinMaxCST(LPCTSTR szMinCntData, LPCTSTR szMaxCntData);
	long CduSetNumberOfCash(LPCTSTR szCashCntData);
	long CduSetValueOfCash(LPCTSTR szCashValueData);
	long SnsInitialize();
	long CduGetLastDispensedAmount();
	long CduAddNumberOfCash(LPCTSTR szInitialCnt, LPCTSTR szAddCnt);
	long ProcBackupTrace(LPCTSTR szFileName, long nFileSize);
	long CduDispenseAndPresentCount(long nCST1Cnt, long nCST2Cnt, long nCST3Cnt, long nCST4Cnt, long nWaitSec);
	long PinLoadEncryptedKey(LPCTSTR KeyUse, LPCTSTR strKeyName, LPCTSTR strKeyValue, LPCTSTR strEncKeyName);
	BOOL CduGetShutterStatus();
	long SnsGetEnhancedAudio();
	long CduGetLastDispensedCount(long nCstNum);

	long McuICChipPower(long nActType);
	CString CduGetCurrencyID(long nCSTNo);
	long PinBuildPinBlock(LPCTSTR CustomerData, LPCTSTR XORData, short Padchar, LPCTSTR Format, LPCTSTR Key, LPCTSTR KeyEncKey);
	long CduSetCurrencyID(LPCTSTR CurrencyID);
	long RKT_ExportRSAIssuerSignedItem(LPCTSTR ExportItemType, LPCTSTR KeyName);
// [#GLDV-2797] AU Kook 2020.04.28 Support Host PK Removal
//	long RKT_ImportRSAPublicKey(LPCTSTR Recv_HSM_PublicKey, LPCTSTR Recv_HSM_Signature);
	long RKT_ImportRSAPublicKey(LPCTSTR Recv_HSM_PublicKey, LPCTSTR Recv_HSM_Signature, LPCTSTR Usage);
// end of [#GLDV-2797]
	long RKT_StartKeyExchange();
	long RKT_ImportRSASignedDESKey(long KeyType, LPCTSTR Recv_EPP_RSACrypt, LPCTSTR Recv_TMK_RSACrypt, LPCTSTR Recv_HSM_Signature);
	CString RKT_GetExportedKey();
	CString RKT_GetExportedSignedValue();
	CString RKT_GetEPP_RandomNumber();
	CString RKT_GetEPP_KCV();
	CString	EMV_SendRecvMsgWithIFM(long ProtocolID, LPCTSTR szSendData, long nWaitSec);
	long SnsGetProximity();
	long PinInitializeEDM();
	long RKT_GetExtraCaps();
	CString PIN_GenerateKCV_512K(LPCTSTR KeyName);

	// [#2325] NH KSK 2015.01.20
	long RFIDInitialize();
	long RFIDDeinitialize();
	CString RFIDGetErrorCode();
	long RFIDClearErrorCode();
	long RFIDGetDeviceStatus();
	CString RFIDGetCardData();
	long RFIDEntryEnable(long nWaitSec);
	long RFIDEntryDisable();
	// end of [#2325]

	// [#RWC6-151] US Kook 2020.07.20 TR34
	long PinGetCertificate(LPCTSTR Certificate);
	CString PinGetCertificateData();
	CString PinGetCertificateState();
	long PinInitializeEDMEx(LPCTSTR Indent, LPCTSTR Key);
	long PinImportKeyBlock(LPCTSTR Key, LPCTSTR EncKey, LPCTSTR KeyBlock);
	long PinLoadCertificateEx(LPCTSTR LoadOption, LPCTSTR Signer, LPCTSTR CertificateData);
	long PinImportRSAEncipheredPKCS7KeyEx(LPCTSTR RSAKeyIn, LPCTSTR Key, LPCTSTR Use, LPCTSTR LoadOption);
	long PinStartAuthenticateSync(LPCTSTR MethodName, LPCTSTR Parameters);

	CString PinGetAuthenticateDataToSign();
	CString PinGetAuthenticateSigner();
	void PinSetAuthenticateSigner(LPCTSTR Signer);
	void PinSetAuthenticateSigKey(LPCTSTR SigKey);
	void PinSetAuthenticateSignedData(LPCTSTR SignedData);
	// [#GLDV-3005] US Kook 2021.11.08 Support Side Car
	// BCR
	long BcrInitialize();
	long BcrDeinitialize();
	CString BcrGetErrorCode();
	long BcrClearErrorCode();
	long BcrGetDeviceStatus();
	long BcrSendRawData();
	long BcrCancelAccept();
	long BcrReset();
	CString BcrGetBarcodeData();

	//// BNA: TODO
	long BnaInitialize();
	long BnaDeinitialize();
	CString BnaGetErrorCode();
	long BnaClearErrorCode();
	long BnaGetDeviceStatus();
	CString BnaGetExtraStatus(LPCTSTR KeyName);
	long BnaStartCashIn();
	long BnaAcceptCash(long InsertionTimeOut, long TakenTimeOut);
	long BnaCancelAccept();
	long BnaStoreCash();
	long BnaRollbackCash(long TakenTimeOut);
	//long BnaRetract(short RetractAreas);
	//long BnaOpenShutter(BOOL Position);
	//long BnaCloseShutter(BOOL Position);
	//long BnaStartExchangeSync(VARIANT CashUnitToExchange);
	//long BnaEndExchangeSync();
	//long BnaOpenSafeDoor();
	long BnaReset(short UnitNumber);
	long BnaConfigureNoteTypeSync();
	//long BnaCreateP6Signature(long InsertionTimeOut, long TakenTimeOut);
	//long BnaGetP6Signautre(BSTR Level, short Index);
	//long BnaConfigureCashUnitSync(short Number, BSTR Type, VARIANT NoteIDs);
	long BnaSetCashUnitInfo();
	////long BnaSetCashInLimit(long TotalItemsLimit, BSTR CurrencyID, long Amount);
	CString BnaGetAcceptorStatus();
	CString BnaGetStackerStatus();
	long BnaGetMaxCashInItem();
	long BnaGetMaxStackerItem();
	long BnaGetLastRefusedCount();

	CString BnaGetLastCashInStatus();
	long BnaGetNumberOfCashInStatus();
	long BnaGetNumberOfLogicalUnit();
	LPDISPATCH BnaGetCashInStatus(long Index);
	LPDISPATCH BnaGetLogicalUnit(long Index);
	// end of [#GLDV-3005]

	CString BnaGetPositionStatus();	// [RWC6-676] SKKim 2024.05.17
	long	BnaGetRefusedStatus();  // [RWC6-676] SKKim 2024.05.27

	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_NHMWI_H__B8A03A76_7BEB_4EF2_A33C_59386400747C__INCLUDED_)
