#ifndef __TRAN_BIZ_DEF_H__
#define __TRAN_BIZ_DEF_H__

// [#2150] US Justin 2012.10.03 Add Surcharge display option
#define	SURCHARGE_DISP_NORMAL			0
#define	SURCHARGE_DISP_PRECENT			1
#define	SURCHARGE_DISP_TABLE			2
#define	SURCHARGE_DISP_DYNAMIC1ST		3
#define	SURCHARGE_DISP_DYNAMIC2ND		4
#define	SURCHARGE_DISP_DYNAMICDCC		5
#define	SURCHARGE_DISP_BALANCEINQUIRY	6
#define	SURCHARGE_DISP_PINCHANGE		7
// End of [#2150]
// [#2292] US Justin 2014.09.30 Add TDL
#define	SURCHARGE_DISP_TDL_SEGMENTATION	8
#define	SURCHARGE_DISP_TDL_DCC			9
// End of [#2292]

#define	SURCHARGE_DISP_UNDER_BINRANGE	10

typedef enum BIZ_RETURN
{
	RES_OK = 0,
	RES_NG = 1,

	// Pre-Balance User Input
	RES_YES,
	RES_NO,

	// Result of User Input
	RES_USER_EXIT,		// User select Exit.
	RES_USER_PREV,		// User select Prev.
	RES_USER_TIMEOUT,	// User Timeout

	// Result of Card Read
	RES_CARD_ERROR,			// Card Data Error
	RES_CARD_MOD_10,		// Mode 10 Error
	RES_CARD_BIN_NG,		// BIN Error

	// Result of CDU Capability
	RES_CASH_NOT_AVAILABLE,	// Cash is not available
	RES_CASH_RETRY_OVER,	// Retry Over
	RES_CASH_MAX_OVER,		// Max Over
	RES_CASH_MIN_OVER,		// Min Over
	RES_PROGRAM_ERROR,

	// Result of Host Communication
	RES_HOST_SEND_ERR,	// Error in Send data
	RES_HOST_RECV_ERR,	// Error in Recv data
	RES_HOST_DENIED,	// Host Denied.

	// Result of Device Action
	RES_DEV_CDU_ERR_PARTIAL,
	RES_DEV_CDU_ERR,
	RES_DEV_SPR_ERR,

	// Result EMV Action
	RES_INIT,
	RES_NOR_MS_TRANS,
	RES_EMV_IC_FIRST,
	RES_EMV_MS_FIRST,
	RES_EMV_FALLBACK,
	RES_CHECK_ICREADER,
	RES_MAKE_AID,
	RES_EMV_TERMINATE,
	RES_AID_SELECT,
	RES_MULTI_AID_SELECT,
	RES_LANGUAGE_SELECT,
	RES_PASSWORD_INPUT,
	RES_EMV_PROCESSING_ERROR,
	RES_EMV_ERROR_REVERSAL,
	RES_EMV_FALLBACK_DISABLED,		// [#2554] NH Justin 2018.06.05 Change Fallback Disabled Error Message

	RES_lottery_dep0,
	RES_lottery_dep1,
	RES_lottery_dep2,
	RES_lottery_dep3,

	// [#2144] US Justin 2012.08.30 Add 3rd Party Biz Return
	RES_ATM_READCARD_NORMAL,
	RES_ATM_READCARD_CANCEL,
	RES_ATM_READCARD_TIMEOUT,
	// End of [#2144]

	// [#2150] US Justin 2012.10.01 Add Dynamic Flow, DCC WD option, PIN Change Cancel option
	RES_DCC_USE_LOCALCURRENCY,
	RES_DCC_USE_HOMECURRENCY,
	RES_PINCHANGE_SAMEASORIGINAL,
	RES_PINCHANGE_DIFFERENTPIN,
	// End of [#2150]

	//RES_DAMAGED_ICCARD,			// [#2159] MX Justin 2012.10.26 Cancel transaction for damaged IC card => [#2285] NH Justin 2014.07.09 Remove Damaged Card Restriction

	RES_CARDLESS_PIN4,				// [#2396] US Justin 2016.02.10 Add PIN4
	RES_CARDLESS_POPMONEY,			// [#2396] US Justin 2016.02.10 Add POPMONEY
	RES_CARDLESS_JUSTCASH,			// [#2445] US Justin 2016.09.22 Add Just.Cash
	RES_CARDLESS_PAYPAL,			// [#2446] US Justin 2016.09.29 Paypal CCA
	RES_CARDLESS_LIBERTYX,			// [#RWC6-59] US William 2019.10.14 LibertyX
	RES_CARDLESS_DIGITALMINT,

	RES_GIVEPAY_FINALSELECT,		// [#2530] US Justin 2018.01.24 GivePay
	RES_GIVEPAY_VIEWTNC,			// [#2557] NH Justin 2018.06.25 GivePay Enhancement 

	RES_DENOMINATION_SELECT,		// [#RWC6-12] Denomination Selection Support

	RES_CARDLESS_B4U,				// [#RWC6-16] Bitload4U

	RES_BITCOIN_B4U,				// [#RWC6-68] PAI Bitcoin button
	RES_BITCOIN_LIBERTYX_BUY,		// [#RWC6-59] US William 2019.10.14 LibertyX
	RES_BITCOIN_LIBERTYX_SELL,		// [#RWC6-59] US William 2020.10.16 LibertyX
	RES_LIBERTYX_BTC,
	RES_LIBERTYX_BILLPAY,
	RES_LIBERTYX_AUTH_FAIL,
	RES_LIBERTYX_DEBIT_FAIL,
	RES_LIBERTYX_EXEC_FAIL,

	RES_TANGOPAY_CHECKSUM_ERR,		// [RWC6-676] SKKim 2024.04.01
	RES_TANGOPAY_PRINTRECEIPT,		// [RWC6-676] SKKim 2024.04.23
	RES_RESPONSE_ERROR,				// [RWC6-676] SKKim 2024.05.09

	MAX_OF_RES
};

typedef enum FLOW_ID
{
	FID_END_OF_FLOW			= 0,

	FID_NH_NOR_CLEANUP,

	// Normal Flow
	FID_NH_NOR_FLOWS		= 1000,
	FID_NH_NOR_COMMON,
	FID_NH_NOR_PREBALANCE,				// [iTM] KSK 2010.01.25
	FID_NH_NOR_SELECTTRAN,
	FID_NH_NOR_WITHDRAWAL,
	FID_NH_NOR_INQUIRY,
	FID_NH_NOR_TRANSFER,
	FID_NH_NOR_PINCHANGE,				// [#2150] US Justin 2012.10.04 Dynamic Flow ... Add Pin Change
	FID_NH_NOR_REVERSAL,
	FID_NH_NOR_RECEIPT,
	FID_NH_NOR_CANCEL,
	FID_NH_NOR_EXIT,

	FID_MX_NOR_COMMON,					// [#2137] MX PCS 2012.07.24
	FID_MX_NOR_WITHDRAWAL,
	FID_MX_NOR_INQUIRY,

	FID_NH_NOR_POWEROFF_REVERSAL,

	// Addon AP
	FID_NH_NOR_READCARD		= 2000,		// [#2144] US Justin 2012.08.30 Add 3rd party application ID ( 4000 ~ )
	FID_NH_POPMONEY_FLOWS,				// [#2350] US Justin 2015.06.17 POP Money
	FID_NH_CCW_FLOWS,
	FID_NH_PIN4_FLOWS,					// [#2396] US Justin 2016.02.10 PIN4 Flow
	FID_NH_CARDLESS_FLOWS,				// [#2385] US Justin 2016.02.10 PIN4 Flow
	FID_NH_PAYPAL_FLOWS,				// [#2446] US Justin 2016.09.29 Paypal CCA Flow
	FID_NH_BITCOIN_SVC_FLOWS,			// [#RWC6-68] Bitcoin button

	// [#RWC6-16] Bitload4U
	FID_NH_B4U_REQ_INFO_FLOWS,			
	FID_NH_B4U_QR_FLOWS,				
	FID_NH_B4U_FAIL_FLOWS,				
	FID_NH_B4U_CANCEL_FLOWS,				
	FID_NH_B4U_TIMEOUT_FLOWS,				
	FID_NH_B4U_AUTH_FLOWS,				
	FID_NH_B4U_SUCCESS_FLOWS,			
	FID_NH_B4U_FINALIZE_FLOWS,
	FID_NH_B4U_TERMINATE_FLOWS,
	// end of [#RWC-16]

	// EMV Mode Flow
	FID_CHECK_ICREADER		= 8000,
	FID_FALLBACK,
	FID_LANGUAGE_SELECT,
	FID_AIDLIST_SELECT,
	FID_PASSWORD_INPUT,
	FID_PREBALANCE,
	FID_TRANSACTION_SELECT,
	FID_EXIT_STATE,

	// ADA Mode Flow
	FID_NH_ADA_FLOWS		= 9000,
	FID_NH_ADA_COMMON,
	FID_NH_ADA_WITHDRAWAL,
	FID_NH_ADA_INQUIRY,
	FID_NH_ADA_TRANSFER,
	FID_NH_ADA_REVERSAL,
	FID_NH_ADA_RECEIPT,
	FID_NH_ADA_CANCEL,
	FID_NH_ADA_EXIT,

	FID_NH_GPAY_RETURN2MAIN_FLOWS,			// [#2557] US Justin 2018.6.21

	
	// [#RWC6-59] US William 2019.10.09 LibertyX
	// LibertyX
	FID_NH_LIBERTYX_INIT		= 10000,		
	FID_NH_LIBERTYX_PURCHASE,
	FID_NH_LIBERTYX_DISPENSE,  // [#RWC6-224] US William 2020.10.12 LibertyX Dispense

	// Just.Cash
	FID_NH_JUSTCASH_START,
	FID_NH_JUSTCASH_GREET,
	FID_NH_JUSTCASH_TRANSACTION,
	FID_NH_JUSTCASH_CARDLESS_TRANSACTION,
	FID_NH_JUSTCASH_DEBIT,
	FID_NH_JUSTCASH_ACCEPT_CASH,
	FID_NH_JUSTCASH_END_TRANSACTION,
	FID_NH_JUSTCASH_CANCEL_TRANSACTION,
	FID_NH_JUSTCASH_CLEANUP,

	// DigitalMint
	FID_NH_DIGITALMINT_START,
	FID_NH_DIGITALMINT_GREET,
	FID_NH_DIGITALMINT_TRANSACTION,
	FID_NH_DIGITALMINT_DEBIT,
	FID_NH_DIGITALMINT_ACCEPT_CASH,
	FID_NH_DIGITALMINT_END_TRANSACTION,
	FID_NH_DIGITALMINT_CANCEL_TRANSACTION,
	FID_NH_DIGITALMINT_CLEANUP,

	// Cash Depot
	FID_NH_CASHDEPOT_START,
	FID_NH_CASHDEPOT_GREET,
	FID_NH_CASHDEPOT_TRANSACTION,
	FID_NH_CASHDEPOT_DEBIT,
	FID_NH_CASHDEPOT_END_TRANSACTION,
	FID_NH_CASHDEPOT_CANCEL_TRANSACTION,
	FID_NH_CASHDEPOT_CLEANUP,

	// [RWC6-676] Start SKKim 2024.04.09
	FID_NH_TANGOPAY_START,
	FID_NH_TANGOPAY_PRESTAGING,
	FID_NH_TANGOPAY_ACCEPTCASH,
	FID_NH_TANGOPAY_END,

	FID_NH_TANGOPAY_CANCEL,
	FID_NH_TANGOPAY_CLEANUP,
	// [RWC6-676] End SKKim 2024.04.09

	MAX_OF_FLOW
};

typedef enum PRE_BALANCE_STATUS
{
	PRE_BAL_NONE	= 0,		// Pre balance not start
	PRE_BAL_START,				// pre balance start
	PRE_BAL_ANOTHER,			// after pre balance, start another transaction
};

////////////////////////////////////////////////////////////////////////////////
struct S_WEATHER_INFO
{
	int		nYear;
	int		nMonth;
	int		nDay;
	CString strDayOfWeek;
	int		nWeatherCode;
//	CString	strWeatherUnit;
	CString	strTemperatureType;		// KSK 2010.06.21 RMS 사양 맞추기 위해 변수 Name 변경
//	int		nMax;
//	int		nMin;
	int		nHighestTemp;
	int		nLowestTemp;
};

struct S_NOTICE_INFO
{
	CString		strTitle;
	CString		strLine1;
	CString		strLine2;
	CString		strLine3;
};

#endif // __TRAN_BIZ_DEF_H__