sonar.projectKey=retail-ce-6.0_moniplus2ce_AX6hDtU4V0YOU2wUxaPO
sonar.cfamily.threads=2
sonar.cfamily.cache.enabled=true
sonar.cfamily.cache.path=./.sonar-cache
sonar.exclusions=App/H/curl/**,App/H/parson/**,App/Dll/NetCtrl/Include/**,**/zip.cpp,**/zip.h,App/Dll/CmnLib/LibQREncode/**,App/Dll/CmnLib/crypto_blowfish/**