//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EagleCE_ATM.rc
//
#define IDD_EAGLECE_ATM_DIALOG          102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_SSL_TERMINAL_CERTIFICATE    130
#define IDR_SSL_TERMINAL_PRIVATEKEY     131
#define IDR_SSL_AMS_CERTIFICATE         132
#define IDR_DEFAULT_CONFIG_ADS          133
#define IDR_DEFAULT_CONFIG_BINLIST      134
#define IDR_DEFAULT_CONFIG_CBXINFO      135
#define IDR_DEFAULT_CONFIG_DEVICE       136
#define IDR_DEFAULT_CONFIG_DISPENSE     137
#define IDR_DEFAULT_CONFIG_EMV          138
#define IDR_DEFAULT_CONFIG_EMV_US       139
#define IDR_DEFAULT_CONFIG_HOST         140
#define IDR_DEFAULT_CONFIG_LASTTRANS    141
#define IDR_DEFAULT_CONFIG_MESSAGE      143
#define IDR_DEFAULT_CONFIG_OPTION       144
#define IDR_DEFAULT_CONFIG_SYSTEM       145
#define IDR_DEFAULT_CONFIG_TOTAL        146

#define IDR_MAINFRAME                   999

#define IDR_CS130_SCREEN_OP_DESIGN			2001
#define IDR_CS130_SCREEN_CLIENT_CTRL		2002
#define IDR_CS130_SCREEN_CLIENT_ADV_CTRL	2003
#define IDR_CS130_TEXT_CLIENT_HOST_ERROR	2004
#define IDR_CS130_TEXT_CLIENT_RECEIPTPRINT	2005
#define IDR_MF200_SCREEN_OP_DESIGN			2101
#define IDR_MF200_SCREEN_CLIENT_CTRL		2102
#define IDR_MF200_SCREEN_CLIENT_ADV_CTRL	2103
#define IDR_MF200_TEXT_CLIENT_HOST_ERROR	2104
#define IDR_MF200_TEXT_CLIENT_RECEIPTPRINT	2105

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        133
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
