#pragma once

//
// DEVICE 변경 메세지
//
typedef enum
{
	EAGLE_ATM_DEV_DIO_STATUS_CHANGED = 0,
	EAGLE_ATM_DEV_DIO_FRONT_DOOR,
	EAGLE_ATM_DEV_DIO_SAFE_DOOR,
	EAGLE_ATM_DEV_DIO_UPPER_FRAME,
	EAGLE_ATM_DEV_DIO_EAR_JACK,
	EAGLE_ATM_DEV_PRT_STATUS_CHANGED,

	EAGLE_ATM_DEV_USBMEM_INSERTED,
	EAGLE_ATM_DEV_USBMEM_REMOVED,

	EAGLE_ATM_DEV_AMS_LISTEN_START,
	EAGLE_ATM_DEV_AMS_CLOSE_START,

}SVC_DEVICE_STATUS_CHANGE_MESSAGE;


//
// 서비스 MODE 정의
//
#define EAGLE_ATM_SVC_IN_SERVICE					0x0001
#define EAGLE_ATM_SVC_OUT_OF_SERVICE				0x0002
#define EAGLE_ATM_SVC_SUPERVISOR_SERVICE			0x0003	// Added Supervisor Service
#define EAGLE_ATM_SVC_REMOTE_ACCESS_OF_SERVICE		0x0004	// Added Remote Access Service


//
// 계원 모드 권한 정의
//
#define EAGLE_ATM_SVC_MASTER						0x0001
#define EAGLE_ATM_SVC_ADMIN							0x0002
#define EAGLE_ATM_SVC_REPLENISH						0x0003


#define		MAX_PAGE_COUNT		10

